export type City = {
  slug: string;
  city: string;
  state: string;
  population: number;
};

/** Real US city data (top 935 by population), sourced from a public census-derived
 * dataset — used only for honest nationwide-shipping-coverage pages, never to imply
 * a local office or physical presence CIRRUS doesn't have. */
export const CITIES: City[] = [
  { slug: "new-york-new-york", city: "New York", state: "New York", population: 8405837 },
  { slug: "los-angeles-california", city: "Los Angeles", state: "California", population: 3884307 },
  { slug: "chicago-illinois", city: "Chicago", state: "Illinois", population: 2718782 },
  { slug: "houston-texas", city: "Houston", state: "Texas", population: 2195914 },
  { slug: "philadelphia-pennsylvania", city: "Philadelphia", state: "Pennsylvania", population: 1553165 },
  { slug: "phoenix-arizona", city: "Phoenix", state: "Arizona", population: 1513367 },
  { slug: "san-antonio-texas", city: "San Antonio", state: "Texas", population: 1409019 },
  { slug: "san-diego-california", city: "San Diego", state: "California", population: 1355896 },
  { slug: "dallas-texas", city: "Dallas", state: "Texas", population: 1257676 },
  { slug: "san-jose-california", city: "San Jose", state: "California", population: 998537 },
  { slug: "austin-texas", city: "Austin", state: "Texas", population: 885400 },
  { slug: "indianapolis-indiana", city: "Indianapolis", state: "Indiana", population: 843393 },
  { slug: "jacksonville-florida", city: "Jacksonville", state: "Florida", population: 842583 },
  { slug: "san-francisco-california", city: "San Francisco", state: "California", population: 837442 },
  { slug: "columbus-ohio", city: "Columbus", state: "Ohio", population: 822553 },
  { slug: "charlotte-north-carolina", city: "Charlotte", state: "North Carolina", population: 792862 },
  { slug: "fort-worth-texas", city: "Fort Worth", state: "Texas", population: 792727 },
  { slug: "detroit-michigan", city: "Detroit", state: "Michigan", population: 688701 },
  { slug: "el-paso-texas", city: "El Paso", state: "Texas", population: 674433 },
  { slug: "memphis-tennessee", city: "Memphis", state: "Tennessee", population: 653450 },
  { slug: "seattle-washington", city: "Seattle", state: "Washington", population: 652405 },
  { slug: "denver-colorado", city: "Denver", state: "Colorado", population: 649495 },
  { slug: "washington-district-of-columbia", city: "Washington", state: "District of Columbia", population: 646449 },
  { slug: "boston-massachusetts", city: "Boston", state: "Massachusetts", population: 645966 },
  { slug: "nashville-tennessee", city: "Nashville", state: "Tennessee", population: 634464 },
  { slug: "baltimore-maryland", city: "Baltimore", state: "Maryland", population: 622104 },
  { slug: "oklahoma-city-oklahoma", city: "Oklahoma City", state: "Oklahoma", population: 610613 },
  { slug: "louisville-kentucky", city: "Louisville", state: "Kentucky", population: 609893 },
  { slug: "portland-oregon", city: "Portland", state: "Oregon", population: 609456 },
  { slug: "las-vegas-nevada", city: "Las Vegas", state: "Nevada", population: 603488 },
  { slug: "milwaukee-wisconsin", city: "Milwaukee", state: "Wisconsin", population: 599164 },
  { slug: "albuquerque-new-mexico", city: "Albuquerque", state: "New Mexico", population: 556495 },
  { slug: "tucson-arizona", city: "Tucson", state: "Arizona", population: 526116 },
  { slug: "fresno-california", city: "Fresno", state: "California", population: 509924 },
  { slug: "sacramento-california", city: "Sacramento", state: "California", population: 479686 },
  { slug: "long-beach-california", city: "Long Beach", state: "California", population: 469428 },
  { slug: "kansas-city-missouri", city: "Kansas City", state: "Missouri", population: 467007 },
  { slug: "mesa-arizona", city: "Mesa", state: "Arizona", population: 457587 },
  { slug: "virginia-beach-virginia", city: "Virginia Beach", state: "Virginia", population: 448479 },
  { slug: "atlanta-georgia", city: "Atlanta", state: "Georgia", population: 447841 },
  { slug: "colorado-springs-colorado", city: "Colorado Springs", state: "Colorado", population: 439886 },
  { slug: "omaha-nebraska", city: "Omaha", state: "Nebraska", population: 434353 },
  { slug: "raleigh-north-carolina", city: "Raleigh", state: "North Carolina", population: 431746 },
  { slug: "miami-florida", city: "Miami", state: "Florida", population: 417650 },
  { slug: "oakland-california", city: "Oakland", state: "California", population: 406253 },
  { slug: "minneapolis-minnesota", city: "Minneapolis", state: "Minnesota", population: 400070 },
  { slug: "tulsa-oklahoma", city: "Tulsa", state: "Oklahoma", population: 398121 },
  { slug: "cleveland-ohio", city: "Cleveland", state: "Ohio", population: 390113 },
  { slug: "wichita-kansas", city: "Wichita", state: "Kansas", population: 386552 },
  { slug: "arlington-texas", city: "Arlington", state: "Texas", population: 379577 },
  { slug: "new-orleans-louisiana", city: "New Orleans", state: "Louisiana", population: 378715 },
  { slug: "bakersfield-california", city: "Bakersfield", state: "California", population: 363630 },
  { slug: "tampa-florida", city: "Tampa", state: "Florida", population: 352957 },
  { slug: "honolulu-hawaii", city: "Honolulu", state: "Hawaii", population: 347884 },
  { slug: "aurora-colorado", city: "Aurora", state: "Colorado", population: 345803 },
  { slug: "anaheim-california", city: "Anaheim", state: "California", population: 345012 },
  { slug: "santa-ana-california", city: "Santa Ana", state: "California", population: 334227 },
  { slug: "st--louis-missouri", city: "St. Louis", state: "Missouri", population: 318416 },
  { slug: "riverside-california", city: "Riverside", state: "California", population: 316619 },
  { slug: "corpus-christi-texas", city: "Corpus Christi", state: "Texas", population: 316381 },
  { slug: "lexington-fayette-kentucky", city: "Lexington-Fayette", state: "Kentucky", population: 308428 },
  { slug: "pittsburgh-pennsylvania", city: "Pittsburgh", state: "Pennsylvania", population: 305841 },
  { slug: "anchorage-alaska", city: "Anchorage", state: "Alaska", population: 300950 },
  { slug: "stockton-california", city: "Stockton", state: "California", population: 298118 },
  { slug: "cincinnati-ohio", city: "Cincinnati", state: "Ohio", population: 297517 },
  { slug: "st--paul-minnesota", city: "St. Paul", state: "Minnesota", population: 294873 },
  { slug: "toledo-ohio", city: "Toledo", state: "Ohio", population: 282313 },
  { slug: "greensboro-north-carolina", city: "Greensboro", state: "North Carolina", population: 279639 },
  { slug: "newark-new-jersey", city: "Newark", state: "New Jersey", population: 278427 },
  { slug: "plano-texas", city: "Plano", state: "Texas", population: 274409 },
  { slug: "henderson-nevada", city: "Henderson", state: "Nevada", population: 270811 },
  { slug: "lincoln-nebraska", city: "Lincoln", state: "Nebraska", population: 268738 },
  { slug: "buffalo-new-york", city: "Buffalo", state: "New York", population: 258959 },
  { slug: "jersey-city-new-jersey", city: "Jersey City", state: "New Jersey", population: 257342 },
  { slug: "chula-vista-california", city: "Chula Vista", state: "California", population: 256780 },
  { slug: "fort-wayne-indiana", city: "Fort Wayne", state: "Indiana", population: 256496 },
  { slug: "orlando-florida", city: "Orlando", state: "Florida", population: 255483 },
  { slug: "st--petersburg-florida", city: "St. Petersburg", state: "Florida", population: 249688 },
  { slug: "chandler-arizona", city: "Chandler", state: "Arizona", population: 249146 },
  { slug: "laredo-texas", city: "Laredo", state: "Texas", population: 248142 },
  { slug: "norfolk-virginia", city: "Norfolk", state: "Virginia", population: 246139 },
  { slug: "durham-north-carolina", city: "Durham", state: "North Carolina", population: 245475 },
  { slug: "madison-wisconsin", city: "Madison", state: "Wisconsin", population: 243344 },
  { slug: "lubbock-texas", city: "Lubbock", state: "Texas", population: 239538 },
  { slug: "irvine-california", city: "Irvine", state: "California", population: 236716 },
  { slug: "winston-salem-north-carolina", city: "Winston-Salem", state: "North Carolina", population: 236441 },
  { slug: "glendale-arizona", city: "Glendale", state: "Arizona", population: 234632 },
  { slug: "garland-texas", city: "Garland", state: "Texas", population: 234566 },
  { slug: "hialeah-florida", city: "Hialeah", state: "Florida", population: 233394 },
  { slug: "reno-nevada", city: "Reno", state: "Nevada", population: 233294 },
  { slug: "chesapeake-virginia", city: "Chesapeake", state: "Virginia", population: 230571 },
  { slug: "gilbert-arizona", city: "Gilbert", state: "Arizona", population: 229972 },
  { slug: "baton-rouge-louisiana", city: "Baton Rouge", state: "Louisiana", population: 229426 },
  { slug: "irving-texas", city: "Irving", state: "Texas", population: 228653 },
  { slug: "scottsdale-arizona", city: "Scottsdale", state: "Arizona", population: 226918 },
  { slug: "north-las-vegas-nevada", city: "North Las Vegas", state: "Nevada", population: 226877 },
  { slug: "fremont-california", city: "Fremont", state: "California", population: 224922 },
  { slug: "boise-city-idaho", city: "Boise City", state: "Idaho", population: 214237 },
  { slug: "richmond-virginia", city: "Richmond", state: "Virginia", population: 214114 },
  { slug: "san-bernardino-california", city: "San Bernardino", state: "California", population: 213708 },
  { slug: "birmingham-alabama", city: "Birmingham", state: "Alabama", population: 212113 },
  { slug: "spokane-washington", city: "Spokane", state: "Washington", population: 210721 },
  { slug: "rochester-new-york", city: "Rochester", state: "New York", population: 210358 },
  { slug: "des-moines-iowa", city: "Des Moines", state: "Iowa", population: 207510 },
  { slug: "modesto-california", city: "Modesto", state: "California", population: 204933 },
  { slug: "fayetteville-north-carolina", city: "Fayetteville", state: "North Carolina", population: 204408 },
  { slug: "tacoma-washington", city: "Tacoma", state: "Washington", population: 203446 },
  { slug: "oxnard-california", city: "Oxnard", state: "California", population: 203007 },
  { slug: "fontana-california", city: "Fontana", state: "California", population: 203003 },
  { slug: "columbus-georgia", city: "Columbus", state: "Georgia", population: 202824 },
  { slug: "montgomery-alabama", city: "Montgomery", state: "Alabama", population: 201332 },
  { slug: "moreno-valley-california", city: "Moreno Valley", state: "California", population: 201175 },
  { slug: "shreveport-louisiana", city: "Shreveport", state: "Louisiana", population: 200327 },
  { slug: "aurora-illinois", city: "Aurora", state: "Illinois", population: 199963 },
  { slug: "yonkers-new-york", city: "Yonkers", state: "New York", population: 199766 },
  { slug: "akron-ohio", city: "Akron", state: "Ohio", population: 198100 },
  { slug: "huntington-beach-california", city: "Huntington Beach", state: "California", population: 197575 },
  { slug: "little-rock-arkansas", city: "Little Rock", state: "Arkansas", population: 197357 },
  { slug: "augusta-richmond-county-georgia", city: "Augusta-Richmond County", state: "Georgia", population: 197350 },
  { slug: "amarillo-texas", city: "Amarillo", state: "Texas", population: 196429 },
  { slug: "glendale-california", city: "Glendale", state: "California", population: 196021 },
  { slug: "mobile-alabama", city: "Mobile", state: "Alabama", population: 194899 },
  { slug: "grand-rapids-michigan", city: "Grand Rapids", state: "Michigan", population: 192294 },
  { slug: "salt-lake-city-utah", city: "Salt Lake City", state: "Utah", population: 191180 },
  { slug: "tallahassee-florida", city: "Tallahassee", state: "Florida", population: 186411 },
  { slug: "huntsville-alabama", city: "Huntsville", state: "Alabama", population: 186254 },
  { slug: "grand-prairie-texas", city: "Grand Prairie", state: "Texas", population: 183372 },
  { slug: "knoxville-tennessee", city: "Knoxville", state: "Tennessee", population: 183270 },
  { slug: "worcester-massachusetts", city: "Worcester", state: "Massachusetts", population: 182544 },
  { slug: "newport-news-virginia", city: "Newport News", state: "Virginia", population: 182020 },
  { slug: "brownsville-texas", city: "Brownsville", state: "Texas", population: 181860 },
  { slug: "overland-park-kansas", city: "Overland Park", state: "Kansas", population: 181260 },
  { slug: "santa-clarita-california", city: "Santa Clarita", state: "California", population: 179590 },
  { slug: "providence-rhode-island", city: "Providence", state: "Rhode Island", population: 177994 },
  { slug: "garden-grove-california", city: "Garden Grove", state: "California", population: 175140 },
  { slug: "chattanooga-tennessee", city: "Chattanooga", state: "Tennessee", population: 173366 },
  { slug: "oceanside-california", city: "Oceanside", state: "California", population: 172794 },
  { slug: "jackson-mississippi", city: "Jackson", state: "Mississippi", population: 172638 },
  { slug: "fort-lauderdale-florida", city: "Fort Lauderdale", state: "Florida", population: 172389 },
  { slug: "santa-rosa-california", city: "Santa Rosa", state: "California", population: 171990 },
  { slug: "rancho-cucamonga-california", city: "Rancho Cucamonga", state: "California", population: 171386 },
  { slug: "port-st--lucie-florida", city: "Port St. Lucie", state: "Florida", population: 171016 },
  { slug: "tempe-arizona", city: "Tempe", state: "Arizona", population: 168228 },
  { slug: "ontario-california", city: "Ontario", state: "California", population: 167500 },
  { slug: "vancouver-washington", city: "Vancouver", state: "Washington", population: 167405 },
  { slug: "cape-coral-florida", city: "Cape Coral", state: "Florida", population: 165831 },
  { slug: "sioux-falls-south-dakota", city: "Sioux Falls", state: "South Dakota", population: 164676 },
  { slug: "springfield-missouri", city: "Springfield", state: "Missouri", population: 164122 },
  { slug: "peoria-arizona", city: "Peoria", state: "Arizona", population: 162592 },
  { slug: "pembroke-pines-florida", city: "Pembroke Pines", state: "Florida", population: 162329 },
  { slug: "elk-grove-california", city: "Elk Grove", state: "California", population: 161007 },
  { slug: "salem-oregon", city: "Salem", state: "Oregon", population: 160614 },
  { slug: "lancaster-california", city: "Lancaster", state: "California", population: 159523 },
  { slug: "corona-california", city: "Corona", state: "California", population: 159503 },
  { slug: "eugene-oregon", city: "Eugene", state: "Oregon", population: 159190 },
  { slug: "palmdale-california", city: "Palmdale", state: "California", population: 157161 },
  { slug: "salinas-california", city: "Salinas", state: "California", population: 155662 },
  { slug: "springfield-massachusetts", city: "Springfield", state: "Massachusetts", population: 153703 },
  { slug: "pasadena-texas", city: "Pasadena", state: "Texas", population: 152735 },
  { slug: "fort-collins-colorado", city: "Fort Collins", state: "Colorado", population: 152061 },
  { slug: "hayward-california", city: "Hayward", state: "California", population: 151574 },
  { slug: "pomona-california", city: "Pomona", state: "California", population: 151348 },
  { slug: "cary-north-carolina", city: "Cary", state: "North Carolina", population: 151088 },
  { slug: "rockford-illinois", city: "Rockford", state: "Illinois", population: 150251 },
  { slug: "alexandria-virginia", city: "Alexandria", state: "Virginia", population: 148892 },
  { slug: "escondido-california", city: "Escondido", state: "California", population: 148738 },
  { slug: "mckinney-texas", city: "McKinney", state: "Texas", population: 148559 },
  { slug: "kansas-city-kansas", city: "Kansas City", state: "Kansas", population: 148483 },
  { slug: "joliet-illinois", city: "Joliet", state: "Illinois", population: 147806 },
  { slug: "sunnyvale-california", city: "Sunnyvale", state: "California", population: 147559 },
  { slug: "torrance-california", city: "Torrance", state: "California", population: 147478 },
  { slug: "bridgeport-connecticut", city: "Bridgeport", state: "Connecticut", population: 147216 },
  { slug: "lakewood-colorado", city: "Lakewood", state: "Colorado", population: 147214 },
  { slug: "hollywood-florida", city: "Hollywood", state: "Florida", population: 146526 },
  { slug: "paterson-new-jersey", city: "Paterson", state: "New Jersey", population: 145948 },
  { slug: "naperville-illinois", city: "Naperville", state: "Illinois", population: 144864 },
  { slug: "syracuse-new-york", city: "Syracuse", state: "New York", population: 144669 },
  { slug: "mesquite-texas", city: "Mesquite", state: "Texas", population: 143484 },
  { slug: "dayton-ohio", city: "Dayton", state: "Ohio", population: 143355 },
  { slug: "savannah-georgia", city: "Savannah", state: "Georgia", population: 142772 },
  { slug: "clarksville-tennessee", city: "Clarksville", state: "Tennessee", population: 142357 },
  { slug: "orange-california", city: "Orange", state: "California", population: 139969 },
  { slug: "pasadena-california", city: "Pasadena", state: "California", population: 139731 },
  { slug: "fullerton-california", city: "Fullerton", state: "California", population: 138981 },
  { slug: "killeen-texas", city: "Killeen", state: "Texas", population: 137147 },
  { slug: "frisco-texas", city: "Frisco", state: "Texas", population: 136791 },
  { slug: "hampton-virginia", city: "Hampton", state: "Virginia", population: 136699 },
  { slug: "mcallen-texas", city: "McAllen", state: "Texas", population: 136639 },
  { slug: "warren-michigan", city: "Warren", state: "Michigan", population: 134873 },
  { slug: "bellevue-washington", city: "Bellevue", state: "Washington", population: 133992 },
  { slug: "west-valley-city-utah", city: "West Valley City", state: "Utah", population: 133579 },
  { slug: "columbia-south-carolina", city: "Columbia", state: "South Carolina", population: 133358 },
  { slug: "olathe-kansas", city: "Olathe", state: "Kansas", population: 131885 },
  { slug: "sterling-heights-michigan", city: "Sterling Heights", state: "Michigan", population: 131224 },
  { slug: "new-haven-connecticut", city: "New Haven", state: "Connecticut", population: 130660 },
  { slug: "miramar-florida", city: "Miramar", state: "Florida", population: 130288 },
  { slug: "waco-texas", city: "Waco", state: "Texas", population: 129030 },
  { slug: "thousand-oaks-california", city: "Thousand Oaks", state: "California", population: 128731 },
  { slug: "cedar-rapids-iowa", city: "Cedar Rapids", state: "Iowa", population: 128429 },
  { slug: "charleston-south-carolina", city: "Charleston", state: "South Carolina", population: 127999 },
  { slug: "visalia-california", city: "Visalia", state: "California", population: 127763 },
  { slug: "topeka-kansas", city: "Topeka", state: "Kansas", population: 127679 },
  { slug: "elizabeth-new-jersey", city: "Elizabeth", state: "New Jersey", population: 127558 },
  { slug: "gainesville-florida", city: "Gainesville", state: "Florida", population: 127488 },
  { slug: "thornton-colorado", city: "Thornton", state: "Colorado", population: 127359 },
  { slug: "roseville-california", city: "Roseville", state: "California", population: 127035 },
  { slug: "carrollton-texas", city: "Carrollton", state: "Texas", population: 126700 },
  { slug: "coral-springs-florida", city: "Coral Springs", state: "Florida", population: 126604 },
  { slug: "stamford-connecticut", city: "Stamford", state: "Connecticut", population: 126456 },
  { slug: "simi-valley-california", city: "Simi Valley", state: "California", population: 126181 },
  { slug: "concord-california", city: "Concord", state: "California", population: 125880 },
  { slug: "hartford-connecticut", city: "Hartford", state: "Connecticut", population: 125017 },
  { slug: "kent-washington", city: "Kent", state: "Washington", population: 124435 },
  { slug: "lafayette-louisiana", city: "Lafayette", state: "Louisiana", population: 124276 },
  { slug: "midland-texas", city: "Midland", state: "Texas", population: 123933 },
  { slug: "surprise-arizona", city: "Surprise", state: "Arizona", population: 123546 },
  { slug: "denton-texas", city: "Denton", state: "Texas", population: 123099 },
  { slug: "victorville-california", city: "Victorville", state: "California", population: 121096 },
  { slug: "evansville-indiana", city: "Evansville", state: "Indiana", population: 120310 },
  { slug: "santa-clara-california", city: "Santa Clara", state: "California", population: 120245 },
  { slug: "abilene-texas", city: "Abilene", state: "Texas", population: 120099 },
  { slug: "athens-clarke-county-georgia", city: "Athens-Clarke County", state: "Georgia", population: 119980 },
  { slug: "vallejo-california", city: "Vallejo", state: "California", population: 118837 },
  { slug: "allentown-pennsylvania", city: "Allentown", state: "Pennsylvania", population: 118577 },
  { slug: "norman-oklahoma", city: "Norman", state: "Oklahoma", population: 118197 },
  { slug: "beaumont-texas", city: "Beaumont", state: "Texas", population: 117796 },
  { slug: "independence-missouri", city: "Independence", state: "Missouri", population: 117240 },
  { slug: "murfreesboro-tennessee", city: "Murfreesboro", state: "Tennessee", population: 117044 },
  { slug: "ann-arbor-michigan", city: "Ann Arbor", state: "Michigan", population: 117025 },
  { slug: "springfield-illinois", city: "Springfield", state: "Illinois", population: 117006 },
  { slug: "berkeley-california", city: "Berkeley", state: "California", population: 116768 },
  { slug: "peoria-illinois", city: "Peoria", state: "Illinois", population: 116513 },
  { slug: "provo-utah", city: "Provo", state: "Utah", population: 116288 },
  { slug: "el-monte-california", city: "El Monte", state: "California", population: 115708 },
  { slug: "columbia-missouri", city: "Columbia", state: "Missouri", population: 115276 },
  { slug: "lansing-michigan", city: "Lansing", state: "Michigan", population: 113972 },
  { slug: "fargo-north-dakota", city: "Fargo", state: "North Dakota", population: 113658 },
  { slug: "downey-california", city: "Downey", state: "California", population: 113242 },
  { slug: "costa-mesa-california", city: "Costa Mesa", state: "California", population: 112174 },
  { slug: "wilmington-north-carolina", city: "Wilmington", state: "North Carolina", population: 112067 },
  { slug: "arvada-colorado", city: "Arvada", state: "Colorado", population: 111707 },
  { slug: "inglewood-california", city: "Inglewood", state: "California", population: 111542 },
  { slug: "miami-gardens-florida", city: "Miami Gardens", state: "Florida", population: 111378 },
  { slug: "carlsbad-california", city: "Carlsbad", state: "California", population: 110972 },
  { slug: "westminster-colorado", city: "Westminster", state: "Colorado", population: 110945 },
  { slug: "rochester-minnesota", city: "Rochester", state: "Minnesota", population: 110742 },
  { slug: "odessa-texas", city: "Odessa", state: "Texas", population: 110720 },
  { slug: "manchester-new-hampshire", city: "Manchester", state: "New Hampshire", population: 110378 },
  { slug: "elgin-illinois", city: "Elgin", state: "Illinois", population: 110145 },
  { slug: "west-jordan-utah", city: "West Jordan", state: "Utah", population: 110077 },
  { slug: "round-rock-texas", city: "Round Rock", state: "Texas", population: 109821 },
  { slug: "clearwater-florida", city: "Clearwater", state: "Florida", population: 109703 },
  { slug: "waterbury-connecticut", city: "Waterbury", state: "Connecticut", population: 109676 },
  { slug: "gresham-oregon", city: "Gresham", state: "Oregon", population: 109397 },
  { slug: "fairfield-california", city: "Fairfield", state: "California", population: 109320 },
  { slug: "billings-montana", city: "Billings", state: "Montana", population: 109059 },
  { slug: "lowell-massachusetts", city: "Lowell", state: "Massachusetts", population: 108861 },
  { slug: "san-buenaventura--ventura-california", city: "San Buenaventura (Ventura)", state: "California", population: 108817 },
  { slug: "pueblo-colorado", city: "Pueblo", state: "Colorado", population: 108249 },
  { slug: "high-point-north-carolina", city: "High Point", state: "North Carolina", population: 107741 },
  { slug: "west-covina-california", city: "West Covina", state: "California", population: 107740 },
  { slug: "richmond-california", city: "Richmond", state: "California", population: 107571 },
  { slug: "murrieta-california", city: "Murrieta", state: "California", population: 107479 },
  { slug: "cambridge-massachusetts", city: "Cambridge", state: "Massachusetts", population: 107289 },
  { slug: "antioch-california", city: "Antioch", state: "California", population: 107100 },
  { slug: "temecula-california", city: "Temecula", state: "California", population: 106780 },
  { slug: "norwalk-california", city: "Norwalk", state: "California", population: 106589 },
  { slug: "centennial-colorado", city: "Centennial", state: "Colorado", population: 106114 },
  { slug: "everett-washington", city: "Everett", state: "Washington", population: 105370 },
  { slug: "wichita-falls-texas", city: "Wichita Falls", state: "Texas", population: 104898 },
  { slug: "palm-bay-florida", city: "Palm Bay", state: "Florida", population: 104898 },
  { slug: "green-bay-wisconsin", city: "Green Bay", state: "Wisconsin", population: 104779 },
  { slug: "daly-city-california", city: "Daly City", state: "California", population: 104739 },
  { slug: "burbank-california", city: "Burbank", state: "California", population: 104709 },
  { slug: "richardson-texas", city: "Richardson", state: "Texas", population: 104475 },
  { slug: "pompano-beach-florida", city: "Pompano Beach", state: "Florida", population: 104410 },
  { slug: "north-charleston-south-carolina", city: "North Charleston", state: "South Carolina", population: 104054 },
  { slug: "broken-arrow-oklahoma", city: "Broken Arrow", state: "Oklahoma", population: 103500 },
  { slug: "boulder-colorado", city: "Boulder", state: "Colorado", population: 103166 },
  { slug: "west-palm-beach-florida", city: "West Palm Beach", state: "Florida", population: 102436 },
  { slug: "santa-maria-california", city: "Santa Maria", state: "California", population: 102216 },
  { slug: "el-cajon-california", city: "El Cajon", state: "California", population: 102211 },
  { slug: "davenport-iowa", city: "Davenport", state: "Iowa", population: 102157 },
  { slug: "rialto-california", city: "Rialto", state: "California", population: 101910 },
  { slug: "las-cruces-new-mexico", city: "Las Cruces", state: "New Mexico", population: 101324 },
  { slug: "san-mateo-california", city: "San Mateo", state: "California", population: 101128 },
  { slug: "lewisville-texas", city: "Lewisville", state: "Texas", population: 101074 },
  { slug: "south-bend-indiana", city: "South Bend", state: "Indiana", population: 100886 },
  { slug: "lakeland-florida", city: "Lakeland", state: "Florida", population: 100710 },
  { slug: "erie-pennsylvania", city: "Erie", state: "Pennsylvania", population: 100671 },
  { slug: "tyler-texas", city: "Tyler", state: "Texas", population: 100223 },
  { slug: "pearland-texas", city: "Pearland", state: "Texas", population: 100065 },
  { slug: "college-station-texas", city: "College Station", state: "Texas", population: 100050 },
  { slug: "kenosha-wisconsin", city: "Kenosha", state: "Wisconsin", population: 99889 },
  { slug: "sandy-springs-georgia", city: "Sandy Springs", state: "Georgia", population: 99770 },
  { slug: "clovis-california", city: "Clovis", state: "California", population: 99769 },
  { slug: "flint-michigan", city: "Flint", state: "Michigan", population: 99763 },
  { slug: "roanoke-virginia", city: "Roanoke", state: "Virginia", population: 98465 },
  { slug: "albany-new-york", city: "Albany", state: "New York", population: 98424 },
  { slug: "jurupa-valley-california", city: "Jurupa Valley", state: "California", population: 98030 },
  { slug: "compton-california", city: "Compton", state: "California", population: 97877 },
  { slug: "san-angelo-texas", city: "San Angelo", state: "Texas", population: 97492 },
  { slug: "hillsboro-oregon", city: "Hillsboro", state: "Oregon", population: 97368 },
  { slug: "lawton-oklahoma", city: "Lawton", state: "Oklahoma", population: 97151 },
  { slug: "renton-washington", city: "Renton", state: "Washington", population: 97003 },
  { slug: "vista-california", city: "Vista", state: "California", population: 96929 },
  { slug: "davie-florida", city: "Davie", state: "Florida", population: 96830 },
  { slug: "greeley-colorado", city: "Greeley", state: "Colorado", population: 96539 },
  { slug: "mission-viejo-california", city: "Mission Viejo", state: "California", population: 96346 },
  { slug: "portsmouth-virginia", city: "Portsmouth", state: "Virginia", population: 96205 },
  { slug: "dearborn-michigan", city: "Dearborn", state: "Michigan", population: 95884 },
  { slug: "south-gate-california", city: "South Gate", state: "California", population: 95677 },
  { slug: "tuscaloosa-alabama", city: "Tuscaloosa", state: "Alabama", population: 95334 },
  { slug: "livonia-michigan", city: "Livonia", state: "Michigan", population: 95208 },
  { slug: "new-bedford-massachusetts", city: "New Bedford", state: "Massachusetts", population: 95078 },
  { slug: "vacaville-california", city: "Vacaville", state: "California", population: 94275 },
  { slug: "brockton-massachusetts", city: "Brockton", state: "Massachusetts", population: 94089 },
  { slug: "roswell-georgia", city: "Roswell", state: "Georgia", population: 94034 },
  { slug: "beaverton-oregon", city: "Beaverton", state: "Oregon", population: 93542 },
  { slug: "quincy-massachusetts", city: "Quincy", state: "Massachusetts", population: 93494 },
  { slug: "sparks-nevada", city: "Sparks", state: "Nevada", population: 93282 },
  { slug: "yakima-washington", city: "Yakima", state: "Washington", population: 93257 },
  { slug: "lee-s-summit-missouri", city: "Lee's Summit", state: "Missouri", population: 93184 },
  { slug: "federal-way-washington", city: "Federal Way", state: "Washington", population: 92734 },
  { slug: "carson-california", city: "Carson", state: "California", population: 92599 },
  { slug: "santa-monica-california", city: "Santa Monica", state: "California", population: 92472 },
  { slug: "hesperia-california", city: "Hesperia", state: "California", population: 92147 },
  { slug: "allen-texas", city: "Allen", state: "Texas", population: 92020 },
  { slug: "rio-rancho-new-mexico", city: "Rio Rancho", state: "New Mexico", population: 91956 },
  { slug: "yuma-arizona", city: "Yuma", state: "Arizona", population: 91923 },
  { slug: "westminster-california", city: "Westminster", state: "California", population: 91739 },
  { slug: "orem-utah", city: "Orem", state: "Utah", population: 91648 },
  { slug: "lynn-massachusetts", city: "Lynn", state: "Massachusetts", population: 91589 },
  { slug: "redding-california", city: "Redding", state: "California", population: 91119 },
  { slug: "spokane-valley-washington", city: "Spokane Valley", state: "Washington", population: 91113 },
  { slug: "miami-beach-florida", city: "Miami Beach", state: "Florida", population: 91026 },
  { slug: "league-city-texas", city: "League City", state: "Texas", population: 90983 },
  { slug: "lawrence-kansas", city: "Lawrence", state: "Kansas", population: 90811 },
  { slug: "santa-barbara-california", city: "Santa Barbara", state: "California", population: 90412 },
  { slug: "plantation-florida", city: "Plantation", state: "Florida", population: 90268 },
  { slug: "sandy-utah", city: "Sandy", state: "Utah", population: 90231 },
  { slug: "sunrise-florida", city: "Sunrise", state: "Florida", population: 90116 },
  { slug: "macon-georgia", city: "Macon", state: "Georgia", population: 89981 },
  { slug: "longmont-colorado", city: "Longmont", state: "Colorado", population: 89919 },
  { slug: "boca-raton-florida", city: "Boca Raton", state: "Florida", population: 89407 },
  { slug: "san-marcos-california", city: "San Marcos", state: "California", population: 89387 },
  { slug: "greenville-north-carolina", city: "Greenville", state: "North Carolina", population: 89130 },
  { slug: "waukegan-illinois", city: "Waukegan", state: "Illinois", population: 88826 },
  { slug: "fall-river-massachusetts", city: "Fall River", state: "Massachusetts", population: 88697 },
  { slug: "chico-california", city: "Chico", state: "California", population: 88077 },
  { slug: "newton-massachusetts", city: "Newton", state: "Massachusetts", population: 87971 },
  { slug: "san-leandro-california", city: "San Leandro", state: "California", population: 87965 },
  { slug: "reading-pennsylvania", city: "Reading", state: "Pennsylvania", population: 87893 },
  { slug: "norwalk-connecticut", city: "Norwalk", state: "Connecticut", population: 87776 },
  { slug: "fort-smith-arkansas", city: "Fort Smith", state: "Arkansas", population: 87650 },
  { slug: "newport-beach-california", city: "Newport Beach", state: "California", population: 87273 },
  { slug: "asheville-north-carolina", city: "Asheville", state: "North Carolina", population: 87236 },
  { slug: "nashua-new-hampshire", city: "Nashua", state: "New Hampshire", population: 87137 },
  { slug: "edmond-oklahoma", city: "Edmond", state: "Oklahoma", population: 87004 },
  { slug: "whittier-california", city: "Whittier", state: "California", population: 86635 },
  { slug: "nampa-idaho", city: "Nampa", state: "Idaho", population: 86518 },
  { slug: "bloomington-minnesota", city: "Bloomington", state: "Minnesota", population: 86319 },
  { slug: "deltona-florida", city: "Deltona", state: "Florida", population: 86290 },
  { slug: "hawthorne-california", city: "Hawthorne", state: "California", population: 86199 },
  { slug: "duluth-minnesota", city: "Duluth", state: "Minnesota", population: 86128 },
  { slug: "carmel-indiana", city: "Carmel", state: "Indiana", population: 85927 },
  { slug: "suffolk-virginia", city: "Suffolk", state: "Virginia", population: 85728 },
  { slug: "clifton-new-jersey", city: "Clifton", state: "New Jersey", population: 85390 },
  { slug: "citrus-heights-california", city: "Citrus Heights", state: "California", population: 85285 },
  { slug: "livermore-california", city: "Livermore", state: "California", population: 85156 },
  { slug: "tracy-california", city: "Tracy", state: "California", population: 84691 },
  { slug: "alhambra-california", city: "Alhambra", state: "California", population: 84577 },
  { slug: "kirkland-washington", city: "Kirkland", state: "Washington", population: 84430 },
  { slug: "trenton-new-jersey", city: "Trenton", state: "New Jersey", population: 84349 },
  { slug: "ogden-utah", city: "Ogden", state: "Utah", population: 84249 },
  { slug: "hoover-alabama", city: "Hoover", state: "Alabama", population: 84126 },
  { slug: "cicero-illinois", city: "Cicero", state: "Illinois", population: 84103 },
  { slug: "fishers-indiana", city: "Fishers", state: "Indiana", population: 83891 },
  { slug: "sugar-land-texas", city: "Sugar Land", state: "Texas", population: 83860 },
  { slug: "danbury-connecticut", city: "Danbury", state: "Connecticut", population: 83684 },
  { slug: "meridian-idaho", city: "Meridian", state: "Idaho", population: 83596 },
  { slug: "indio-california", city: "Indio", state: "California", population: 83539 },
  { slug: "concord-north-carolina", city: "Concord", state: "North Carolina", population: 83506 },
  { slug: "menifee-california", city: "Menifee", state: "California", population: 83447 },
  { slug: "champaign-illinois", city: "Champaign", state: "Illinois", population: 83424 },
  { slug: "buena-park-california", city: "Buena Park", state: "California", population: 82882 },
  { slug: "troy-michigan", city: "Troy", state: "Michigan", population: 82821 },
  { slug: "o-fallon-missouri", city: "O'Fallon", state: "Missouri", population: 82809 },
  { slug: "johns-creek-georgia", city: "Johns Creek", state: "Georgia", population: 82788 },
  { slug: "bellingham-washington", city: "Bellingham", state: "Washington", population: 82631 },
  { slug: "westland-michigan", city: "Westland", state: "Michigan", population: 82578 },
  { slug: "bloomington-indiana", city: "Bloomington", state: "Indiana", population: 82575 },
  { slug: "sioux-city-iowa", city: "Sioux City", state: "Iowa", population: 82459 },
  { slug: "warwick-rhode-island", city: "Warwick", state: "Rhode Island", population: 81971 },
  { slug: "hemet-california", city: "Hemet", state: "California", population: 81750 },
  { slug: "longview-texas", city: "Longview", state: "Texas", population: 81443 },
  { slug: "farmington-hills-michigan", city: "Farmington Hills", state: "Michigan", population: 81295 },
  { slug: "bend-oregon", city: "Bend", state: "Oregon", population: 81236 },
  { slug: "lakewood-california", city: "Lakewood", state: "California", population: 81121 },
  { slug: "merced-california", city: "Merced", state: "California", population: 81102 },
  { slug: "mission-texas", city: "Mission", state: "Texas", population: 81050 },
  { slug: "chino-california", city: "Chino", state: "California", population: 80988 },
  { slug: "redwood-city-california", city: "Redwood City", state: "California", population: 80872 },
  { slug: "edinburg-texas", city: "Edinburg", state: "Texas", population: 80836 },
  { slug: "cranston-rhode-island", city: "Cranston", state: "Rhode Island", population: 80566 },
  { slug: "parma-ohio", city: "Parma", state: "Ohio", population: 80429 },
  { slug: "new-rochelle-new-york", city: "New Rochelle", state: "New York", population: 79446 },
  { slug: "lake-forest-california", city: "Lake Forest", state: "California", population: 79312 },
  { slug: "napa-california", city: "Napa", state: "California", population: 79068 },
  { slug: "hammond-indiana", city: "Hammond", state: "Indiana", population: 78967 },
  { slug: "fayetteville-arkansas", city: "Fayetteville", state: "Arkansas", population: 78960 },
  { slug: "bloomington-illinois", city: "Bloomington", state: "Illinois", population: 78902 },
  { slug: "avondale-arizona", city: "Avondale", state: "Arizona", population: 78822 },
  { slug: "somerville-massachusetts", city: "Somerville", state: "Massachusetts", population: 78804 },
  { slug: "palm-coast-florida", city: "Palm Coast", state: "Florida", population: 78740 },
  { slug: "bryan-texas", city: "Bryan", state: "Texas", population: 78709 },
  { slug: "gary-indiana", city: "Gary", state: "Indiana", population: 78450 },
  { slug: "largo-florida", city: "Largo", state: "Florida", population: 78409 },
  { slug: "brooklyn-park-minnesota", city: "Brooklyn Park", state: "Minnesota", population: 78373 },
  { slug: "tustin-california", city: "Tustin", state: "California", population: 78327 },
  { slug: "racine-wisconsin", city: "Racine", state: "Wisconsin", population: 78199 },
  { slug: "deerfield-beach-florida", city: "Deerfield Beach", state: "Florida", population: 78041 },
  { slug: "lynchburg-virginia", city: "Lynchburg", state: "Virginia", population: 78014 },
  { slug: "mountain-view-california", city: "Mountain View", state: "California", population: 77846 },
  { slug: "medford-oregon", city: "Medford", state: "Oregon", population: 77677 },
  { slug: "lawrence-massachusetts", city: "Lawrence", state: "Massachusetts", population: 77657 },
  { slug: "bellflower-california", city: "Bellflower", state: "California", population: 77593 },
  { slug: "melbourne-florida", city: "Melbourne", state: "Florida", population: 77508 },
  { slug: "st--joseph-missouri", city: "St. Joseph", state: "Missouri", population: 77147 },
  { slug: "camden-new-jersey", city: "Camden", state: "New Jersey", population: 76903 },
  { slug: "st--george-utah", city: "St. George", state: "Utah", population: 76817 },
  { slug: "kennewick-washington", city: "Kennewick", state: "Washington", population: 76762 },
  { slug: "baldwin-park-california", city: "Baldwin Park", state: "California", population: 76635 },
  { slug: "chino-hills-california", city: "Chino Hills", state: "California", population: 76572 },
  { slug: "alameda-california", city: "Alameda", state: "California", population: 76419 },
  { slug: "albany-georgia", city: "Albany", state: "Georgia", population: 76185 },
  { slug: "arlington-heights-illinois", city: "Arlington Heights", state: "Illinois", population: 75994 },
  { slug: "scranton-pennsylvania", city: "Scranton", state: "Pennsylvania", population: 75806 },
  { slug: "evanston-illinois", city: "Evanston", state: "Illinois", population: 75570 },
  { slug: "kalamazoo-michigan", city: "Kalamazoo", state: "Michigan", population: 75548 },
  { slug: "baytown-texas", city: "Baytown", state: "Texas", population: 75418 },
  { slug: "upland-california", city: "Upland", state: "California", population: 75413 },
  { slug: "springdale-arkansas", city: "Springdale", state: "Arkansas", population: 75229 },
  { slug: "bethlehem-pennsylvania", city: "Bethlehem", state: "Pennsylvania", population: 75018 },
  { slug: "schaumburg-illinois", city: "Schaumburg", state: "Illinois", population: 74907 },
  { slug: "mount-pleasant-south-carolina", city: "Mount Pleasant", state: "South Carolina", population: 74885 },
  { slug: "auburn-washington", city: "Auburn", state: "Washington", population: 74860 },
  { slug: "decatur-illinois", city: "Decatur", state: "Illinois", population: 74710 },
  { slug: "san-ramon-california", city: "San Ramon", state: "California", population: 74513 },
  { slug: "pleasanton-california", city: "Pleasanton", state: "California", population: 74110 },
  { slug: "wyoming-michigan", city: "Wyoming", state: "Michigan", population: 74100 },
  { slug: "lake-charles-louisiana", city: "Lake Charles", state: "Louisiana", population: 74024 },
  { slug: "plymouth-minnesota", city: "Plymouth", state: "Minnesota", population: 73987 },
  { slug: "bolingbrook-illinois", city: "Bolingbrook", state: "Illinois", population: 73936 },
  { slug: "pharr-texas", city: "Pharr", state: "Texas", population: 73790 },
  { slug: "appleton-wisconsin", city: "Appleton", state: "Wisconsin", population: 73596 },
  { slug: "gastonia-north-carolina", city: "Gastonia", state: "North Carolina", population: 73209 },
  { slug: "folsom-california", city: "Folsom", state: "California", population: 73098 },
  { slug: "southfield-michigan", city: "Southfield", state: "Michigan", population: 73006 },
  { slug: "rochester-hills-michigan", city: "Rochester Hills", state: "Michigan", population: 72952 },
  { slug: "new-britain-connecticut", city: "New Britain", state: "Connecticut", population: 72939 },
  { slug: "goodyear-arizona", city: "Goodyear", state: "Arizona", population: 72864 },
  { slug: "canton-ohio", city: "Canton", state: "Ohio", population: 72535 },
  { slug: "warner-robins-georgia", city: "Warner Robins", state: "Georgia", population: 72531 },
  { slug: "union-city-california", city: "Union City", state: "California", population: 72528 },
  { slug: "perris-california", city: "Perris", state: "California", population: 72326 },
  { slug: "manteca-california", city: "Manteca", state: "California", population: 71948 },
  { slug: "iowa-city-iowa", city: "Iowa City", state: "Iowa", population: 71591 },
  { slug: "jonesboro-arkansas", city: "Jonesboro", state: "Arkansas", population: 71551 },
  { slug: "wilmington-delaware", city: "Wilmington", state: "Delaware", population: 71525 },
  { slug: "lynwood-california", city: "Lynwood", state: "California", population: 71371 },
  { slug: "loveland-colorado", city: "Loveland", state: "Colorado", population: 71334 },
  { slug: "pawtucket-rhode-island", city: "Pawtucket", state: "Rhode Island", population: 71172 },
  { slug: "boynton-beach-florida", city: "Boynton Beach", state: "Florida", population: 71097 },
  { slug: "waukesha-wisconsin", city: "Waukesha", state: "Wisconsin", population: 71016 },
  { slug: "gulfport-mississippi", city: "Gulfport", state: "Mississippi", population: 71012 },
  { slug: "apple-valley-california", city: "Apple Valley", state: "California", population: 70924 },
  { slug: "passaic-new-jersey", city: "Passaic", state: "New Jersey", population: 70868 },
  { slug: "rapid-city-south-dakota", city: "Rapid City", state: "South Dakota", population: 70812 },
  { slug: "layton-utah", city: "Layton", state: "Utah", population: 70790 },
  { slug: "lafayette-indiana", city: "Lafayette", state: "Indiana", population: 70373 },
  { slug: "turlock-california", city: "Turlock", state: "California", population: 70365 },
  { slug: "muncie-indiana", city: "Muncie", state: "Indiana", population: 70316 },
  { slug: "temple-texas", city: "Temple", state: "Texas", population: 70190 },
  { slug: "missouri-city-texas", city: "Missouri City", state: "Texas", population: 70185 },
  { slug: "redlands-california", city: "Redlands", state: "California", population: 69999 },
  { slug: "santa-fe-new-mexico", city: "Santa Fe", state: "New Mexico", population: 69976 },
  { slug: "lauderhill-florida", city: "Lauderhill", state: "Florida", population: 69813 },
  { slug: "milpitas-california", city: "Milpitas", state: "California", population: 69783 },
  { slug: "palatine-illinois", city: "Palatine", state: "Illinois", population: 69350 },
  { slug: "missoula-montana", city: "Missoula", state: "Montana", population: 69122 },
  { slug: "rock-hill-south-carolina", city: "Rock Hill", state: "South Carolina", population: 69103 },
  { slug: "jacksonville-north-carolina", city: "Jacksonville", state: "North Carolina", population: 69079 },
  { slug: "franklin-tennessee", city: "Franklin", state: "Tennessee", population: 68886 },
  { slug: "flagstaff-arizona", city: "Flagstaff", state: "Arizona", population: 68667 },
  { slug: "flower-mound-texas", city: "Flower Mound", state: "Texas", population: 68609 },
  { slug: "weston-florida", city: "Weston", state: "Florida", population: 68388 },
  { slug: "waterloo-iowa", city: "Waterloo", state: "Iowa", population: 68366 },
  { slug: "union-city-new-jersey", city: "Union City", state: "New Jersey", population: 68247 },
  { slug: "mount-vernon-new-york", city: "Mount Vernon", state: "New York", population: 68224 },
  { slug: "fort-myers-florida", city: "Fort Myers", state: "Florida", population: 68190 },
  { slug: "dothan-alabama", city: "Dothan", state: "Alabama", population: 68001 },
  { slug: "rancho-cordova-california", city: "Rancho Cordova", state: "California", population: 67911 },
  { slug: "redondo-beach-california", city: "Redondo Beach", state: "California", population: 67815 },
  { slug: "jackson-tennessee", city: "Jackson", state: "Tennessee", population: 67685 },
  { slug: "pasco-washington", city: "Pasco", state: "Washington", population: 67599 },
  { slug: "st--charles-missouri", city: "St. Charles", state: "Missouri", population: 67569 },
  { slug: "eau-claire-wisconsin", city: "Eau Claire", state: "Wisconsin", population: 67545 },
  { slug: "north-richland-hills-texas", city: "North Richland Hills", state: "Texas", population: 67317 },
  { slug: "bismarck-north-dakota", city: "Bismarck", state: "North Dakota", population: 67034 },
  { slug: "yorba-linda-california", city: "Yorba Linda", state: "California", population: 67032 },
  { slug: "kenner-louisiana", city: "Kenner", state: "Louisiana", population: 66975 },
  { slug: "walnut-creek-california", city: "Walnut Creek", state: "California", population: 66900 },
  { slug: "frederick-maryland", city: "Frederick", state: "Maryland", population: 66893 },
  { slug: "oshkosh-wisconsin", city: "Oshkosh", state: "Wisconsin", population: 66778 },
  { slug: "pittsburg-california", city: "Pittsburg", state: "California", population: 66695 },
  { slug: "palo-alto-california", city: "Palo Alto", state: "California", population: 66642 },
  { slug: "bossier-city-louisiana", city: "Bossier City", state: "Louisiana", population: 66333 },
  { slug: "portland-maine", city: "Portland", state: "Maine", population: 66318 },
  { slug: "st--cloud-minnesota", city: "St. Cloud", state: "Minnesota", population: 66297 },
  { slug: "davis-california", city: "Davis", state: "California", population: 66205 },
  { slug: "south-san-francisco-california", city: "South San Francisco", state: "California", population: 66174 },
  { slug: "camarillo-california", city: "Camarillo", state: "California", population: 66086 },
  { slug: "north-little-rock-arkansas", city: "North Little Rock", state: "Arkansas", population: 66075 },
  { slug: "schenectady-new-york", city: "Schenectady", state: "New York", population: 65902 },
  { slug: "gaithersburg-maryland", city: "Gaithersburg", state: "Maryland", population: 65690 },
  { slug: "harlingen-texas", city: "Harlingen", state: "Texas", population: 65665 },
  { slug: "woodbury-minnesota", city: "Woodbury", state: "Minnesota", population: 65656 },
  { slug: "eagan-minnesota", city: "Eagan", state: "Minnesota", population: 65453 },
  { slug: "yuba-city-california", city: "Yuba City", state: "California", population: 65416 },
  { slug: "maple-grove-minnesota", city: "Maple Grove", state: "Minnesota", population: 65415 },
  { slug: "youngstown-ohio", city: "Youngstown", state: "Ohio", population: 65184 },
  { slug: "skokie-illinois", city: "Skokie", state: "Illinois", population: 65176 },
  { slug: "kissimmee-florida", city: "Kissimmee", state: "Florida", population: 65173 },
  { slug: "johnson-city-tennessee", city: "Johnson City", state: "Tennessee", population: 65123 },
  { slug: "victoria-texas", city: "Victoria", state: "Texas", population: 65098 },
  { slug: "san-clemente-california", city: "San Clemente", state: "California", population: 65040 },
  { slug: "bayonne-new-jersey", city: "Bayonne", state: "New Jersey", population: 65028 },
  { slug: "laguna-niguel-california", city: "Laguna Niguel", state: "California", population: 64652 },
  { slug: "east-orange-new-jersey", city: "East Orange", state: "New Jersey", population: 64544 },
  { slug: "shawnee-kansas", city: "Shawnee", state: "Kansas", population: 64323 },
  { slug: "homestead-florida", city: "Homestead", state: "Florida", population: 64079 },
  { slug: "delray-beach-florida", city: "Delray Beach", state: "Florida", population: 64072 },
  { slug: "rockville-maryland", city: "Rockville", state: "Maryland", population: 64072 },
  { slug: "janesville-wisconsin", city: "Janesville", state: "Wisconsin", population: 63820 },
  { slug: "conway-arkansas", city: "Conway", state: "Arkansas", population: 63816 },
  { slug: "pico-rivera-california", city: "Pico Rivera", state: "California", population: 63771 },
  { slug: "lorain-ohio", city: "Lorain", state: "Ohio", population: 63710 },
  { slug: "montebello-california", city: "Montebello", state: "California", population: 63495 },
  { slug: "lodi-california", city: "Lodi", state: "California", population: 63338 },
  { slug: "new-braunfels-texas", city: "New Braunfels", state: "Texas", population: 63279 },
  { slug: "marysville-washington", city: "Marysville", state: "Washington", population: 63269 },
  { slug: "tamarac-florida", city: "Tamarac", state: "Florida", population: 63155 },
  { slug: "madera-california", city: "Madera", state: "California", population: 63105 },
  { slug: "conroe-texas", city: "Conroe", state: "Texas", population: 63032 },
  { slug: "santa-cruz-california", city: "Santa Cruz", state: "California", population: 62864 },
  { slug: "eden-prairie-minnesota", city: "Eden Prairie", state: "Minnesota", population: 62603 },
  { slug: "cheyenne-wyoming", city: "Cheyenne", state: "Wyoming", population: 62448 },
  { slug: "daytona-beach-florida", city: "Daytona Beach", state: "Florida", population: 62316 },
  { slug: "alpharetta-georgia", city: "Alpharetta", state: "Georgia", population: 62298 },
  { slug: "hamilton-ohio", city: "Hamilton", state: "Ohio", population: 62258 },
  { slug: "waltham-massachusetts", city: "Waltham", state: "Massachusetts", population: 62227 },
  { slug: "coon-rapids-minnesota", city: "Coon Rapids", state: "Minnesota", population: 62103 },
  { slug: "haverhill-massachusetts", city: "Haverhill", state: "Massachusetts", population: 62088 },
  { slug: "council-bluffs-iowa", city: "Council Bluffs", state: "Iowa", population: 61969 },
  { slug: "taylor-michigan", city: "Taylor", state: "Michigan", population: 61817 },
  { slug: "utica-new-york", city: "Utica", state: "New York", population: 61808 },
  { slug: "ames-iowa", city: "Ames", state: "Iowa", population: 61792 },
  { slug: "la-habra-california", city: "La Habra", state: "California", population: 61653 },
  { slug: "encinitas-california", city: "Encinitas", state: "California", population: 61588 },
  { slug: "bowling-green-kentucky", city: "Bowling Green", state: "Kentucky", population: 61488 },
  { slug: "burnsville-minnesota", city: "Burnsville", state: "Minnesota", population: 61434 },
  { slug: "greenville-south-carolina", city: "Greenville", state: "South Carolina", population: 61397 },
  { slug: "west-des-moines-iowa", city: "West Des Moines", state: "Iowa", population: 61255 },
  { slug: "cedar-park-texas", city: "Cedar Park", state: "Texas", population: 61238 },
  { slug: "tulare-california", city: "Tulare", state: "California", population: 61170 },
  { slug: "monterey-park-california", city: "Monterey Park", state: "California", population: 61085 },
  { slug: "vineland-new-jersey", city: "Vineland", state: "New Jersey", population: 61050 },
  { slug: "terre-haute-indiana", city: "Terre Haute", state: "Indiana", population: 61025 },
  { slug: "north-miami-florida", city: "North Miami", state: "Florida", population: 61007 },
  { slug: "mansfield-texas", city: "Mansfield", state: "Texas", population: 60872 },
  { slug: "west-allis-wisconsin", city: "West Allis", state: "Wisconsin", population: 60697 },
  { slug: "bristol-connecticut", city: "Bristol", state: "Connecticut", population: 60568 },
  { slug: "taylorsville-utah", city: "Taylorsville", state: "Utah", population: 60519 },
  { slug: "malden-massachusetts", city: "Malden", state: "Massachusetts", population: 60509 },
  { slug: "meriden-connecticut", city: "Meriden", state: "Connecticut", population: 60456 },
  { slug: "blaine-minnesota", city: "Blaine", state: "Minnesota", population: 60407 },
  { slug: "wellington-florida", city: "Wellington", state: "Florida", population: 60202 },
  { slug: "cupertino-california", city: "Cupertino", state: "California", population: 60189 },
  { slug: "springfield-oregon", city: "Springfield", state: "Oregon", population: 60177 },
  { slug: "rogers-arkansas", city: "Rogers", state: "Arkansas", population: 60112 },
  { slug: "st--clair-shores-michigan", city: "St. Clair Shores", state: "Michigan", population: 60070 },
  { slug: "gardena-california", city: "Gardena", state: "California", population: 59957 },
  { slug: "pontiac-michigan", city: "Pontiac", state: "Michigan", population: 59887 },
  { slug: "national-city-california", city: "National City", state: "California", population: 59834 },
  { slug: "grand-junction-colorado", city: "Grand Junction", state: "Colorado", population: 59778 },
  { slug: "rocklin-california", city: "Rocklin", state: "California", population: 59738 },
  { slug: "chapel-hill-north-carolina", city: "Chapel Hill", state: "North Carolina", population: 59635 },
  { slug: "casper-wyoming", city: "Casper", state: "Wyoming", population: 59628 },
  { slug: "broomfield-colorado", city: "Broomfield", state: "Colorado", population: 59471 },
  { slug: "petaluma-california", city: "Petaluma", state: "California", population: 59440 },
  { slug: "south-jordan-utah", city: "South Jordan", state: "Utah", population: 59366 },
  { slug: "springfield-ohio", city: "Springfield", state: "Ohio", population: 59357 },
  { slug: "great-falls-montana", city: "Great Falls", state: "Montana", population: 59351 },
  { slug: "lancaster-pennsylvania", city: "Lancaster", state: "Pennsylvania", population: 59325 },
  { slug: "north-port-florida", city: "North Port", state: "Florida", population: 59212 },
  { slug: "lakewood-washington", city: "Lakewood", state: "Washington", population: 59097 },
  { slug: "marietta-georgia", city: "Marietta", state: "Georgia", population: 59089 },
  { slug: "san-rafael-california", city: "San Rafael", state: "California", population: 58994 },
  { slug: "royal-oak-michigan", city: "Royal Oak", state: "Michigan", population: 58946 },
  { slug: "des-plaines-illinois", city: "Des Plaines", state: "Illinois", population: 58918 },
  { slug: "huntington-park-california", city: "Huntington Park", state: "California", population: 58879 },
  { slug: "la-mesa-california", city: "La Mesa", state: "California", population: 58642 },
  { slug: "orland-park-illinois", city: "Orland Park", state: "Illinois", population: 58590 },
  { slug: "auburn-alabama", city: "Auburn", state: "Alabama", population: 58582 },
  { slug: "lakeville-minnesota", city: "Lakeville", state: "Minnesota", population: 58562 },
  { slug: "owensboro-kentucky", city: "Owensboro", state: "Kentucky", population: 58416 },
  { slug: "moore-oklahoma", city: "Moore", state: "Oklahoma", population: 58414 },
  { slug: "jupiter-florida", city: "Jupiter", state: "Florida", population: 58298 },
  { slug: "idaho-falls-idaho", city: "Idaho Falls", state: "Idaho", population: 58292 },
  { slug: "dubuque-iowa", city: "Dubuque", state: "Iowa", population: 58253 },
  { slug: "bartlett-tennessee", city: "Bartlett", state: "Tennessee", population: 58226 },
  { slug: "rowlett-texas", city: "Rowlett", state: "Texas", population: 58043 },
  { slug: "novi-michigan", city: "Novi", state: "Michigan", population: 57960 },
  { slug: "white-plains-new-york", city: "White Plains", state: "New York", population: 57866 },
  { slug: "arcadia-california", city: "Arcadia", state: "California", population: 57639 },
  { slug: "redmond-washington", city: "Redmond", state: "Washington", population: 57530 },
  { slug: "lake-elsinore-california", city: "Lake Elsinore", state: "California", population: 57525 },
  { slug: "ocala-florida", city: "Ocala", state: "Florida", population: 57468 },
  { slug: "tinley-park-illinois", city: "Tinley Park", state: "Illinois", population: 57282 },
  { slug: "port-orange-florida", city: "Port Orange", state: "Florida", population: 57203 },
  { slug: "medford-massachusetts", city: "Medford", state: "Massachusetts", population: 57170 },
  { slug: "oak-lawn-illinois", city: "Oak Lawn", state: "Illinois", population: 57073 },
  { slug: "rocky-mount-north-carolina", city: "Rocky Mount", state: "North Carolina", population: 56954 },
  { slug: "kokomo-indiana", city: "Kokomo", state: "Indiana", population: 56895 },
  { slug: "coconut-creek-florida", city: "Coconut Creek", state: "Florida", population: 56792 },
  { slug: "bowie-maryland", city: "Bowie", state: "Maryland", population: 56759 },
  { slug: "berwyn-illinois", city: "Berwyn", state: "Illinois", population: 56758 },
  { slug: "midwest-city-oklahoma", city: "Midwest City", state: "Oklahoma", population: 56756 },
  { slug: "fountain-valley-california", city: "Fountain Valley", state: "California", population: 56707 },
  { slug: "buckeye-arizona", city: "Buckeye", state: "Arizona", population: 56683 },
  { slug: "dearborn-heights-michigan", city: "Dearborn Heights", state: "Michigan", population: 56620 },
  { slug: "woodland-california", city: "Woodland", state: "California", population: 56590 },
  { slug: "noblesville-indiana", city: "Noblesville", state: "Indiana", population: 56540 },
  { slug: "valdosta-georgia", city: "Valdosta", state: "Georgia", population: 56481 },
  { slug: "diamond-bar-california", city: "Diamond Bar", state: "California", population: 56449 },
  { slug: "manhattan-kansas", city: "Manhattan", state: "Kansas", population: 56143 },
  { slug: "santee-california", city: "Santee", state: "California", population: 56105 },
  { slug: "taunton-massachusetts", city: "Taunton", state: "Massachusetts", population: 56069 },
  { slug: "sanford-florida", city: "Sanford", state: "Florida", population: 56002 },
  { slug: "kettering-ohio", city: "Kettering", state: "Ohio", population: 55870 },
  { slug: "new-brunswick-new-jersey", city: "New Brunswick", state: "New Jersey", population: 55831 },
  { slug: "decatur-alabama", city: "Decatur", state: "Alabama", population: 55816 },
  { slug: "chicopee-massachusetts", city: "Chicopee", state: "Massachusetts", population: 55717 },
  { slug: "anderson-indiana", city: "Anderson", state: "Indiana", population: 55670 },
  { slug: "margate-florida", city: "Margate", state: "Florida", population: 55456 },
  { slug: "weymouth-town-massachusetts", city: "Weymouth Town", state: "Massachusetts", population: 55419 },
  { slug: "hempstead-new-york", city: "Hempstead", state: "New York", population: 55361 },
  { slug: "corvallis-oregon", city: "Corvallis", state: "Oregon", population: 55298 },
  { slug: "eastvale-california", city: "Eastvale", state: "California", population: 55191 },
  { slug: "porterville-california", city: "Porterville", state: "California", population: 55174 },
  { slug: "west-haven-connecticut", city: "West Haven", state: "Connecticut", population: 55046 },
  { slug: "brentwood-california", city: "Brentwood", state: "California", population: 55000 },
  { slug: "paramount-california", city: "Paramount", state: "California", population: 54980 },
  { slug: "grand-forks-north-dakota", city: "Grand Forks", state: "North Dakota", population: 54932 },
  { slug: "georgetown-texas", city: "Georgetown", state: "Texas", population: 54898 },
  { slug: "st--peters-missouri", city: "St. Peters", state: "Missouri", population: 54842 },
  { slug: "shoreline-washington", city: "Shoreline", state: "Washington", population: 54790 },
  { slug: "mount-prospect-illinois", city: "Mount Prospect", state: "Illinois", population: 54771 },
  { slug: "hanford-california", city: "Hanford", state: "California", population: 54686 },
  { slug: "normal-illinois", city: "Normal", state: "Illinois", population: 54664 },
  { slug: "rosemead-california", city: "Rosemead", state: "California", population: 54561 },
  { slug: "lehi-utah", city: "Lehi", state: "Utah", population: 54382 },
  { slug: "pocatello-idaho", city: "Pocatello", state: "Idaho", population: 54350 },
  { slug: "highland-california", city: "Highland", state: "California", population: 54291 },
  { slug: "novato-california", city: "Novato", state: "California", population: 54194 },
  { slug: "port-arthur-texas", city: "Port Arthur", state: "Texas", population: 54135 },
  { slug: "carson-city-nevada", city: "Carson City", state: "Nevada", population: 54080 },
  { slug: "san-marcos-texas", city: "San Marcos", state: "Texas", population: 54076 },
  { slug: "hendersonville-tennessee", city: "Hendersonville", state: "Tennessee", population: 54068 },
  { slug: "elyria-ohio", city: "Elyria", state: "Ohio", population: 53956 },
  { slug: "revere-massachusetts", city: "Revere", state: "Massachusetts", population: 53756 },
  { slug: "pflugerville-texas", city: "Pflugerville", state: "Texas", population: 53752 },
  { slug: "greenwood-indiana", city: "Greenwood", state: "Indiana", population: 53665 },
  { slug: "bellevue-nebraska", city: "Bellevue", state: "Nebraska", population: 53663 },
  { slug: "wheaton-illinois", city: "Wheaton", state: "Illinois", population: 53648 },
  { slug: "smyrna-georgia", city: "Smyrna", state: "Georgia", population: 53438 },
  { slug: "sarasota-florida", city: "Sarasota", state: "Florida", population: 53326 },
  { slug: "blue-springs-missouri", city: "Blue Springs", state: "Missouri", population: 53294 },
  { slug: "colton-california", city: "Colton", state: "California", population: 53243 },
  { slug: "euless-texas", city: "Euless", state: "Texas", population: 53224 },
  { slug: "castle-rock-colorado", city: "Castle Rock", state: "Colorado", population: 53063 },
  { slug: "cathedral-city-california", city: "Cathedral City", state: "California", population: 52977 },
  { slug: "kingsport-tennessee", city: "Kingsport", state: "Tennessee", population: 52962 },
  { slug: "lake-havasu-city-arizona", city: "Lake Havasu City", state: "Arizona", population: 52844 },
  { slug: "pensacola-florida", city: "Pensacola", state: "Florida", population: 52703 },
  { slug: "hoboken-new-jersey", city: "Hoboken", state: "New Jersey", population: 52575 },
  { slug: "yucaipa-california", city: "Yucaipa", state: "California", population: 52536 },
  { slug: "watsonville-california", city: "Watsonville", state: "California", population: 52477 },
  { slug: "richland-washington", city: "Richland", state: "Washington", population: 52413 },
  { slug: "delano-california", city: "Delano", state: "California", population: 52403 },
  { slug: "hoffman-estates-illinois", city: "Hoffman Estates", state: "Illinois", population: 52398 },
  { slug: "florissant-missouri", city: "Florissant", state: "Missouri", population: 52363 },
  { slug: "placentia-california", city: "Placentia", state: "California", population: 52206 },
  { slug: "west-new-york-new-jersey", city: "West New York", state: "New Jersey", population: 52122 },
  { slug: "dublin-california", city: "Dublin", state: "California", population: 52105 },
  { slug: "oak-park-illinois", city: "Oak Park", state: "Illinois", population: 52066 },
  { slug: "peabody-massachusetts", city: "Peabody", state: "Massachusetts", population: 52044 },
  { slug: "perth-amboy-new-jersey", city: "Perth Amboy", state: "New Jersey", population: 51982 },
  { slug: "battle-creek-michigan", city: "Battle Creek", state: "Michigan", population: 51848 },
  { slug: "bradenton-florida", city: "Bradenton", state: "Florida", population: 51763 },
  { slug: "gilroy-california", city: "Gilroy", state: "California", population: 51701 },
  { slug: "milford-connecticut", city: "Milford", state: "Connecticut", population: 51644 },
  { slug: "albany-oregon", city: "Albany", state: "Oregon", population: 51583 },
  { slug: "ankeny-iowa", city: "Ankeny", state: "Iowa", population: 51567 },
  { slug: "la-crosse-wisconsin", city: "La Crosse", state: "Wisconsin", population: 51522 },
  { slug: "burlington-north-carolina", city: "Burlington", state: "North Carolina", population: 51510 },
  { slug: "desoto-texas", city: "DeSoto", state: "Texas", population: 51483 },
  { slug: "harrisonburg-virginia", city: "Harrisonburg", state: "Virginia", population: 51395 },
  { slug: "minnetonka-minnesota", city: "Minnetonka", state: "Minnesota", population: 51368 },
  { slug: "elkhart-indiana", city: "Elkhart", state: "Indiana", population: 51265 },
  { slug: "lakewood-ohio", city: "Lakewood", state: "Ohio", population: 51143 },
  { slug: "glendora-california", city: "Glendora", state: "California", population: 51074 },
  { slug: "southaven-mississippi", city: "Southaven", state: "Mississippi", population: 50997 },
  { slug: "charleston-west-virginia", city: "Charleston", state: "West Virginia", population: 50821 },
  { slug: "joplin-missouri", city: "Joplin", state: "Missouri", population: 50789 },
  { slug: "enid-oklahoma", city: "Enid", state: "Oklahoma", population: 50725 },
  { slug: "palm-beach-gardens-florida", city: "Palm Beach Gardens", state: "Florida", population: 50699 },
  { slug: "brookhaven-georgia", city: "Brookhaven", state: "Georgia", population: 50603 },
  { slug: "plainfield-new-jersey", city: "Plainfield", state: "New Jersey", population: 50588 },
  { slug: "grand-island-nebraska", city: "Grand Island", state: "Nebraska", population: 50550 },
  { slug: "palm-desert-california", city: "Palm Desert", state: "California", population: 50508 },
  { slug: "huntersville-north-carolina", city: "Huntersville", state: "North Carolina", population: 50458 },
  { slug: "tigard-oregon", city: "Tigard", state: "Oregon", population: 50444 },
  { slug: "lenexa-kansas", city: "Lenexa", state: "Kansas", population: 50344 },
  { slug: "saginaw-michigan", city: "Saginaw", state: "Michigan", population: 50303 },
  { slug: "kentwood-michigan", city: "Kentwood", state: "Michigan", population: 50233 },
  { slug: "doral-florida", city: "Doral", state: "Florida", population: 50213 },
  { slug: "apple-valley-minnesota", city: "Apple Valley", state: "Minnesota", population: 50201 },
  { slug: "grapevine-texas", city: "Grapevine", state: "Texas", population: 50195 },
  { slug: "aliso-viejo-california", city: "Aliso Viejo", state: "California", population: 50175 },
  { slug: "sammamish-washington", city: "Sammamish", state: "Washington", population: 50169 },
  { slug: "casa-grande-arizona", city: "Casa Grande", state: "Arizona", population: 50111 },
  { slug: "pinellas-park-florida", city: "Pinellas Park", state: "Florida", population: 49998 },
  { slug: "troy-new-york", city: "Troy", state: "New York", population: 49974 },
  { slug: "west-sacramento-california", city: "West Sacramento", state: "California", population: 49891 },
  { slug: "burien-washington", city: "Burien", state: "Washington", population: 49858 },
  { slug: "commerce-city-colorado", city: "Commerce City", state: "Colorado", population: 49799 },
  { slug: "monroe-louisiana", city: "Monroe", state: "Louisiana", population: 49761 },
  { slug: "cerritos-california", city: "Cerritos", state: "California", population: 49707 },
  { slug: "downers-grove-illinois", city: "Downers Grove", state: "Illinois", population: 49670 },
  { slug: "coral-gables-florida", city: "Coral Gables", state: "Florida", population: 49631 },
  { slug: "wilson-north-carolina", city: "Wilson", state: "North Carolina", population: 49628 },
  { slug: "niagara-falls-new-york", city: "Niagara Falls", state: "New York", population: 49468 },
  { slug: "poway-california", city: "Poway", state: "California", population: 49417 },
  { slug: "edina-minnesota", city: "Edina", state: "Minnesota", population: 49376 },
  { slug: "cuyahoga-falls-ohio", city: "Cuyahoga Falls", state: "Ohio", population: 49267 },
  { slug: "rancho-santa-margarita-california", city: "Rancho Santa Margarita", state: "California", population: 49228 },
  { slug: "harrisburg-pennsylvania", city: "Harrisburg", state: "Pennsylvania", population: 49188 },
  { slug: "huntington-west-virginia", city: "Huntington", state: "West Virginia", population: 49177 },
  { slug: "la-mirada-california", city: "La Mirada", state: "California", population: 49133 },
  { slug: "cypress-california", city: "Cypress", state: "California", population: 49087 },
  { slug: "caldwell-idaho", city: "Caldwell", state: "Idaho", population: 48957 },
  { slug: "logan-utah", city: "Logan", state: "Utah", population: 48913 },
  { slug: "galveston-texas", city: "Galveston", state: "Texas", population: 48733 },
  { slug: "sheboygan-wisconsin", city: "Sheboygan", state: "Wisconsin", population: 48725 },
  { slug: "middletown-ohio", city: "Middletown", state: "Ohio", population: 48630 },
  { slug: "murray-utah", city: "Murray", state: "Utah", population: 48612 },
  { slug: "roswell-new-mexico", city: "Roswell", state: "New Mexico", population: 48611 },
  { slug: "parker-colorado", city: "Parker", state: "Colorado", population: 48608 },
  { slug: "bedford-texas", city: "Bedford", state: "Texas", population: 48592 },
  { slug: "east-lansing-michigan", city: "East Lansing", state: "Michigan", population: 48554 },
  { slug: "methuen-massachusetts", city: "Methuen", state: "Massachusetts", population: 48514 },
  { slug: "covina-california", city: "Covina", state: "California", population: 48508 },
  { slug: "alexandria-louisiana", city: "Alexandria", state: "Louisiana", population: 48426 },
  { slug: "olympia-washington", city: "Olympia", state: "Washington", population: 48338 },
  { slug: "euclid-ohio", city: "Euclid", state: "Ohio", population: 48139 },
  { slug: "mishawaka-indiana", city: "Mishawaka", state: "Indiana", population: 47989 },
  { slug: "salina-kansas", city: "Salina", state: "Kansas", population: 47846 },
  { slug: "azusa-california", city: "Azusa", state: "California", population: 47842 },
  { slug: "newark-ohio", city: "Newark", state: "Ohio", population: 47777 },
  { slug: "chesterfield-missouri", city: "Chesterfield", state: "Missouri", population: 47749 },
  { slug: "leesburg-virginia", city: "Leesburg", state: "Virginia", population: 47673 },
  { slug: "dunwoody-georgia", city: "Dunwoody", state: "Georgia", population: 47591 },
  { slug: "hattiesburg-mississippi", city: "Hattiesburg", state: "Mississippi", population: 47556 },
  { slug: "roseville-michigan", city: "Roseville", state: "Michigan", population: 47555 },
  { slug: "bonita-springs-florida", city: "Bonita Springs", state: "Florida", population: 47547 },
  { slug: "portage-michigan", city: "Portage", state: "Michigan", population: 47523 },
  { slug: "st--louis-park-minnesota", city: "St. Louis Park", state: "Minnesota", population: 47411 },
  { slug: "collierville-tennessee", city: "Collierville", state: "Tennessee", population: 47333 },
  { slug: "middletown-connecticut", city: "Middletown", state: "Connecticut", population: 47333 },
  { slug: "stillwater-oklahoma", city: "Stillwater", state: "Oklahoma", population: 47186 },
  { slug: "east-providence-rhode-island", city: "East Providence", state: "Rhode Island", population: 47149 },
  { slug: "lawrence-indiana", city: "Lawrence", state: "Indiana", population: 47135 },
  { slug: "wauwatosa-wisconsin", city: "Wauwatosa", state: "Wisconsin", population: 47134 },
  { slug: "mentor-ohio", city: "Mentor", state: "Ohio", population: 46979 },
  { slug: "ceres-california", city: "Ceres", state: "California", population: 46714 },
  { slug: "cedar-hill-texas", city: "Cedar Hill", state: "Texas", population: 46663 },
  { slug: "mansfield-ohio", city: "Mansfield", state: "Ohio", population: 46454 },
  { slug: "binghamton-new-york", city: "Binghamton", state: "New York", population: 46444 },
  { slug: "coeur-d-alene-idaho", city: "Coeur d'Alene", state: "Idaho", population: 46402 },
  { slug: "san-luis-obispo-california", city: "San Luis Obispo", state: "California", population: 46377 },
  { slug: "minot-north-dakota", city: "Minot", state: "North Dakota", population: 46321 },
  { slug: "palm-springs-california", city: "Palm Springs", state: "California", population: 46281 },
  { slug: "pine-bluff-arkansas", city: "Pine Bluff", state: "Arkansas", population: 46094 },
  { slug: "texas-city-texas", city: "Texas City", state: "Texas", population: 46081 },
  { slug: "summerville-south-carolina", city: "Summerville", state: "South Carolina", population: 46074 },
  { slug: "twin-falls-idaho", city: "Twin Falls", state: "Idaho", population: 45981 },
  { slug: "jeffersonville-indiana", city: "Jeffersonville", state: "Indiana", population: 45929 },
  { slug: "san-jacinto-california", city: "San Jacinto", state: "California", population: 45851 },
  { slug: "madison-alabama", city: "Madison", state: "Alabama", population: 45799 },
  { slug: "altoona-pennsylvania", city: "Altoona", state: "Pennsylvania", population: 45796 },
  { slug: "columbus-indiana", city: "Columbus", state: "Indiana", population: 45775 },
  { slug: "beavercreek-ohio", city: "Beavercreek", state: "Ohio", population: 45712 },
  { slug: "apopka-florida", city: "Apopka", state: "Florida", population: 45587 },
  { slug: "elmhurst-illinois", city: "Elmhurst", state: "Illinois", population: 45556 },
  { slug: "maricopa-arizona", city: "Maricopa", state: "Arizona", population: 45508 },
  { slug: "farmington-new-mexico", city: "Farmington", state: "New Mexico", population: 45426 },
  { slug: "glenview-illinois", city: "Glenview", state: "Illinois", population: 45417 },
  { slug: "cleveland-heights-ohio", city: "Cleveland Heights", state: "Ohio", population: 45394 },
  { slug: "draper-utah", city: "Draper", state: "Utah", population: 45285 },
  { slug: "lincoln-california", city: "Lincoln", state: "California", population: 45237 },
  { slug: "sierra-vista-arizona", city: "Sierra Vista", state: "Arizona", population: 45129 },
  { slug: "lacey-washington", city: "Lacey", state: "Washington", population: 44919 },
  { slug: "biloxi-mississippi", city: "Biloxi", state: "Mississippi", population: 44820 },
  { slug: "strongsville-ohio", city: "Strongsville", state: "Ohio", population: 44730 },
  { slug: "barnstable-town-massachusetts", city: "Barnstable Town", state: "Massachusetts", population: 44641 },
  { slug: "wylie-texas", city: "Wylie", state: "Texas", population: 44575 },
  { slug: "sayreville-new-jersey", city: "Sayreville", state: "New Jersey", population: 44412 },
  { slug: "kannapolis-north-carolina", city: "Kannapolis", state: "North Carolina", population: 44359 },
  { slug: "charlottesville-virginia", city: "Charlottesville", state: "Virginia", population: 44349 },
  { slug: "littleton-colorado", city: "Littleton", state: "Colorado", population: 44275 },
  { slug: "titusville-florida", city: "Titusville", state: "Florida", population: 44206 },
  { slug: "hackensack-new-jersey", city: "Hackensack", state: "New Jersey", population: 44113 },
  { slug: "newark-california", city: "Newark", state: "California", population: 44096 },
  { slug: "pittsfield-massachusetts", city: "Pittsfield", state: "Massachusetts", population: 44057 },
  { slug: "york-pennsylvania", city: "York", state: "Pennsylvania", population: 43935 },
  { slug: "lombard-illinois", city: "Lombard", state: "Illinois", population: 43907 },
  { slug: "attleboro-massachusetts", city: "Attleboro", state: "Massachusetts", population: 43886 },
  { slug: "dekalb-illinois", city: "DeKalb", state: "Illinois", population: 43849 },
  { slug: "blacksburg-virginia", city: "Blacksburg", state: "Virginia", population: 43609 },
  { slug: "dublin-ohio", city: "Dublin", state: "Ohio", population: 43607 },
  { slug: "haltom-city-texas", city: "Haltom City", state: "Texas", population: 43580 },
  { slug: "lompoc-california", city: "Lompoc", state: "California", population: 43509 },
  { slug: "el-centro-california", city: "El Centro", state: "California", population: 43363 },
  { slug: "danville-california", city: "Danville", state: "California", population: 43341 },
  { slug: "jefferson-city-missouri", city: "Jefferson City", state: "Missouri", population: 43330 },
  { slug: "cutler-bay-florida", city: "Cutler Bay", state: "Florida", population: 43328 },
  { slug: "oakland-park-florida", city: "Oakland Park", state: "Florida", population: 43286 },
  { slug: "north-miami-beach-florida", city: "North Miami Beach", state: "Florida", population: 43250 },
  { slug: "freeport-new-york", city: "Freeport", state: "New York", population: 43167 },
  { slug: "moline-illinois", city: "Moline", state: "Illinois", population: 43116 },
  { slug: "coachella-california", city: "Coachella", state: "California", population: 43092 },
  { slug: "fort-pierce-florida", city: "Fort Pierce", state: "Florida", population: 43074 },
  { slug: "smyrna-tennessee", city: "Smyrna", state: "Tennessee", population: 43060 },
  { slug: "bountiful-utah", city: "Bountiful", state: "Utah", population: 43023 },
  { slug: "fond-du-lac-wisconsin", city: "Fond du Lac", state: "Wisconsin", population: 42970 },
  { slug: "everett-massachusetts", city: "Everett", state: "Massachusetts", population: 42935 },
  { slug: "danville-virginia", city: "Danville", state: "Virginia", population: 42907 },
  { slug: "keller-texas", city: "Keller", state: "Texas", population: 42907 },
  { slug: "belleville-illinois", city: "Belleville", state: "Illinois", population: 42895 },
  { slug: "bell-gardens-california", city: "Bell Gardens", state: "California", population: 42889 },
  { slug: "cleveland-tennessee", city: "Cleveland", state: "Tennessee", population: 42774 },
  { slug: "north-lauderdale-florida", city: "North Lauderdale", state: "Florida", population: 42757 },
  { slug: "fairfield-ohio", city: "Fairfield", state: "Ohio", population: 42635 },
  { slug: "salem-massachusetts", city: "Salem", state: "Massachusetts", population: 42544 },
  { slug: "rancho-palos-verdes-california", city: "Rancho Palos Verdes", state: "California", population: 42448 },
  { slug: "san-bruno-california", city: "San Bruno", state: "California", population: 42443 },
  { slug: "concord-new-hampshire", city: "Concord", state: "New Hampshire", population: 42419 },
  { slug: "burlington-vermont", city: "Burlington", state: "Vermont", population: 42284 },
  { slug: "apex-north-carolina", city: "Apex", state: "North Carolina", population: 42214 },
  { slug: "midland-michigan", city: "Midland", state: "Michigan", population: 42181 },
  { slug: "altamonte-springs-florida", city: "Altamonte Springs", state: "Florida", population: 42150 },
  { slug: "hutchinson-kansas", city: "Hutchinson", state: "Kansas", population: 41889 },
  { slug: "buffalo-grove-illinois", city: "Buffalo Grove", state: "Illinois", population: 41778 },
  { slug: "urbandale-iowa", city: "Urbandale", state: "Iowa", population: 41776 },
  { slug: "state-college-pennsylvania", city: "State College", state: "Pennsylvania", population: 41757 },
  { slug: "urbana-illinois", city: "Urbana", state: "Illinois", population: 41752 },
  { slug: "plainfield-illinois", city: "Plainfield", state: "Illinois", population: 41734 },
  { slug: "manassas-virginia", city: "Manassas", state: "Virginia", population: 41705 },
  { slug: "bartlett-illinois", city: "Bartlett", state: "Illinois", population: 41679 },
  { slug: "kearny-new-jersey", city: "Kearny", state: "New Jersey", population: 41664 },
  { slug: "oro-valley-arizona", city: "Oro Valley", state: "Arizona", population: 41627 },
  { slug: "findlay-ohio", city: "Findlay", state: "Ohio", population: 41512 },
  { slug: "rohnert-park-california", city: "Rohnert Park", state: "California", population: 41398 },
  { slug: "westfield-massachusetts", city: "Westfield", state: "Massachusetts", population: 41301 },
  { slug: "linden-new-jersey", city: "Linden", state: "New Jersey", population: 41301 },
  { slug: "sumter-south-carolina", city: "Sumter", state: "South Carolina", population: 41190 },
  { slug: "wilkes-barre-pennsylvania", city: "Wilkes-Barre", state: "Pennsylvania", population: 41108 },
  { slug: "woonsocket-rhode-island", city: "Woonsocket", state: "Rhode Island", population: 41026 },
  { slug: "leominster-massachusetts", city: "Leominster", state: "Massachusetts", population: 41002 },
  { slug: "shelton-connecticut", city: "Shelton", state: "Connecticut", population: 40999 },
  { slug: "brea-california", city: "Brea", state: "California", population: 40963 },
  { slug: "covington-kentucky", city: "Covington", state: "Kentucky", population: 40956 },
  { slug: "rockwall-texas", city: "Rockwall", state: "Texas", population: 40922 },
  { slug: "riverton-utah", city: "Riverton", state: "Utah", population: 40921 },
  { slug: "meridian-mississippi", city: "Meridian", state: "Mississippi", population: 40921 },
  { slug: "st--cloud-florida", city: "St. Cloud", state: "Florida", population: 40918 },
  { slug: "quincy-illinois", city: "Quincy", state: "Illinois", population: 40915 },
  { slug: "morgan-hill-california", city: "Morgan Hill", state: "California", population: 40836 },
  { slug: "warren-ohio", city: "Warren", state: "Ohio", population: 40768 },
  { slug: "edmonds-washington", city: "Edmonds", state: "Washington", population: 40727 },
  { slug: "burleson-texas", city: "Burleson", state: "Texas", population: 40714 },
  { slug: "beverly-massachusetts", city: "Beverly", state: "Massachusetts", population: 40664 },
  { slug: "mankato-minnesota", city: "Mankato", state: "Minnesota", population: 40641 },
  { slug: "hagerstown-maryland", city: "Hagerstown", state: "Maryland", population: 40612 },
  { slug: "prescott-arizona", city: "Prescott", state: "Arizona", population: 40590 },
  { slug: "campbell-california", city: "Campbell", state: "California", population: 40584 },
  { slug: "cedar-falls-iowa", city: "Cedar Falls", state: "Iowa", population: 40566 },
  { slug: "beaumont-california", city: "Beaumont", state: "California", population: 40481 },
  { slug: "la-puente-california", city: "La Puente", state: "California", population: 40435 },
  { slug: "crystal-lake-illinois", city: "Crystal Lake", state: "Illinois", population: 40388 },
  { slug: "fitchburg-massachusetts", city: "Fitchburg", state: "Massachusetts", population: 40383 },
  { slug: "carol-stream-illinois", city: "Carol Stream", state: "Illinois", population: 40379 },
  { slug: "hickory-north-carolina", city: "Hickory", state: "North Carolina", population: 40361 },
  { slug: "streamwood-illinois", city: "Streamwood", state: "Illinois", population: 40351 },
  { slug: "norwich-connecticut", city: "Norwich", state: "Connecticut", population: 40347 },
  { slug: "coppell-texas", city: "Coppell", state: "Texas", population: 40342 },
  { slug: "san-gabriel-california", city: "San Gabriel", state: "California", population: 40275 },
  { slug: "holyoke-massachusetts", city: "Holyoke", state: "Massachusetts", population: 40249 },
  { slug: "bentonville-arkansas", city: "Bentonville", state: "Arkansas", population: 40167 },
  { slug: "peachtree-corners-georgia", city: "Peachtree Corners", state: "Georgia", population: 40059 },
  { slug: "florence-alabama", city: "Florence", state: "Alabama", population: 40059 },
  { slug: "brentwood-tennessee", city: "Brentwood", state: "Tennessee", population: 40021 },
  { slug: "bozeman-montana", city: "Bozeman", state: "Montana", population: 39860 },
  { slug: "new-berlin-wisconsin", city: "New Berlin", state: "Wisconsin", population: 39834 },
  { slug: "goose-creek-south-carolina", city: "Goose Creek", state: "South Carolina", population: 39823 },
  { slug: "huntsville-texas", city: "Huntsville", state: "Texas", population: 39795 },
  { slug: "prescott-valley-arizona", city: "Prescott Valley", state: "Arizona", population: 39791 },
  { slug: "maplewood-minnesota", city: "Maplewood", state: "Minnesota", population: 39765 },
  { slug: "romeoville-illinois", city: "Romeoville", state: "Illinois", population: 39650 },
  { slug: "duncanville-texas", city: "Duncanville", state: "Texas", population: 39605 },
  { slug: "atlantic-city-new-jersey", city: "Atlantic City", state: "New Jersey", population: 39551 },
  { slug: "clovis-new-mexico", city: "Clovis", state: "New Mexico", population: 39508 },
  { slug: "the-colony-texas", city: "The Colony", state: "Texas", population: 39458 },
];

export function getCity(slug: string) {
  return CITIES.find((c) => c.slug === slug);
}
