import type { Article } from "./journal";

/** Third and final batch of the 2026-08 addition — clears 100+ new articles
 * combined with journal-new-2026-08.ts and journal-new-2026-08b.ts. */
export const NEW_ARTICLES_2026_08C: Article[] = [
  {
    slug: "menopause-hormone-therapy-updated-safety-guidance",
    title: "Menopause hormone therapy: how the safety guidance has changed since the original WHI panic",
    dek: "The 2002 Women's Health Initiative results reshaped hormone therapy prescribing for two decades — newer analysis has meaningfully revised that picture.",
    date: "2026-05-04",
    readTime: "5 min",
    category: "Longevity",
    body: [
      "The original 2002 Women's Health Initiative findings, which reported increased breast cancer and cardiovascular risk with hormone therapy, led to a sharp, sustained decline in hormone therapy prescribing that persisted for roughly two decades. Subsequent re-analysis, accounting for the age and time-since-menopause of the original trial population, found that much of the elevated risk was concentrated in women who started therapy later after menopause onset — a distinction the initial headline findings didn't capture clearly.",
      "Current menopause society guidelines now generally support hormone therapy as a reasonable, often favorable option for symptomatic women within roughly ten years of menopause onset or under age 60, with the risk-benefit profile shifting less favorably for women starting therapy later — the 'timing hypothesis' that's emerged from this re-analysis is now a central part of how the decision is framed clinically.",
      "This is a genuinely individualized decision depending on personal and family cancer history, cardiovascular risk factors, and symptom severity — the practical takeaway from the revised evidence isn't 'hormone therapy is safe for everyone' but that the blanket avoidance that followed the original 2002 findings swept in many women who academic re-analysis suggests could have reasonably benefited, which is worth raising directly with a menopause-informed physician rather than assuming the original headline risk still applies uniformly.",
    ],
  },
  {
    slug: "perimenopause-symptoms-underrecognized-diagnosis-gap",
    title: "Perimenopause symptoms are widely underrecognized — here's what the research says clinicians miss",
    dek: "The transition years before menopause proper carry a symptom pattern that's frequently misattributed to other causes.",
    date: "2026-05-03",
    readTime: "4 min",
    category: "Longevity",
    body: [
      "Perimenopause — the transition period, often lasting several years, leading up to menopause — involves fluctuating rather than simply declining hormone levels, which produces a broader and less predictable symptom pattern than menopause itself: irregular cycles, mood changes, sleep disruption, brain fog, and hot flashes that can begin years before a woman's periods actually stop, often while she's still cycling regularly enough that menopause isn't yet suspected as the cause.",
      "Surveys of women experiencing perimenopausal symptoms have found many report their symptoms were initially attributed to stress, depression, or other causes before perimenopause was raised as an explanation — a diagnostic gap partly attributable to limited menopause-specific training historically included in general medical education, an issue that professional societies have specifically flagged and begun addressing through updated curricula.",
      "For anyone in their late 30s to mid-40s experiencing a new pattern of mood changes, sleep disruption, or cycle irregularity without an obvious cause, explicitly raising perimenopause as a possibility — rather than waiting for a physician to suggest it — is a reasonable step given how commonly it gets initially misattributed to other causes.",
    ],
  },
  {
    slug: "endometriosis-diagnosis-delay-research-explained",
    title: "Why endometriosis diagnosis takes an average of years — the research behind the delay",
    dek: "Studies consistently find a long gap between symptom onset and diagnosis for this common condition — the reasons are specific and partly addressable.",
    date: "2026-05-02",
    readTime: "5 min",
    category: "Longevity",
    body: [
      "Endometriosis, a condition where tissue similar to the uterine lining grows outside the uterus, affects a substantial share of women of reproductive age, yet research across multiple countries has consistently found a diagnostic delay averaging several years from symptom onset to confirmed diagnosis — one of the longer diagnostic delays documented for a common condition.",
      "Contributing factors identified in this research include normalization of severe menstrual pain (both by patients themselves and, historically, by clinicians who didn't fully investigate pain dismissed as 'normal periods'), the historical reliance on laparoscopic surgery for definitive diagnosis rather than a simpler test, and symptom overlap with other conditions like irritable bowel syndrome that can lead diagnosis down a different path initially.",
      "Diagnostic approaches are evolving — while laparoscopy remains the definitive diagnostic standard, imaging techniques (specialized transvaginal ultrasound and MRI protocols) have improved enough that some cases can now be identified with reasonable confidence non-surgically, which specialist guidelines increasingly incorporate into earlier-stage evaluation rather than requiring surgery as the first diagnostic step for every suspected case.",
    ],
  },
  {
    slug: "iron-deficiency-without-anemia-fatigue-research",
    title: "Iron deficiency without anemia: an underrecognized cause of fatigue the standard blood test can miss",
    dek: "A normal hemoglobin doesn't rule out iron deficiency — a specific additional test is needed, and it's not always ordered by default.",
    date: "2026-05-01",
    readTime: "4 min",
    category: "Nutrition",
    body: [
      "Iron deficiency can exist well before it progresses to iron-deficiency anemia — the body depletes stored iron (reflected in ferritin levels) before hemoglobin production is affected enough to show up as anemia on a standard complete blood count, meaning a 'normal' CBC doesn't rule out a genuine iron deficiency that could be contributing to fatigue, hair loss, or reduced exercise tolerance.",
      "Research on iron-deficiency-without-anemia has found it's associated with meaningful fatigue and reduced quality of life even without meeting the anemia threshold, and studies specifically testing iron supplementation in non-anemic but iron-deficient women with unexplained fatigue have found measurable symptom improvement — evidence that the deficiency itself, not just the downstream anemia, has a real functional cost.",
      "Ferritin testing, which reflects iron stores directly rather than the downstream hemoglobin effect, isn't always included in a routine blood panel by default — for anyone with persistent unexplained fatigue, particularly menstruating women who lose iron regularly, specifically requesting a ferritin level alongside a standard CBC closes a gap that routine testing sometimes leaves open.",
    ],
  },
  {
    slug: "postpartum-recovery-timeline-fourth-trimester-research",
    title: "The 'fourth trimester': what the postpartum recovery research actually says about timelines",
    dek: "Physical recovery from childbirth extends well beyond the traditional six-week checkup, and the evidence supports a longer, more structured view.",
    date: "2026-04-30",
    readTime: "5 min",
    category: "Longevity",
    body: [
      "The traditional single postpartum visit around six weeks after delivery has been increasingly criticized by obstetric professional societies as insufficient given the actual physiological recovery timeline — research on postpartum recovery has found that many physical changes (pelvic floor function, cardiovascular adaptation, hormonal normalization) continue well beyond six weeks, in some measures extending to a year or more postpartum.",
      "This evidence gap is part of why the American College of Obstetricians and Gynecologists now recommends ongoing postpartum contact rather than a single visit — an initial check within the first three weeks and a comprehensive visit by twelve weeks, with the explicit goal of catching issues (postpartum depression, pelvic floor dysfunction, cardiovascular symptoms) that a single six-week checkup can miss if they emerge earlier or persist later.",
      "Pelvic floor dysfunction specifically has strong evidence for benefiting from targeted physical therapy rather than the historical 'give it time' approach — studies on postpartum pelvic floor physical therapy have found meaningful improvement in incontinence and pelvic pain symptoms, yet referral remains inconsistent across providers, making it worth requesting directly rather than assuming it will be offered automatically.",
    ],
  },
  {
    slug: "picky-eating-versus-arfid-when-to-seek-help",
    title: "Picky eating vs. ARFID: when restrictive eating in children needs professional evaluation",
    dek: "Most picky eating is developmentally normal — a distinct clinical condition looks different and has specific warning signs.",
    date: "2026-04-29",
    readTime: "4 min",
    category: "Nutrition",
    body: [
      "Ordinary picky eating — food preferences, texture aversions, and selective eating that most children display to some degree — is developmentally common and typically doesn't significantly impact growth, nutrition, or daily functioning. Avoidant/Restrictive Food Intake Disorder (ARFID), a distinct diagnosis added to clinical classification systems relatively recently, is characterized by restriction severe enough to cause nutritional deficiency, dependence on supplements to meet nutritional needs, significant weight or growth impact, or meaningful interference with daily social functioning.",
      "The distinguishing features clinicians look for beyond simple pickiness include an extremely narrow accepted food list (sometimes fewer than ten foods total), lack of the typical hunger-driven flexibility that eventually leads picky eaters to try new foods when hungry enough, and physical growth or nutritional lab markers showing an actual measurable impact — features that separate ARFID from the far more common, non-clinical picky eating most children display.",
      "For families managing a child whose eating restriction seems to exceed typical pickiness — particularly with documented growth concerns or nutritional deficiency — evaluation by a pediatric feeding specialist or a team including a pediatrician, dietitian, and often a psychologist trained in feeding disorders is the evidence-supported path, since ARFID responds to structured, specialized intervention differently than typical pickiness responds to general parenting strategies.",
    ],
  },
  {
    slug: "screen-time-child-development-research-nuance",
    title: "Screen time and child development: what the research actually supports beyond the headlines",
    dek: "The relationship between screen exposure and developmental outcomes is more dependent on content and context than blanket time limits suggest.",
    date: "2026-04-28",
    readTime: "5 min",
    category: "Longevity",
    body: [
      "Research on screen time and child development has moved considerably beyond simple total-hours metrics toward examining content type, context (co-viewing with a parent versus solo use), and what activity the screen time is displacing — studies controlling for these factors generally find weaker and more nuanced associations with developmental outcomes than early alarm-driven headlines suggested, though genuine concerns remain for specific patterns.",
      "The clearer negative associations in the research tend to involve screen use that displaces sleep, physical activity, or in-person social interaction, and content that's specifically fast-paced or lacks educational structure — rather than screen exposure as a uniform category. Co-viewing with active parental engagement and discussion has shown more favorable outcomes in several studies compared to identical content consumed solo, suggesting the social context of screen use matters as much as the screen itself.",
      "Pediatric guideline bodies have accordingly shifted messaging somewhat from rigid time-limit numbers toward a more contextual framework emphasizing content quality, co-viewing, and ensuring screen time doesn't crowd out sleep, activity, and unstructured play — a more nuanced position than the earlier blanket-hour-limit guidance that dominated public messaging for years.",
    ],
  },
  {
    slug: "seasonal-affective-disorder-light-therapy-evidence",
    title: "Light therapy for seasonal affective disorder: the specific protocol the evidence actually supports",
    dek: "Not all light boxes and usage patterns are equally effective — the trial evidence points to specific intensity, timing, and duration parameters.",
    date: "2026-04-27",
    readTime: "4 min",
    category: "Longevity",
    body: [
      "Bright light therapy has some of the strongest evidence of any non-pharmacological treatment for seasonal affective disorder, with multiple randomized trials and meta-analyses finding effect sizes comparable to antidepressant medication for this specific condition — a notably strong evidence base for a non-drug intervention.",
      "The trial-validated protocol is more specific than casually sitting near a bright lamp: typically 10,000 lux light intensity, used for 20-30 minutes each morning, ideally shortly after waking, with the light positioned at an angle to indirectly reach the eyes rather than requiring direct staring at the source — deviating meaningfully from these parameters (lower lux, evening timing, inconsistent use) has less supporting trial evidence and anecdotally less effect.",
      "Timing appears to matter mechanistically, not just as a scheduling convenience — morning light exposure is thought to help realign circadian rhythm timing that's disrupted in seasonal affective disorder, which is part of why evening use hasn't shown comparable results in trials and in some cases has been associated with sleep disruption instead of benefit.",
    ],
  },
  {
    slug: "fecal-microbiota-transplant-approved-uses-research",
    title: "Fecal microbiota transplant: the one FDA-approved use and the many unapproved ones under study",
    dek: "FMT has a specific, well-established medical application and a much larger, still-experimental research frontier that's easy to conflate.",
    date: "2026-04-26",
    readTime: "4 min",
    category: "Health Technology",
    body: [
      "Fecal microbiota transplant — transferring processed stool from a screened donor to a recipient, typically via colonoscopy, enema, or oral capsule — has strong, well-established evidence and formal FDA-approved products specifically for recurrent Clostridioides difficile infection that hasn't responded to standard antibiotic treatment, where cure rates in trials have been notably high compared to further antibiotic courses.",
      "Beyond this specific approved use, FMT is being actively researched for a range of other conditions — inflammatory bowel disease, certain metabolic conditions, and some neurological and psychiatric conditions under the gut-brain axis research umbrella — but evidence for these applications remains considerably earlier stage, with more mixed and preliminary results than the C. diff use case, and none currently have FDA-approved indications.",
      "The FDA has specifically warned about unregulated FMT products and unsupervised use outside clinical settings, given documented cases of serious infection transmission from inadequately screened donor material — a real risk that underscores why FMT for its approved use, and any experimental use, should go through a proper clinical setting with donor screening protocols rather than unregulated sourcing.",
    ],
  },
  {
    slug: "long-covid-research-current-understanding-treatment",
    title: "Long COVID research: what's become clearer and what remains genuinely unresolved",
    dek: "Several years into sustained research funding, some mechanisms and treatment approaches have solidified while others remain actively contested.",
    date: "2026-04-25",
    readTime: "5 min",
    category: "Health Technology",
    body: [
      "Long COVID research has established that symptoms persisting well beyond acute infection are real, measurable, and biologically grounded rather than purely psychological — studies have documented objective findings including persistent inflammation markers, autonomic nervous system dysfunction, and in some patients, viral persistence in tissue reservoirs beyond the acute infection period, providing biological mechanisms for symptoms that were sometimes dismissed early in the pandemic.",
      "Post-exertional malaise — symptom worsening after physical or cognitive exertion, sometimes delayed by a day or more — has emerged as a particularly important and distinct symptom pattern, overlapping considerably with the pattern seen in myalgic encephalomyelitis/chronic fatigue syndrome, and current clinical guidance for long COVID patients experiencing this pattern generally recommends pacing and activity management rather than the graded exercise therapy once more broadly recommended for fatigue conditions, since graded exercise has been shown to worsen symptoms in patients with genuine post-exertional malaise.",
      "Treatment remains largely symptom-management focused rather than curative, since no single approved treatment addresses the underlying condition directly — multidisciplinary long COVID clinics, where available, generally show better patient-reported outcomes than single-specialist management, likely reflecting the genuinely multi-system nature of the condition that a single specialty often can't fully address alone.",
    ],
  },
  {
    slug: "vaccine-hesitancy-communication-research-what-works",
    title: "What actually changes vaccine-hesitant minds — the communication research, not the assumptions",
    dek: "Public health messaging research has tested specific approaches against each other, and some intuitive strategies perform worse than expected.",
    date: "2026-04-24",
    readTime: "5 min",
    category: "Clinical & Institutional",
    body: [
      "Research on vaccine hesitancy communication has consistently found that simply presenting more scientific data or correcting misinformation directly is often ineffective and can sometimes backfire, reinforcing existing skepticism rather than reducing it — a finding that runs against the intuitive assumption that hesitancy stems primarily from an information gap that more facts would close.",
      "Approaches that have performed better in controlled studies include motivational interviewing techniques — a non-confrontational, question-based approach originally developed for other behavior-change contexts — and messaging from trusted messengers within a person's own community or social network, which tends to outperform messaging from unfamiliar authority figures even when the factual content is identical.",
      "Trust in the messenger and the process, rather than volume of information delivered, emerges consistently as the stronger predictor of attitude change across this research — a finding with implications beyond vaccines specifically, since it suggests health communication generally may be more effective when it prioritizes relationship and process over information density alone.",
    ],
  },
  {
    slug: "clinical-trial-participation-patient-access-research",
    title: "How patients actually find and access clinical trials — and why most eligible patients never enroll",
    dek: "A large share of clinical trials struggle to enroll enough participants, and the barriers are more structural than lack of patient interest.",
    date: "2026-04-23",
    readTime: "5 min",
    category: "Clinical & Institutional",
    body: [
      "Research on clinical trial enrollment barriers has consistently found that only a small fraction of eligible patients for a given trial actually enroll, and lack of interest isn't the primary driver — studies have found that a substantial share of eligible patients were simply never informed that a relevant trial existed, since trial awareness typically depends on their specific treating physician being aware of and mentioning it, which isn't systematic.",
      "Geographic and logistical barriers compound the awareness gap — many trials, particularly for specialized conditions, are concentrated at academic medical centers, and travel burden for repeated trial visits disproportionately excludes patients without flexible work schedules, reliable transportation, or nearby lodging, which has been documented to skew trial populations away from broader representativeness.",
      "Patient-facing trial registries (like ClinicalTrials.gov) and matching services have improved discoverability somewhat, allowing patients to search directly rather than relying entirely on their physician's awareness, but research on their actual use suggests many patients don't know these tools exist — for anyone with a serious diagnosis where standard treatment options are limited, proactively searching trial registries and asking a specialist directly about trial eligibility, rather than waiting to be offered one, meaningfully changes access odds given the documented information gap.",
    ],
  },
  {
    slug: "electronic-health-record-patient-portal-underuse",
    title: "Patient portals are underused for one of their most useful features — here's what most people skip",
    dek: "Most patients log into a portal only to check test results, missing functions research shows meaningfully improve care coordination.",
    date: "2026-04-22",
    readTime: "4 min",
    category: "Clinical & Institutional",
    body: [
      "Studies of patient portal usage patterns consistently find that viewing lab results and appointment scheduling dominate actual use, while features like secure messaging with the care team, medication list review, and downloading a complete visit summary go substantially underused relative to how often they'd be clinically useful — particularly for patients seeing multiple specialists who don't automatically share records with each other.",
      "The feature with a specific, documented care-coordination benefit that's most commonly overlooked is the downloadable or shareable visit summary and full record export — bringing a complete, accurate medication and problem list to a new specialist or a hospital visit has been associated in care-transition research with fewer medication errors and redundant testing compared to relying on the patient's memory or an outside provider's incomplete record.",
      "For patients managing a chronic condition across multiple providers, actively using portal messaging to flag discrepancies between what different specialists have on file — rather than assuming each provider automatically sees the others' notes — closes a coordination gap that remains common even with electronic records, since most health systems still don't share data seamlessly across different providers' separate EHR platforms.",
    ],
  },
];
