export type Category =
  | "oxygen-portable"
  | "oxygen-stationary"
  | "oxygen-tank"
  | "oxygen-accessory"
  | "sleep-cpap"
  | "sleep-bipap"
  | "sleep-travel"
  | "sleep-mask"
  | "sleep-cleaner"
  | "respiratory-accessory"
  | "ventilator"
  | "oxygen-rental"
  | "cpap-rental";

export type Badge = "Rental" | "Refurbished" | "Sale" | "Discontinued";

export type Product = {
  slug: string;
  name: string;
  brand: string;
  category: Category;
  price: number | null; // null = call for pricing
  compareAt?: number;
  spec?: string; // real, disclosed spec string only — never fabricated
  faaApproved?: boolean;
  badge?: Badge;
  rxRequired: boolean;
  image?: string; // real product photo path under /public/products — never a stock/placeholder substitute
  specs?: [string, string][]; // real, disclosed full spec table — never fabricated
};

export const CATEGORY_META: Record<Category, { label: string; base: string }> = {
  "oxygen-portable": { label: "Portable Oxygen Concentrators", base: "/oxygen/portable" },
  "oxygen-stationary": { label: "Stationary Oxygen Concentrators", base: "/oxygen/stationary" },
  "oxygen-tank": { label: "Oxygen Tanks & Cylinders", base: "/oxygen/tanks" },
  "oxygen-accessory": { label: "Oxygen Accessories", base: "/oxygen/accessories" },
  "sleep-cpap": { label: "CPAP Machines", base: "/sleep/cpap" },
  "sleep-bipap": { label: "BiPAP & VPAP Machines", base: "/sleep/bipap-apap" },
  "sleep-travel": { label: "Travel CPAP", base: "/sleep/cpap" },
  "sleep-mask": { label: "CPAP Masks", base: "/sleep/accessories" },
  "sleep-cleaner": { label: "CPAP Cleaners", base: "/sleep/accessories" },
  "respiratory-accessory": { label: "Respiratory Accessories", base: "/respiratory-accessories" },
  "ventilator": { label: "Ventilators", base: "/ventilators" },
  "oxygen-rental": { label: "Oxygen Concentrator Rentals", base: "/rentals" },
  "cpap-rental": { label: "CPAP & BiPAP Rentals", base: "/rentals" },
};

function href(p: Pick<Product, "category" | "slug">) {
  return `${CATEGORY_META[p.category].base}/${p.slug}`;
}

export const PRODUCTS: Product[] = [
  // ── Portable oxygen concentrators ──────────────────────────────────
  { slug: "inogen-rove-6", name: "Inogen Rove 6", brand: "Inogen", category: "oxygen-portable", price: null, faaApproved: true, rxRequired: true , image: "/products/inogen-rove-6.png" , specs: [["Weight", "4.8 lbs (standard battery)"], ["Dimensions", "8.27\" x 3.03\" x 7.56\""], ["Flow Settings", "1-6 Pulse Dose"], ["Battery Life", "6-13 hours"], ["Noise Level", "37 dBA"], ["Oxygen Purity", "87-96%"], ["Warranty", "3 Years"]] },
  { slug: "inogen-rove-4", name: "Inogen Rove 4", brand: "Inogen", category: "oxygen-portable", price: null, faaApproved: true, rxRequired: true , image: "/products/inogen-rove-4.png" , specs: [["Weight", "2.9 lbs (standard battery)"], ["Dimensions", "5.91\" x 2.68\" x 7.2\""], ["Flow Settings", "1-4 Pulse Dose"], ["Battery Life", "2.5-8 hours"], ["Noise Level", "40 dBA"], ["Oxygen Purity", "87-96%"], ["Warranty", "3 Years"]] },
  { slug: "caire-freestyle-comfort", name: "Caire FreeStyle Comfort", brand: "Caire", category: "oxygen-portable", price: 2995, faaApproved: true, rxRequired: true , image: "/products/caire-freestyle-comfort.png" , specs: [["Weight", "5 lbs (with battery)"], ["Dimensions", "10\" x 7.3\" x 3.1\""], ["Flow Settings", "1-5 Pulse Dose"], ["Battery Life", "8-16 hours"], ["Noise Level", "43 dBA"], ["Oxygen Purity", "90% ± 6%"], ["Warranty", "3 Years"]] },
  { slug: "oxygo-fit", name: "OxyGo FIT", brand: "OxyGo", category: "oxygen-portable", price: 1995, faaApproved: true, rxRequired: true , image: "/products/oxygo-fit.png" , specs: [["Weight", "4.8 lbs"], ["Dimensions", "8.75\" x 3.5\" x 7.25\""], ["Flow Settings", "1-5 Pulse Dose"], ["Battery Life", "6.5-13 hours"], ["Noise Level", "40 dBA"], ["Warranty", "3 Years"]] },
  { slug: "oxygo-next", name: "OxyGo NEXT", brand: "OxyGo", category: "oxygen-portable", price: 1995, compareAt: 2195, faaApproved: true, badge: "Sale", rxRequired: true , image: "/products/oxygo-next.png" , specs: [["Weight", "4.7 lbs"], ["Flow Settings", "1-6 Pulse Dose"], ["Battery Life", "6.5 hrs (single) / 13 hrs (double)"], ["Warranty", "5 Years (concentrator), 1 Year (sieve beds & battery)"]] },
  { slug: "oxygo-fit-plus", name: "OxyGo FIT+", brand: "OxyGo", category: "oxygen-portable", price: null, spec: "2.9 lbs · 4 pulse settings · up to 5h 49m battery (double)", rxRequired: true , image: "/products/oxygo-fit-plus.png" , specs: [["Weight", "2.9 lbs (single battery) / 3.4 lbs (double)"], ["Dimensions", "5.8\" x 2.7\" x 7.5\""], ["Flow Settings", "1-4 Pulse Dose"], ["Battery Life", "Up to 3 hrs (single) / 5h 49m (double)"], ["Noise Level", "39 dBA (setting 2)"], ["Warranty", "3 Years"]] },
  { slug: "oxygo-next-ng", name: "OxyGo NEXT NG", brand: "OxyGo", category: "oxygen-portable", price: null, spec: "4.8 lbs · 6 pulse settings · up to 12h 45m battery (double)", rxRequired: true , image: "/products/oxygo-next.png" , specs: [["Weight", "4.8 lbs (single battery) / 5.8 lbs (double)"], ["Flow Settings", "1-6 Pulse Dose"], ["Battery Life", "Up to 6.25 hrs (single) / 12.75 hrs (double)"], ["Noise Level", "39 dBA (setting 2)"], ["Warranty", "5 Years"]] },
  { slug: "caire-eclipse-5", name: "Caire Eclipse 5", brand: "Caire", category: "oxygen-portable", price: 3200, faaApproved: true, rxRequired: true , image: "/products/caire-eclipse-5.png" , specs: [["Weight", "18.4 lbs (with battery)"], ["Dimensions", "19.3\" x 12.3\" x 7\""], ["Continuous Flow", "0.5-3 LPM"], ["Pulse Dose", "Settings 1-9"], ["Battery Life", "Up to 5 hours (pulse)"], ["Noise Level", "48 dBA"], ["Oxygen Purity", "90% ± 6%"], ["Warranty", "3 Years"]] },
  { slug: "drive-devilbiss-igo2", name: "Drive DeVilbiss iGo2", brand: "Drive DeVilbiss", category: "oxygen-portable", price: 1995, compareAt: 2295, faaApproved: true, badge: "Sale", rxRequired: true , image: "/products/drive-devilbiss-igo2.png" , specs: [["Weight", "4.8 lbs (with battery)"], ["Dimensions", "8.7\" x 3.5\" x 7.25\""], ["Flow Settings", "1-5 Pulse Dose"], ["Battery Life", "6.5-13 hours"], ["Noise Level", "40 dBA"], ["Oxygen Purity", "87-96%"], ["Warranty", "3 Years"]] },
  { slug: "o2-concepts-oxlife-independence", name: "O2 Concepts Oxlife Independence", brand: "O2 Concepts", category: "oxygen-portable", price: null, spec: "16.7 lbs · 0.5–3 LPM continuous / 1–6 pulse · up to 6.25h battery (dual)", faaApproved: true, rxRequired: true , image: "/products/o2-concepts-oxlife-independence.png" , specs: [["Weight", "16.7 lbs"], ["Continuous Flow", "0.5-3 LPM"], ["Pulse Dose", "Settings 1-6"], ["Battery Life", "Up to 6.25 hrs (dual battery)"], ["Warranty", "5 Years"]] },
  { slug: "resmed-mobi", name: "ResMed Mobi", brand: "ResMed", category: "oxygen-portable", price: 3195, spec: "5.5 lbs, 1-4 Pulse Dose, up to 13h combined battery", faaApproved: true, rxRequired: true , image: "/products/resmed-mobi.jpg" , specs: [["Weight", "5.5 lbs"], ["Dimensions", "9.6\" x 4.49\" x 7.95\""], ["Flow Settings", "1-4 Pulse Dose"], ["Battery Life", "8.6 hrs internal (13 hrs with external battery)"], ["Warranty", "5 Years"]] },
  { slug: "gce-zen-o-lite", name: "GCE Zen-O lite", brand: "GCE", category: "oxygen-portable", price: 2695, spec: "4.6 lbs, 1-5 Pulse Dose, 37 dBA", faaApproved: true, rxRequired: true , image: "/products/gce-zen-o-lite.jpg" , specs: [["Weight", "4.6 lbs (5.5 lbs with battery)"], ["Flow Settings", "1-5 Pulse Dose (0.5 increments)"], ["Noise Level", "37 dBA"], ["Oxygen Purity", "87-96%"], ["Warranty", "3 Years (machine), 1 Year (accessories)"]] },

  // ── Manufacturer-discontinued — final inventory only ─────────────────
  // These are no longer manufactured (Philips exited the US sleep/respiratory
  // device market in Jan 2024; Precision Medical's EasyPulse line is fully
  // discontinued). Sold as final inventory, not authorized-new stock — the
  // "Discontinued" badge and PDP notice make that distinction explicit.
  { slug: "precision-medical-easypulse-5", name: "Precision Medical EasyPulse POC 5", brand: "Precision Medical", category: "oxygen-portable", price: 1895, compareAt: 2295, spec: "USA-made · manufacturer-discontinued", faaApproved: true, badge: "Discontinued", rxRequired: true , image: "/products/precision-medical-easypulse-5.png" , specs: [["Weight", "5.5 lbs (with battery)"], ["Dimensions", "9.8\" x 4.3\" x 7.5\""], ["Flow Settings", "1-5 Pulse Dose"], ["Battery Life", "5-10 hours"], ["Noise Level", "40 dBA"], ["Oxygen Purity", "87-96%"], ["Warranty", "3 Years (5 Years Sieve Bed)"]] },
  { slug: "philips-simplygo", name: "Philips Respironics SimplyGo", brand: "Philips Respironics", category: "oxygen-portable", price: null, spec: "10 lbs · continuous 0.5–2 LPM / pulse to 6 · manufacturer-discontinued", faaApproved: true, badge: "Discontinued", rxRequired: true , image: "/products/philips-simplygo.jpg" , specs: [["Weight", "10 lbs"], ["Continuous Flow", "0.5-2 LPM"], ["Pulse Dose", "Settings 1-6"], ["Battery Life", "0.9-3.7 hours (setting-dependent)"], ["Warranty", "2, 3, or 5 Years (buyer's choice)"]] },
  { slug: "philips-simplygo-mini", name: "Philips Respironics SimplyGo Mini", brand: "Philips Respironics", category: "oxygen-portable", price: null, spec: "5 lbs · 5 pulse settings · up to 9h battery (extended) · manufacturer-discontinued", faaApproved: true, badge: "Discontinued", rxRequired: true , image: "/products/philips-simplygo-mini.jpg" , specs: [["Weight", "5 lbs (standard battery) / 6 lbs (extended)"], ["Dimensions", "9.4\" x 8.3\" x 3.6\""], ["Flow Settings", "1-5 Pulse Dose"], ["Battery Life", "4.5 hrs (standard) / 9 hrs (extended)"], ["Oxygen Purity", "87-96%"], ["Warranty", "3 Years"]] },

  // ── Refurbished portable oxygen ─────────────────────────────────────
  { slug: "refurbished-inogen-g5", name: "Refurbished Inogen One G5", brand: "Inogen", category: "oxygen-portable", price: null, faaApproved: true, badge: "Refurbished", rxRequired: true , image: "/products/refurbished-inogen-g5.png" , specs: [["Weight", "4.8 lbs (standard battery)"], ["Dimensions", "8.27\" x 3.03\" x 7.56\""], ["Flow Settings", "1-6 Pulse Dose"], ["Battery Life", "6-13 hours"], ["Noise Level", "37 dBA"], ["Oxygen Purity", "87-96%"], ["Warranty", "3 Years"]] },
  { slug: "refurbished-caire-freestyle-comfort", name: "Refurbished Caire FreeStyle Comfort", brand: "Caire", category: "oxygen-portable", price: 2995, faaApproved: true, badge: "Refurbished", rxRequired: true , image: "/products/refurbished-caire-freestyle-comfort.png" , specs: [["Weight", "5 lbs (with battery)"], ["Dimensions", "10\" x 7.3\" x 3.1\""], ["Flow Settings", "1-5 Pulse Dose"], ["Battery Life", "8-16 hours"], ["Noise Level", "43 dBA"], ["Oxygen Purity", "90% ± 6%"], ["Warranty", "3 Years"]] },
  { slug: "refurbished-caire-eclipse-5", name: "Refurbished Caire Eclipse 5", brand: "Caire", category: "oxygen-portable", price: 3200, faaApproved: true, badge: "Refurbished", rxRequired: true , image: "/products/refurbished-caire-eclipse-5.png" , specs: [["Weight", "18.4 lbs (with battery)"], ["Dimensions", "19.3\" x 12.3\" x 7\""], ["Continuous Flow", "0.5-3 LPM"], ["Pulse Dose", "Settings 1-9"], ["Battery Life", "Up to 5 hours (pulse)"], ["Noise Level", "48 dBA"], ["Oxygen Purity", "90% ± 6%"], ["Warranty", "3 Years"]] },
  { slug: "refurbished-drive-devilbiss-igo2", name: "Refurbished Drive DeVilbiss iGo2", brand: "Drive DeVilbiss", category: "oxygen-portable", price: 1095, compareAt: 1395, faaApproved: true, badge: "Refurbished", rxRequired: true , image: "/products/refurbished-drive-devilbiss-igo2.png" , specs: [["Weight", "4.8 lbs (with battery)"], ["Dimensions", "8.7\" x 3.5\" x 7.25\""], ["Flow Settings", "1-5 Pulse Dose"], ["Battery Life", "6.5-13 hours"], ["Noise Level", "40 dBA"], ["Oxygen Purity", "87-96%"], ["Warranty", "3 Years"]] },
  { slug: "refurbished-inogen-rove-4", name: "Refurbished Inogen Rove 4", brand: "Inogen", category: "oxygen-portable", price: null, faaApproved: true, badge: "Refurbished", rxRequired: true , image: "/products/refurbished-inogen-rove-4.png" , specs: [["Weight", "2.9 lbs (standard battery)"], ["Dimensions", "5.91\" x 2.68\" x 7.2\""], ["Flow Settings", "1-4 Pulse Dose"], ["Battery Life", "2.5-8 hours"], ["Noise Level", "40 dBA"], ["Oxygen Purity", "87-96%"], ["Warranty", "3 Years"]] },

  // ── Stationary oxygen concentrators ─────────────────────────────────
  { slug: "caire-companion-5", name: "Caire Companion 5", brand: "Caire", category: "oxygen-stationary", price: 995, compareAt: 1095, spec: "0.5–5 LPM Continuous Flow", badge: "Sale", rxRequired: true , image: "/products/caire-companion-5.png" , specs: [["Flow Rate", "0.5-5 LPM Continuous"], ["Weight", "34 lbs"], ["Dimensions", "18.5\" x 9.5\" x 16.5\""], ["Noise Level", "40 dBA"], ["Oxygen Purity", "93% ± 3%"], ["Power", "310 Watts"], ["Warranty", "3 Years"]] },
  { slug: "drive-devilbiss-525ds", name: "Drive DeVilbiss 525DS", brand: "Drive DeVilbiss", category: "oxygen-stationary", price: 749, compareAt: 895, spec: "0.5–5 LPM Continuous Flow", badge: "Sale", rxRequired: true , image: "/products/drive-devilbiss-525ds.jpg" , specs: [["Flow Rate", "0.5-5 LPM"], ["Weight", "38 lbs"], ["Dimensions", "23\" x 13.5\" x 12\""], ["Noise Level", "40 dBA"], ["Oxygen Purity", "93% ± 3%"], ["Power", "310 Watts"], ["Warranty", "3 Years"]] },
  { slug: "caire-newlife-intensity-10", name: "Caire NewLife Intensity 10", brand: "Caire", category: "oxygen-stationary", price: 1995, spec: "2–10 LPM Continuous Flow", rxRequired: true , image: "/products/caire-newlife-intensity-10.jpg" , specs: [["Flow Rate", "2-10 LPM"], ["Weight", "58 lbs"], ["Dimensions", "27.5\" x 14.5\" x 15.5\""], ["Noise Level", "50 dBA"], ["Oxygen Purity", "87-96%"], ["Power", "600 Watts"], ["Warranty", "5 Years"]] },
  { slug: "philips-everflo-q", name: "Philips EverFlo Q", brand: "Philips Respironics", category: "oxygen-stationary", price: 749, spec: "1–5 LPM Continuous Flow", rxRequired: true , image: "/products/philips-everflo-q.jpg" , specs: [["Flow Rate", "1-5 LPM"], ["Weight", "31 lbs"], ["Dimensions", "23\" x 15\" x 9.5\""], ["Noise Level", "40 dBA"], ["Power", "350 Watts"], ["Warranty", "3 Years"]] },
  { slug: "invacare-platinum-10", name: "Invacare Platinum 10", brand: "Invacare", category: "oxygen-stationary", price: 1595, compareAt: 1895, spec: "2–10 LPM Continuous Flow", badge: "Sale", rxRequired: true , image: "/products/invacare-platinum-10.jpg" },
  { slug: "invacare-perfecto2-v", name: "Invacare Perfecto2 V", brand: "Invacare", category: "oxygen-stationary", price: 995, compareAt: 1295, spec: "0.5–5 LPM Continuous Flow", badge: "Sale", rxRequired: true , image: "/products/invacare-perfecto2-v.jpg" , specs: [["Flow Rate", "0.5-5 LPM"], ["Weight", "40 lbs (18.1 kg)"], ["Dimensions", "15\" x 23\" x 12\""], ["Noise Level", "40 dBA"], ["Oxygen Purity", "87-95.6%"], ["Power", "340 Watts"], ["Warranty", "3 Years"]] },
  { slug: "philips-everflo", name: "Philips Respironics EverFlo", brand: "Philips Respironics", category: "oxygen-stationary", price: 749, compareAt: 895, spec: "1–5 LPM Continuous Flow", badge: "Sale", rxRequired: true , image: "/products/philips-everflo.jpg" , specs: [["Flow Rate", "1-5 LPM"], ["Weight", "31 lbs (14 kg)"], ["Dimensions", "23\" x 15\" x 9.5\""], ["Noise Level", "40 dBA"], ["Oxygen Purity", "93% ± 3%"], ["Power", "350 Watts"], ["Warranty", "3 Years"]] },
  { slug: "philips-simplyflo", name: "Philips Respironics SimplyFlo", brand: "Philips Respironics", category: "oxygen-stationary", price: 649, compareAt: 795, spec: "0.5–2 LPM Continuous Flow", badge: "Sale", rxRequired: true , image: "/products/philips-simplyflo.jpg" , specs: [["Flow Rate", "0.5-2 LPM"], ["Weight", "8.5 lbs (3.9 kg)"], ["Dimensions", "10\" x 11.5\" x 6\""], ["Noise Level", "50 dBA"], ["Oxygen Purity", "90% ± 3%"], ["Power", "120 Watts"], ["Voltage", "100-240 VAC, 50/60 Hz"], ["Warranty", "3 Years"]] },
  { slug: "inogen-at-home-gs-100", name: "Inogen At Home GS-100", brand: "Inogen", category: "oxygen-stationary", price: null, spec: "1–5 LPM Continuous Flow", rxRequired: true , image: "/products/inogen-at-home-gs-100.jpg" , specs: [["Flow Rate", "1-5 LPM"], ["Weight", "18 lbs (8.2 kg)"], ["Dimensions", "13\" x 16.5\" x 7\""], ["Noise Level", "40 dBA"], ["Oxygen Purity", "90% ± 3% at 2 LPM"], ["Power", "100W at 2 LPM, 260W Max"], ["Altitude Rating", "Up to 10,000 ft"], ["Warranty", "5 Years"]] },
  { slug: "inogen-voxi-5", name: "Inogen Voxi 5", brand: "Inogen", category: "oxygen-stationary", price: null, spec: "1–5 LPM Continuous Flow", rxRequired: true , image: "/products/inogen-voxi-5.jpg" , specs: [["Flow Rate", "1-5 LPM Continuous"], ["Weight", "34.2 lbs (15.5 kg)"], ["Dimensions", "15.35\" x 9.65\" x 19.69\""], ["Noise Level", "45 dBA (Flow Setting 2)"], ["Oxygen Purity", "87-96% at 1-5 LPM"], ["Power", "120V, 60Hz, 350VA"], ["Sieve Bed Warranty", "3 Years / 8,000 hours"], ["Warranty", "3 or 5 Years"]] },

  // ── Refurbished stationary oxygen ───────────────────────────────────
  { slug: "refurbished-philips-everflo", name: "Refurbished Philips EverFlo", brand: "Philips Respironics", category: "oxygen-stationary", price: 395, compareAt: 495, badge: "Refurbished", rxRequired: true , image: "/products/refurbished-philips-everflo.jpg" , specs: [["Flow Rate", "1-5 LPM"], ["Weight", "31 lbs (14 kg)"], ["Dimensions", "23\" x 15\" x 9.5\""], ["Noise Level", "40 dBA"], ["Oxygen Purity", "93% ± 3%"], ["Power", "350 Watts"], ["Warranty", "3 Years"]] },
  { slug: "refurbished-invacare-platinum-10", name: "Refurbished Invacare Platinum 10", brand: "Invacare", category: "oxygen-stationary", price: 695, compareAt: 895, badge: "Refurbished", rxRequired: true , image: "/products/refurbished-invacare-platinum-10.jpg" },
  { slug: "refurbished-caire-companion-5", name: "Refurbished Caire Companion 5", brand: "Caire", category: "oxygen-stationary", price: 995, badge: "Refurbished", rxRequired: true , image: "/products/refurbished-caire-companion-5.png" , specs: [["Flow Rate", "0.5-5 LPM Continuous"], ["Weight", "34 lbs"], ["Dimensions", "18.5\" x 9.5\" x 16.5\""], ["Noise Level", "40 dBA"], ["Oxygen Purity", "93% ± 3%"], ["Power", "310 Watts"], ["Warranty", "3 Years"]] },
  { slug: "refurbished-devilbiss-525ds", name: "Refurbished DeVilbiss 525DS", brand: "Drive DeVilbiss", category: "oxygen-stationary", price: 395, compareAt: 545, badge: "Refurbished", rxRequired: true , image: "/products/refurbished-devilbiss-525ds.jpg" , specs: [["Flow Rate", "0.5-5 LPM"], ["Weight", "38 lbs"], ["Dimensions", "23\" x 13.5\" x 12\""], ["Noise Level", "40 dBA"], ["Oxygen Purity", "93% ± 3%"], ["Power", "310 Watts"], ["Warranty", "3 Years"]] },
  { slug: "refurbished-invacare-perfecto2-v", name: "Refurbished Invacare Perfecto2 V", brand: "Invacare", category: "oxygen-stationary", price: 349, compareAt: 495, badge: "Refurbished", rxRequired: true , image: "/products/refurbished-invacare-perfecto2-v.jpg" , specs: [["Flow Rate", "0.5-5 LPM"], ["Weight", "40 lbs (18.1 kg)"], ["Dimensions", "15\" x 23\" x 12\""], ["Noise Level", "40 dBA"], ["Oxygen Purity", "87-95.6%"], ["Power", "340 Watts"], ["Warranty", "3 Years"]] },

  // ── Oxygen tanks & cylinders ─────────────────────────────────────────
  { slug: "m6-cylinder-regulator", name: "M6 Portable Oxygen Cylinder with Regulator", brand: "800Oxygen", category: "oxygen-tank", price: 159, compareAt: 189, spec: "Lightweight aluminum", badge: "Sale", rxRequired: false , image: "/products/m6-cylinder-regulator.jpg" , specs: [["Capacity", "165 Liters"], ["Weight (Empty)", "1.5 lbs"], ["Height", "11.5 in"], ["Diameter", "3.2 in"], ["Material", "Aluminum"], ["Valve Type", "CGA 870"], ["Pressure", "2000 PSI"]] },
  { slug: "m9-cylinder-conserving-regulator", name: "M9 Oxygen Cylinder with Conserving Regulator", brand: "800Oxygen", category: "oxygen-tank", price: 199, compareAt: 229, spec: "Conserving regulator", badge: "Sale", rxRequired: false , image: "/products/m9-cylinder-conserving-regulator.png" , specs: [["Capacity", "248 Liters"], ["Weight (Empty)", "2.5 lbs"], ["Height", "15 in"], ["Diameter", "3.2 in"], ["Material", "Aluminum"], ["Valve Type", "CGA 870"], ["Flow Settings", "1-6 Pulse Dose"]] },
  { slug: "m4-mini-tank-regulator-kit", name: "M4 Mini Oxygen Tank with Regulator Kit", brand: "800Oxygen", category: "oxygen-tank", price: 129, compareAt: 149, spec: "Ultra-compact", badge: "Sale", rxRequired: false , image: "/products/m4-mini-tank-regulator-kit.jpg" },
  { slug: "d-size-cylinder-cart", name: "D-Size Oxygen Cylinder with Cart", brand: "800Oxygen", category: "oxygen-tank", price: 249, compareAt: 279, spec: "Wheeled cart included", badge: "Sale", rxRequired: false , image: "/products/d-size-cylinder-cart.jpg" , specs: [["Capacity", "425 Liters"], ["Weight (Empty)", "5 lbs"], ["Height", "17 in"], ["Diameter", "4.4 in"], ["Material", "Aluminum"], ["Valve Type", "CGA 870"], ["Cart Weight Capacity", "25 lbs"], ["Warranty", "3 Years"]] },
  { slug: "e-size-cylinder-setup", name: "E-Size Oxygen Cylinder Complete Setup", brand: "800Oxygen", category: "oxygen-tank", price: 289, compareAt: 329, spec: "Complete setup", badge: "Sale", rxRequired: false , image: "/products/e-size-cylinder-setup.jpg" , specs: [["Capacity", "679 Liters"], ["Weight (Empty)", "8 lbs"], ["Height", "26 in"], ["Diameter", "4.4 in"], ["Material", "Aluminum"], ["Valve Type", "CGA 870"], ["Flow Rate", "0.5-15 LPM"], ["Warranty", "5 Years"]] },
  { slug: "m-size-high-capacity-cylinder", name: "M-Size High Capacity Oxygen Cylinder", brand: "800Oxygen", category: "oxygen-tank", price: 399, compareAt: 449, spec: "High capacity", badge: "Sale", rxRequired: false , image: "/products/m-size-high-capacity-cylinder.jpg" , specs: [["Capacity", "3,455 Liters"], ["Weight (Empty)", "63 lbs"], ["Height", "43 in"], ["Diameter", "7 in"], ["Material", "Steel"], ["Valve Type", "CGA 540"], ["Pressure", "2200 PSI"], ["Warranty", "10 Years"]] },
  { slug: "h-size-jumbo-cylinder", name: "H-Size Jumbo Oxygen Cylinder", brand: "800Oxygen", category: "oxygen-tank", price: 499, compareAt: 549, spec: "Maximum capacity", badge: "Sale", rxRequired: false , image: "/products/h-size-jumbo-cylinder.jpg" , specs: [["Capacity", "6,910 Liters"], ["Weight (Empty)", "135 lbs"], ["Height", "55 in"], ["Diameter", "9 in"], ["Material", "Steel"], ["Valve Type", "CGA 540"], ["Pressure", "2200 PSI"], ["Warranty", "10 Years"]] },
  { slug: "cga-870-regulator-flow-meter", name: "Oxygen Regulator CGA 870 with Flow Meter", brand: "800Oxygen", category: "oxygen-tank", price: 69, compareAt: 89, spec: "CGA 870 connection", badge: "Sale", rxRequired: false , image: "/products/cga-870-regulator-flow-meter.jpg" , specs: [["Connection", "CGA 870 Yoke"], ["Flow Range", "0-15 LPM"], ["Inlet Pressure", "2000 PSI Max"], ["Outlet", "DISS 1240"], ["Material", "Brass/Chrome"], ["Certification", "FDA, DOT"], ["Warranty", "2 Years"]] },
  { slug: "conserving-regulator-pulse-dose", name: "Oxygen Conserving Regulator with Pulse Dose", brand: "800Oxygen", category: "oxygen-tank", price: 149, compareAt: 179, spec: "Extends tank life 3x", badge: "Sale", rxRequired: false , image: "/products/conserving-regulator-pulse-dose.jpg" , specs: [["Connection", "CGA 870 Yoke"], ["Flow Settings", "1-6 Pulse Dose"], ["Inlet Pressure", "2200 PSI Max"], ["Outlet", "DISS 1240"], ["Weight", "0.7 lbs"], ["Battery", "1 AA (2000 hrs)"]] },
  { slug: "dual-tank-cart-de", name: "Dual Oxygen Tank Cart for D/E Cylinders", brand: "800Oxygen", category: "oxygen-tank", price: 99, compareAt: 129, spec: "Holds 2 D or E tanks", badge: "Sale", rxRequired: false , image: "/products/dual-tank-cart-de.jpg" , specs: [["Capacity", "2 x D/E Cylinders"], ["Frame Material", "Steel"], ["Weight Capacity", "50 lbs"], ["Wheel Size", "8 in"], ["Cart Weight", "12 lbs"], ["Finish", "Powder Coated"], ["Dimensions", "24\" x 18\" x 36\""]] },
  { slug: "m6-m9-shoulder-bag", name: "M6/M9 Oxygen Tank Shoulder Bag", brand: "800Oxygen", category: "oxygen-tank", price: 39, compareAt: 49, spec: "Fits M6 and M9 tanks", badge: "Sale", rxRequired: false , image: "/products/m6-m9-shoulder-bag.png" , specs: [["Fits", "M6, M9 Cylinders"], ["Material", "600D Nylon"], ["Strap Length", "24\"-48\" Adjustable"], ["Pockets", "1 Exterior"], ["Weight", "0.5 lbs"], ["Color", "Black"], ["Warranty", "1 Year"]] },
  { slug: "h-tank-stand-casters", name: "H-Tank Stand with Casters", brand: "800Oxygen", category: "oxygen-tank", price: 159, compareAt: 189, spec: "For H/M size tanks", badge: "Sale", rxRequired: false , image: "/products/h-tank-stand-casters.jpg" , specs: [["Fits", "H, M Size Cylinders"], ["Material", "Steel"], ["Weight Capacity", "200 lbs"], ["Caster Size", "3 in"], ["Base Width", "18 in"], ["Height", "55 in"], ["Finish", "Chrome Plated"]] },

  // ── Oxygen accessories ────────────────────────────────────────────
  { slug: "inogen-g5-16-cell-battery", name: "Inogen One G5 16-Cell Battery", brand: "Inogen", category: "oxygen-accessory", price: null, spec: "Up to 13 hrs battery life", rxRequired: false , image: "/products/inogen-g5-16-cell-battery.png" , specs: [["Compatibility", "Inogen One G5, Rove 6"], ["Capacity", "16-Cell Lithium-Ion"], ["Weight", "1.27 lbs"], ["Run Time", "6.5-13 hours"], ["Charge Time", "4-5 hours"], ["Warranty", "1 Year"]] },
  { slug: "inogen-g5-8-cell-battery", name: "Inogen One G5 8-Cell Battery", brand: "Inogen", category: "oxygen-accessory", price: null, spec: "Up to 6.5 hrs battery life", rxRequired: false , image: "/products/inogen-g5-8-cell-battery.png" , specs: [["Compatibility", "Inogen One G5, Rove 6"], ["Capacity", "8-Cell Lithium-Ion"], ["Weight", "0.64 lbs"], ["Run Time", "3.25-6.5 hours"], ["Charge Time", "2-3 hours"], ["Warranty", "1 Year"]] },
  { slug: "inogen-g3-16-cell-battery", name: "Inogen One G3 16-Cell Battery", brand: "Inogen", category: "oxygen-accessory", price: null, spec: "Up to 8 hrs battery life", rxRequired: false , image: "/products/inogen-g3-16-cell-battery.jpg" , specs: [["Compatibility", "Inogen One G3"], ["Capacity", "16-Cell Lithium-Ion"], ["Weight", "1.1 lbs"], ["Run Time", "4-8 hours"], ["Charge Time", "4-5 hours"], ["Warranty", "1 Year"]] },
  { slug: "inogen-g3-8-cell-battery", name: "Inogen One G3 8-Cell Battery", brand: "Inogen", category: "oxygen-accessory", price: null, spec: "Up to 4.5 hrs battery life", rxRequired: false , image: "/products/inogen-g3-8-cell-battery.jpg" , specs: [["Compatibility", "Inogen One G3"], ["Capacity", "8-Cell Lithium-Ion"], ["Weight", "0.6 lbs"], ["Run Time", "2.25-4.5 hours"], ["Charge Time", "2-3 hours"], ["Warranty", "1 Year"]] },
  { slug: "inogen-g4-8-cell-battery", name: "Inogen One G4 8-Cell Battery", brand: "Inogen", category: "oxygen-accessory", price: null, spec: "Up to 5 hrs battery life", rxRequired: false , image: "/products/inogen-g4-8-cell-battery.jpg" , specs: [["Compatibility", "Inogen One G4, Rove 4"], ["Capacity", "8-Cell Lithium-Ion"], ["Weight", "0.52 lbs"], ["Run Time", "2.5-5 hours"], ["Charge Time", "3-4 hours"], ["Warranty", "1 Year"]] },
  { slug: "inogen-g4-4-cell-battery", name: "Inogen One G4 4-Cell Battery", brand: "Inogen", category: "oxygen-accessory", price: null, spec: "Up to 2.7 hrs battery life", rxRequired: false , image: "/products/inogen-g4-4-cell-battery.png" , specs: [["Compatibility", "Inogen One G4, Rove 4"], ["Capacity", "4-Cell Lithium-Ion"], ["Weight", "0.26 lbs"], ["Run Time", "1.35-2.7 hours"], ["Charge Time", "2-3 hours"], ["Warranty", "1 Year"]] },
  { slug: "universal-poc-carrying-case", name: "Universal POC Carrying Case", brand: "800Oxygen", category: "oxygen-accessory", price: 49, spec: "Fits most POC models", rxRequired: false },

  // ── CPAP machines ─────────────────────────────────────────────────
  { slug: "resmed-airsense-11-autoset", name: "ResMed AirSense 11 AutoSet", brand: "ResMed", category: "sleep-cpap", price: 949, compareAt: 1099, spec: "Auto-Adjusting Pressure 4–20 cmH₂O", badge: "Sale", rxRequired: true , image: "/products/resmed-airsense-11-autoset.jpg" , specs: [["Pressure Range", "4-20 cm H2O"], ["Weight", "2.75 lbs"], ["Dimensions", "10.16\" x 4.76\" x 5.91\""], ["Humidifier", "Built-in HumidAir"], ["Connectivity", "Cellular, Wi-Fi, Bluetooth"], ["Warranty", "2 Years"]] },
  { slug: "philips-dreamstation-2", name: "Philips DreamStation 2 Auto CPAP", brand: "Philips Respironics", category: "sleep-cpap", price: 849, compareAt: 999, spec: "Auto-Adjusting Pressure Therapy", badge: "Sale", rxRequired: true , image: "/products/philips-dreamstation-2.jpg" },
  { slug: "resmed-airsense-10-autoset", name: "ResMed AirSense 10 AutoSet", brand: "ResMed", category: "sleep-cpap", price: 699, compareAt: 799, spec: "Auto-Adjusting Pressure 4–20 cmH₂O", badge: "Sale", rxRequired: true , image: "/products/resmed-airsense-10-autoset.jpg" , specs: [["Pressure Range", "4-20 cm H2O"], ["Weight", "2.75 lbs"], ["Dimensions", "10.2\" x 5.9\" x 4.6\""], ["Humidifier", "Built-in HumidAir"], ["Connectivity", "SD Card, Optional Wireless"], ["Warranty", "2 Years"]] },
  { slug: "resmed-airsense-10-autoset-for-her", name: "ResMed AirSense 10 AutoSet for Her", brand: "ResMed", category: "sleep-cpap", price: 749, compareAt: 849, spec: "AutoSet for Her algorithm", badge: "Sale", rxRequired: true , image: "/products/resmed-airsense-10-autoset-for-her.jpg" , specs: [["Pressure Range", "4-20 cm H2O"], ["Weight", "2.75 lbs"], ["Dimensions", "10.2\" x 5.9\" x 4.6\""], ["Humidifier", "Built-in HumidAir"], ["Connectivity", "SD Card, Optional Wireless"], ["Warranty", "2 Years"]] },
  { slug: "f-p-sleepstyle", name: "Fisher & Paykel SleepStyle Auto CPAP", brand: "Fisher & Paykel", category: "sleep-cpap", price: 849, compareAt: 999, spec: "SensAwake wake detection", badge: "Sale", rxRequired: true , image: "/products/f-p-sleepstyle.png" , specs: [["Pressure Range", "4-20 cm H2O"], ["Weight", "3.3 lbs"], ["Humidifier", "Integrated ThermoSmart"], ["Noise Level", "26 dBA"], ["Connectivity", "Bluetooth"], ["Warranty", "2 Years"]] },
  { slug: "resmed-airsense-11-elite", name: "ResMed AirSense 11 Elite", brand: "ResMed", category: "sleep-cpap", price: 849, compareAt: 949, spec: "Fixed pressure 4–20 cmH₂O", badge: "Sale", rxRequired: true , image: "/products/resmed-airsense-11-elite.png" , specs: [["Pressure Range", "4-20 cm H2O"], ["Weight", "2.75 lbs"], ["Dimensions", "10.16\" x 4.76\" x 5.91\""], ["Humidifier", "Built-in HumidAir"], ["Connectivity", "Cellular, Wi-Fi, Bluetooth"], ["Warranty", "2 Years"]] },
  { slug: "resmed-airsense-10-elite", name: "ResMed AirSense 10 Elite", brand: "ResMed", category: "sleep-cpap", price: 599, compareAt: 649, spec: "Fixed pressure 4–20 cmH₂O", badge: "Sale", rxRequired: true , image: "/products/resmed-airsense-10-elite.jpg" , specs: [["Pressure Range", "4-20 cm H2O"], ["Weight", "2.75 lbs"], ["Dimensions", "10.2\" x 5.9\" x 4.6\""], ["Humidifier", "Built-in HumidAir"], ["Connectivity", "SD Card"], ["Warranty", "2 Years"]] },
  { slug: "bmc-resmart-gii", name: "BMC RESmart GII Auto CPAP", brand: "BMC Medical", category: "sleep-cpap", price: 549, spec: "RESlex exhalation relief, integrated humidifier", rxRequired: true , image: "/products/bmc-resmart-gii.jpg" , specs: [["Pressure Range", "4-20 cm H2O"], ["Weight", "3.3 lbs (5.5 lbs with humidifier)"], ["Humidifier", "Integrated Heated (350 mL)"], ["Noise Level", "≤28 dBA"], ["Display", "3.5\" Color LCD"], ["Warranty", "2 Years"]] },
  { slug: "drive-devilbiss-intellipap-2", name: "DeVilbiss IntelliPAP 2 AutoAdjust", brand: "Drive DeVilbiss", category: "sleep-cpap", price: 649, spec: "PureView AutoAdjust algorithm", rxRequired: true , image: "/products/drive-devilbiss-intellipap-2.jpg" , specs: [["Pressure Range", "4-20 cm H2O"], ["Weight", "1.93 lbs"], ["Dimensions", "5.9\" x 6.1\" x 3.7\""], ["Comfort Feature", "SmartFlex Exhalation Relief"], ["Connectivity", "Bluetooth (SmartLink)"], ["Warranty", "3 Years"]] },
  { slug: "luna-ii-auto-cpap", name: "3B Medical Luna II Auto CPAP", brand: "3B Medical", category: "sleep-cpap", price: 649, spec: "Dual-Channel Quad-Phase technology", rxRequired: true , image: "/products/luna-ii-auto-cpap.jpg" , specs: [["Pressure Range", "4-20 cm H2O"], ["Weight", "4 lbs (1.9 kg)"], ["Dimensions", "10.75\" x 7.25\" x 4.5\""], ["Humidifier", "Integrated, heated (360 mL)"], ["Warranty", "2 Years"]] },

  // ── Travel CPAP ───────────────────────────────────────────────────
  { slug: "resmed-airmini", name: "ResMed AirMini", brand: "ResMed", category: "sleep-travel", price: 849, spec: "World's smallest CPAP", faaApproved: true, rxRequired: true , image: "/products/resmed-airmini.jpg" , specs: [["Weight", "0.66 lbs"], ["Dimensions", "5.4\" x 3.3\" x 2.1\""], ["Pressure Range", "4-20 cm H2O"], ["Power", "AC/DC/Battery"]] },
  { slug: "transcend-365-auto", name: "Transcend 365 Auto miniCPAP", brand: "Somnetics", category: "sleep-travel", price: 599, spec: "Integrated battery", faaApproved: true, rxRequired: true , image: "/products/transcend-365-auto.jpg" , specs: [["Weight", "0.8 lbs"], ["Battery", "Integrated Li-Ion"], ["Pressure Range", "4-20 cm H2O"], ["Noise Level", "28 dBA"], ["Warranty", "2 Years"]] },
  { slug: "philips-dreamstation-go", name: "Philips DreamStation Go Auto Travel CPAP", brand: "Philips Respironics", category: "sleep-travel", price: 849, spec: "Automatic altitude compensation to 7,500 ft", faaApproved: true, rxRequired: true , image: "/products/philips-dreamstation-go.jpg" , specs: [["Weight", "Under 2 lbs (without battery)"], ["Dimensions", "5.9\" x 5.9\" x 2.3\""], ["Pressure Range", "Auto-adjusting, breath-by-breath"], ["Battery Runtime", "Up to 13 hrs (optional battery)"], ["Warranty", "2 Years"]] },

  // ── BiPAP / VPAP ──────────────────────────────────────────────────
  { slug: "resmed-stellar-150", name: "ResMed Stellar 150", brand: "ResMed", category: "sleep-bipap", price: 4995, rxRequired: true , image: "/products/resmed-stellar-150.webp" },
  { slug: "resmed-astral-150", name: "ResMed Astral 150", brand: "ResMed", category: "sleep-bipap", price: 8995, rxRequired: true , image: "/products/resmed-astral-150.webp" },
  { slug: "resmed-astral-100", name: "ResMed Astral 100", brand: "ResMed", category: "sleep-bipap", price: 7495, rxRequired: true , image: "/products/resmed-astral-100.webp" , specs: [["IPAP", "4-40 cm H2O"], ["EPAP", "2-25 cm H2O"], ["Weight", "7.7 lbs (3.5 kg)"], ["Battery", "Internal, 8+ hours"], ["Modes", "S, ST, T, CPAP, iVAPS"], ["Display", "4.3\" Color Touchscreen"], ["Warranty", "2 Years"]] },
  { slug: "resmed-lumis-150-vpap-st", name: "ResMed Lumis 150 VPAP ST", brand: "ResMed", category: "sleep-bipap", price: 2995, rxRequired: true , image: "/products/resmed-lumis-150-vpap-st.webp" , specs: [["IPAP", "4-30 cm H2O"], ["EPAP", "4-25 cm H2O"], ["Weight", "2.75 lbs"], ["Dimensions", "10.2\" x 5.9\" x 4.6\""], ["Modes", "S, ST, T, iVAPS, PAC"], ["Humidifier", "Built-in HumidAir"], ["Warranty", "2 Years"]] },
  { slug: "resmed-lumis-100-vpap-s", name: "ResMed Lumis 100 VPAP S", brand: "ResMed", category: "sleep-bipap", price: 2495, rxRequired: true , image: "/products/resmed-lumis-100-vpap-s.webp" , specs: [["IPAP", "4-25 cm H2O"], ["EPAP", "4-20 cm H2O"], ["Weight", "2.75 lbs"], ["Dimensions", "10.2\" x 5.9\" x 4.6\""], ["Modes", "S Mode"], ["Humidifier", "Built-in HumidAir"], ["Warranty", "2 Years"]] },
  { slug: "resmed-aircurve-10-vauto", name: "ResMed AirCurve 10 VAuto", brand: "ResMed", category: "sleep-bipap", price: 1695, spec: "Auto bilevel therapy", rxRequired: true , image: "/products/resmed-aircurve-10-vauto.jpg" , specs: [["IPAP", "4-25 cm H2O"], ["EPAP", "4-20 cm H2O"], ["Weight", "2.75 lbs"], ["Humidifier", "Built-in HumidAir"], ["Connectivity", "Cellular, Wi-Fi"], ["Warranty", "2 Years"]] },
  { slug: "philips-dreamstation-bipap", name: "Philips DreamStation BiPAP", brand: "Philips Respironics", category: "sleep-bipap", price: 1495, rxRequired: true , image: "/products/philips-dreamstation-bipap.png" , specs: [["IPAP", "4-25 cm H2O"], ["EPAP", "4-20 cm H2O"], ["Weight", "2.95 lbs"], ["Humidifier", "Integrated"]] },
  { slug: "drive-devilbiss-intellipap-autobilevel", name: "DeVilbiss IntelliPAP Auto Bilevel", brand: "Drive DeVilbiss", category: "sleep-bipap", price: 1295, spec: "Auto-adjusting bilevel with AutoAdjust algorithm", rxRequired: true , image: "/products/drive-devilbiss-intellipap-autobilevel.jpg" , specs: [["Modes", "Fixed and Auto Bilevel"], ["Humidifier", "Integrated Heated"], ["Connectivity", "Bluetooth (SmartLink)"], ["Warranty", "3 Years"]] },
  { slug: "resmed-aircurve-10-s", name: "ResMed AirCurve 10 S", brand: "ResMed", category: "sleep-bipap", price: 1395, compareAt: 1595, badge: "Sale", rxRequired: true , image: "/products/resmed-aircurve-10-s.jpg" , specs: [["IPAP", "4-25 cm H2O"], ["EPAP", "4-25 cm H2O"], ["Weight", "2.75 lbs (1.25 kg)"], ["Dimensions", "10.2\" x 5.9\" x 4.6\""], ["Noise Level", "26 dBA"], ["Humidifier", "Integrated HumidAir"], ["Data", "SD Card & Wireless"], ["Warranty", "2 Years"]] },
  { slug: "resmed-aircurve-10-st", name: "ResMed AirCurve 10 ST", brand: "ResMed", category: "sleep-bipap", price: 1995, compareAt: 2295, badge: "Sale", rxRequired: true , image: "/products/resmed-aircurve-10-st.jpg" , specs: [["IPAP", "4-25 cm H2O"], ["EPAP", "4-25 cm H2O"], ["Backup Rate", "0-30 BPM"], ["Weight", "2.75 lbs (1.25 kg)"], ["Dimensions", "10.2\" x 5.9\" x 4.6\""], ["Noise Level", "26 dBA"], ["Humidifier", "Integrated HumidAir"], ["Warranty", "2 Years"]] },
  { slug: "resmed-aircurve-10-asv", name: "ResMed AirCurve 10 ASV", brand: "ResMed", category: "sleep-bipap", price: 3995, compareAt: 4495, badge: "Sale", rxRequired: true , image: "/products/resmed-aircurve-10-asv.jpg" , specs: [["EPAP", "4-15 cm H2O"], ["PS Min", "0 cm H2O"], ["PS Max", "3-15 cm H2O"], ["Weight", "2.75 lbs (1.25 kg)"], ["Dimensions", "10.2\" x 5.9\" x 4.6\""], ["Noise Level", "26 dBA"], ["Humidifier", "Integrated HumidAir"], ["Warranty", "2 Years"]] },

  // ── Masks ─────────────────────────────────────────────────────────
  { slug: "resmed-airfit-f30", name: "ResMed AirFit F30 Full Face Mask", brand: "ResMed", category: "sleep-mask", price: 159, compareAt: 189, spec: "Full face · under-nose cushion", badge: "Sale", rxRequired: false , image: "/products/resmed-airfit-f30.jpg" , specs: [["Type", "Full Face"], ["Cushion Material", "Silicone"], ["Sizes", "Small, Medium, Large"], ["Headgear", "Included"], ["Frame Sizes", "Standard, Small"], ["Warranty", "90 Days"]] },
  { slug: "resmed-airfit-n30", name: "ResMed AirFit N30 Nasal Mask", brand: "ResMed", category: "sleep-mask", price: 139, spec: "Nasal · cradle cushion", rxRequired: false , image: "/products/resmed-airfit-n30.jpg" , specs: [["Type", "Nasal Cradle"], ["Cushion Material", "Silicone"], ["Sizes", "Small, Medium, Wide"], ["Headgear", "Included"], ["Weight", "45g"], ["Warranty", "90 Days"]] },
  { slug: "resmed-airfit-p10", name: "ResMed AirFit P10 Nasal Pillow Mask", brand: "ResMed", category: "sleep-mask", price: 99, compareAt: 119, spec: "Nasal pillow · QuietAir venting", badge: "Sale", rxRequired: false , image: "/products/resmed-airfit-p10.jpg" , specs: [["Type", "Nasal Pillow"], ["Cushion Material", "Silicone Dual-Wall"], ["Sizes", "XS, S, M, L"], ["Headgear", "Included"], ["Weight", "50g"], ["Noise Level", "21 dBA"], ["Warranty", "90 Days"]] },
  { slug: "resmed-airtouch-f20", name: "ResMed AirTouch F20 Memory Foam Full Face Mask", brand: "ResMed", category: "sleep-mask", price: 199, spec: "Full face · memory foam cushion", rxRequired: false , image: "/products/resmed-airtouch-f20.jpg" , specs: [["Type", "Full Face"], ["Cushion", "UltraSoft Memory Foam"], ["Sizes", "Small, Medium, Large"], ["Headgear", "Included"], ["Frame Sizes", "Standard, Small"], ["Cushion Life", "30 Days"], ["Warranty", "90 Days"]] },
  { slug: "resmed-airfit-f20", name: "ResMed AirFit F20 Full Face Mask", brand: "ResMed", category: "sleep-mask", price: 149, compareAt: 169, spec: "Full face · InfinitySeal cushion", badge: "Sale", rxRequired: false , image: "/products/resmed-airfit-f20.jpg" , specs: [["Type", "Full Face"], ["Cushion", "InfinitySeal Silicone"], ["Sizes", "Small, Medium, Large"], ["Frame", "Standard, Small"], ["Headgear", "Included"], ["Warranty", "90 Days"]] },
  { slug: "resmed-airfit-n20", name: "ResMed AirFit N20 Nasal Mask", brand: "ResMed", category: "sleep-mask", price: 129, compareAt: 149, spec: "Nasal · InfinitySeal cushion", badge: "Sale", rxRequired: false , image: "/products/resmed-airfit-n20.jpg" , specs: [["Type", "Nasal"], ["Cushion", "InfinitySeal Silicone"], ["Sizes", "Small, Medium, Large"], ["Frame", "Standard, Small"], ["Headgear", "Included"], ["Warranty", "90 Days"]] },
  { slug: "resmed-airfit-p30i", name: "ResMed AirFit P30i Nasal Pillow Mask", brand: "ResMed", category: "sleep-mask", price: 115, compareAt: 139, spec: "Nasal pillow · top-of-head tube", badge: "Sale", rxRequired: false , image: "/products/resmed-airfit-p30i.jpg" , specs: [["Type", "Nasal Pillow"], ["Tube Connection", "Top-of-Head"], ["Sizes", "Small, Medium, Large"], ["Frame", "Standard, Small"], ["Headgear", "Included"], ["Warranty", "90 Days"]] },
  { slug: "resmed-airfit-n30i", name: "ResMed AirFit N30i Nasal Cradle Mask", brand: "ResMed", category: "sleep-mask", price: 121, compareAt: 145, spec: "Nasal · top-of-head tube", badge: "Sale", rxRequired: false , image: "/products/resmed-airfit-n30i.jpg" , specs: [["Type", "Nasal Cradle"], ["Tube Connection", "Top-of-Head"], ["Cushion Sizes", "Small, Medium, Large, Wide"], ["Frame", "Standard, Small"], ["Headgear", "Included"], ["Warranty", "90 Days"]] },
  { slug: "resmed-airfit-f30i", name: "ResMed AirFit F30i Full Face Mask", brand: "ResMed", category: "sleep-mask", price: 159, compareAt: 179, spec: "Full face · top-of-head tube", badge: "Sale", rxRequired: false , image: "/products/resmed-airfit-f30i.jpg" , specs: [["Type", "Full Face"], ["Tube Connection", "Top-of-Head"], ["Cushion Sizes", "Small, Medium, Wide"], ["Frame", "Standard, Small"], ["Headgear", "Included"], ["Warranty", "90 Days"]] },
  { slug: "resmed-airfit-f40", name: "ResMed AirFit F40 Full Face Mask", brand: "ResMed", category: "sleep-mask", price: 163, compareAt: 189, spec: "Full face · ultra-compact", badge: "Sale", rxRequired: false , image: "/products/resmed-airfit-f40.jpg" , specs: [["Type", "Full Face"], ["Cushion", "UltraSoft Silicone"], ["Sizes", "Small, Medium, Large"], ["Frame", "Standard, Small"], ["Headgear", "Included"], ["Warranty", "90 Days"]] },
  { slug: "resmed-airtouch-n20", name: "ResMed AirTouch N20 Nasal Mask", brand: "ResMed", category: "sleep-mask", price: 139, compareAt: 159, spec: "Nasal · memory foam cushion", badge: "Sale", rxRequired: false , image: "/products/resmed-airtouch-n20.png" , specs: [["Type", "Nasal"], ["Cushion", "UltraSoft Memory Foam"], ["Sizes", "Small, Medium, Large"], ["Frame", "Standard, Small"], ["Cushion Life", "30 Days"], ["Warranty", "90 Days"]] },
  { slug: "philips-dreamwear-nasal", name: "Philips DreamWear Nasal Mask", brand: "Philips Respironics", category: "sleep-mask", price: 129, compareAt: 149, spec: "Nasal · top-of-head tube", badge: "Sale", rxRequired: false , image: "/products/philips-dreamwear-nasal.png" , specs: [["Type", "Nasal"], ["Tube Connection", "Top-of-Head"], ["Cushion Options", "Nasal, Gel Pillows, Pillows"], ["Sizes", "S, M, MW, L"], ["Headgear", "Included"], ["Warranty", "90 Days"]] },
  { slug: "philips-dreamwear-full-face", name: "Philips DreamWear Full Face Mask", brand: "Philips Respironics", category: "sleep-mask", price: 149, compareAt: 179, spec: "Full face · top-of-head tube", badge: "Sale", rxRequired: false , image: "/products/philips-dreamwear-full-face.png" , specs: [["Type", "Full Face"], ["Tube Connection", "Top-of-Head"], ["Cushion", "Silicone Under-Nose"], ["Sizes", "S, M, MW, L"], ["Headgear", "Included"], ["Warranty", "90 Days"]] },
  { slug: "f-p-vitera", name: "Fisher & Paykel Vitera Full Face Mask", brand: "Fisher & Paykel", category: "sleep-mask", price: 149, compareAt: 179, spec: "Full face · RollFit XT cushion", badge: "Sale", rxRequired: false , image: "/products/f-p-vitera.jpg" , specs: [["Type", "Full Face"], ["Cushion", "RollFit XT Silicone"], ["Sizes", "Small, Medium, Large"], ["Headgear", "Included"], ["Frame Sizes", "Compact, Standard"], ["Warranty", "90 Days"]] },
  { slug: "f-p-brevida", name: "Fisher & Paykel Brevida Nasal Pillow", brand: "Fisher & Paykel", category: "sleep-mask", price: 79, compareAt: 99, spec: "Nasal pillow · AirPillow seal", badge: "Sale", rxRequired: false , image: "/products/f-p-brevida.jpg" , specs: [["Type", "Nasal Pillow"], ["Cushion", "Silicone AirPillow"], ["Sizes", "XS-S, M-L"], ["Headgear", "Included"], ["Weight", "Ultra-Light"], ["Warranty", "90 Days"]] },

  // ── CPAP cleaners ─────────────────────────────────────────────────
  { slug: "soclean-3-sanitizer", name: "SoClean 3 CPAP Sanitizer", brand: "SoClean", category: "sleep-cleaner", price: 299, compareAt: 349, spec: "Automated cleaning", badge: "Sale", rxRequired: false , image: "/products/soclean-3-sanitizer.jpg" , specs: [["Technology", "Activated Oxygen (O3)"], ["Cycle Time", "7 minutes"], ["Compatibility", "Most CPAP/BiPAP"], ["Dimensions", "10\" x 8\" x 5\""], ["Warranty", "2 Years"]] },
  { slug: "lumin-uv-sanitizer", name: "Lumin UV CPAP Sanitizer", brand: "3B Medical", category: "sleep-cleaner", price: 399, spec: "UV-C light sanitization", rxRequired: false , image: "/products/lumin-uv-sanitizer.png" , specs: [["Technology", "UV-C Light"], ["Cycle Time", "5 minutes"], ["FDA Status", "Registered"], ["Dimensions", "14\" x 9\" x 8\""]] },

  // ── Respiratory accessories ──────────────────────────────────────
  { slug: "drive-portable-suction", name: "Drive Medical Portable Suction Unit", brand: "Drive Medical", category: "respiratory-accessory", price: 249, spec: "Rechargeable battery", rxRequired: false , image: "/products/drive-portable-suction.jpg" , specs: [["Suction", "0-550 mmHg"], ["Flow Rate", "27 LPM"], ["Bottle Capacity", "800ml"], ["Battery", "45 min runtime"], ["Weight", "6 lbs"], ["Warranty", "2 Years"]] },
  { slug: "philips-innospire-elegance", name: "Philips InnoSpire Elegance Nebulizer", brand: "Philips Respironics", category: "respiratory-accessory", price: 59, compareAt: 79, spec: "SideStream nebulizer included", badge: "Sale", rxRequired: false , image: "/products/philips-innospire-elegance.jpg" , specs: [["Type", "Compressor Nebulizer"], ["Weight", "4.3 lbs"], ["Treatment Time", "~10 minutes"], ["Noise Level", "58 dBA"], ["Warranty", "5 Years"]] },
  { slug: "nonin-onyx-vantage-9590", name: "Nonin Onyx Vantage 9590 Pulse Oximeter", brand: "Nonin", category: "respiratory-accessory", price: 199, spec: "Medical grade accuracy", rxRequired: false , image: "/products/nonin-onyx-vantage-9590.jpg" , specs: [["SpO2 Range", "0-100%"], ["Pulse Rate", "18-321 BPM"], ["Accuracy", "±2% SpO2"], ["Battery", "2 AAA (6000 hours)"], ["Warranty", "4 Years"]] },
  { slug: "pari-vios-pro", name: "PARI Vios PRO Aerosol Delivery System", brand: "Pari", category: "respiratory-accessory", price: 135, spec: "1.6 bar compressor with dual LC Plus reusable nebulizers", rxRequired: false , image: "/products/pari-vios-pro.jpg" , specs: [["Type", "Compressor Nebulizer"], ["Weight", "4 lbs"], ["Power", "98W / 120V"], ["Compressor Output", "1.6 bar"], ["Includes", "2x PARI LC Plus reusable nebulizers, 7 ft tubing"], ["Warranty", "5 Years"]] },
  { slug: "omron-nec801-compair", name: "Omron NE-C801 CompAir Compressor Nebulizer", brand: "Omron", category: "respiratory-accessory", price: 32, spec: "Compact 9.5 oz compressor, 3 micron MMAD particle size", rxRequired: false , image: "/products/omron-nec801-compair.png" , specs: [["Type", "Compressor Nebulizer"], ["Weight", "9.5 oz"], ["Particle Size", "3 micron MMAD"], ["Nebulization Rate", "0.30 mL/min"], ["Noise Level", "<52 dBA"], ["Medication Capacity", "7 mL"], ["Warranty", "3 Years"]] },
  { slug: "omron-microair-neu100", name: "Omron MicroAir NE-U100 Portable Mesh Nebulizer", brand: "Omron", category: "respiratory-accessory", price: 175, spec: "Handheld vibrating-mesh, 4.2 oz, works in any position", rxRequired: false , image: "/products/omron-microair-neu100.jpg" , specs: [["Type", "Mesh Nebulizer (Handheld)"], ["Weight", "4.2 oz"], ["Particle Size", "~5 microns"], ["Battery", "2x AA (~4 hours)"], ["Noise Level", "<23 dBA"], ["Medication Capacity", "10 mL"]] },
  { slug: "philips-innospire-go", name: "Philips Respironics InnoSpire Go Portable Mesh Nebulizer", brand: "Philips Respironics", category: "respiratory-accessory", price: 210, spec: "Vibrating mesh technology, ~4-minute treatments, FAA-approved", rxRequired: false , image: "/products/philips-innospire-go.jpg" , specs: [["Type", "Mesh Nebulizer (Portable)"], ["Weight", "4 oz"], ["Treatment Time", "~4 minutes"], ["Battery", "Li-ion, up to 30 treatments/charge"], ["Warranty", "2 Years (handset)"]] },
  { slug: "pari-trek-s", name: "PARI Trek S Portable Aerosol System", brand: "Pari", category: "respiratory-accessory", price: 71, spec: "Battery/car-adapter portable compressor, 0.8 lbs", rxRequired: false , image: "/products/pari-trek-s.png" , specs: [["Type", "Compressor Nebulizer (Portable)"], ["Weight", "0.8 lbs (1.2 lbs w/ battery)"], ["Treatment Time", "~5-6 minutes"], ["Operating Pressure", "14.5 PSI nominal"], ["Battery", "Li-ion, ~50 min charge life"], ["Warranty", "3 Years"]] },
  { slug: "drive-neb-u-tyke-pediatric", name: "Drive Medical Beagle Pediatric Compressor Nebulizer", brand: "Drive Medical", category: "respiratory-accessory", price: 58, spec: "Kid-friendly dog-shaped design, quiet piston pump", rxRequired: false , image: "/products/drive-neb-u-tyke-pediatric.png" , specs: [["Type", "Compressor Nebulizer (Pediatric)"], ["Weight", "3.1 lbs"], ["Includes", "Disposable neb kit, pediatric aerosol mask, carry bag"], ["Warranty", "5 Years"]] },
  { slug: "nebulizer-kit-adult", name: "Universal Adult Nebulizer Replacement Kit", brand: "Sunset Healthcare", category: "respiratory-accessory", price: 9, spec: "Adult aerosol mask, medication cup, 7 ft tubing", rxRequired: false , image: "/products/nebulizer-kit-adult.jpg" , specs: [["Type", "Disposable Compressor Nebulizer Kit"], ["Includes", "Adult aerosol mask, medication cup, 7 ft tubing"], ["Use", "Single-patient, disposable"]] },
  { slug: "nebulizer-kit-pediatric", name: "Universal Pediatric Nebulizer Replacement Kit", brand: "Sunset Healthcare", category: "respiratory-accessory", price: 10, spec: "Pediatric aerosol mask, medication cup, 7 ft tubing", rxRequired: false , image: "/products/nebulizer-kit-pediatric.jpg" , specs: [["Type", "Disposable Compressor Nebulizer Kit"], ["Includes", "Pediatric aerosol mask, 6cc medication cup, 7 ft tubing"], ["Use", "Single-patient, disposable"]] },
  { slug: "nonin-go2-achieve-9570", name: "Nonin GO2 Achieve 9570 Fingertip Pulse Oximeter", brand: "Nonin", category: "respiratory-accessory", price: 99, spec: "Rugged, drop-tested — no prescription required", rxRequired: false , image: "/products/nonin-go2-achieve-9570.jpg" , specs: [["SpO2 Range", "0-100%"], ["Pulse Rate", "18-321 BPM"], ["Accuracy", "±2 digits SpO2 (70-100%)"], ["Battery", "1 AAA (2,400 spot checks)"], ["Water Resistance", "IP33"], ["Warranty", "2 Years"]] },
  { slug: "masimo-mightysat", name: "Masimo MightySat Fingertip Pulse Oximeter", brand: "Masimo", category: "respiratory-accessory", price: 279, compareAt: 298, badge: "Sale", spec: "Bluetooth-connected with Masimo Personal Health app", rxRequired: false , image: "/products/masimo-mightysat.jpg" , specs: [["SpO2 Range", "0-100%"], ["Pulse Rate Range", "25-240 BPM"], ["Perfusion Index", "0.02-20%"], ["Accuracy", "±2% SpO2 (no motion, 70-100%)"], ["Battery", "2 AAA (~1,800 spot checks)"], ["Connectivity", "Bluetooth LE"], ["Warranty", "2 Years"]] },
  { slug: "masimo-mightysat-rx", name: "Masimo MightySat Rx Fingertip Pulse Oximeter", brand: "Masimo", category: "respiratory-accessory", price: 549, spec: "Clinical-grade — adds respiration rate & PVi, Rx required", rxRequired: true , image: "/products/masimo-mightysat-rx.jpg" , specs: [["SpO2 Range", "0-100%"], ["Pulse Rate Range", "25-240 BPM"], ["Respiration Rate", "4-70 breaths/min (from pleth waveform)"], ["Additional Parameters", "Perfusion Index, Pleth Variability Index"], ["Accuracy", "±2% SpO2 (no motion), ±3% (motion)"], ["Battery", "2 AAA (~1,800 spot checks)"], ["Warranty", "4 Years"]] },
  { slug: "wellue-o2ring", name: "Wellue O2Ring Continuous Wearable Pulse Oximeter", brand: "Wellue", category: "respiratory-accessory", price: 153, compareAt: 179, badge: "Sale", spec: "Ring-style wearable with vibration desaturation alarm", rxRequired: false , image: "/products/wellue-o2ring.jpg" , specs: [["SpO2 Range", "70-100%"], ["Pulse Rate Range", "30-250 BPM"], ["Accuracy", "±2% (80-99%), ±3% (70-79%)"], ["Battery", "Rechargeable Li-polymer, 12-16 hrs"], ["Alerts", "On-ring LED + 5-level vibration alarm"], ["Connectivity", "Bluetooth 4.0 (ViHealth app)"]] },
  { slug: "pulse-ox-protective-case", name: "Pulse Oximeter Protective Sleeve & Carrying Case", brand: "Hopkins Medical", category: "respiratory-accessory", price: 10, spec: "Fits most standard fingertip pulse oximeter models", rxRequired: false , image: "/products/pulse-ox-protective-case.jpg" , specs: [["Material", "Durable protective fabric sleeve"], ["Compatibility", "Fits most standard fingertip pulse oximeter brands"]] },

  // ── Ventilators — institutional/ICU equipment, not a self-pay consumer
  // purchase. Priced and specced for the biomed/procurement buyer, not the
  // oxygen/CPAP patient the rest of the catalog is built around.
  { slug: "hamilton-c6", name: "Hamilton-C6", brand: "Hamilton Medical", category: "ventilator", price: 52000, spec: "Adaptive Support Ventilation (ASV)", rxRequired: false , image: "/products/hamilton-c6.png" , specs: [["Max Inspiratory Flow", "260 L/min"], ["Noise Level", "37 dB average"], ["Display", "Touchscreen"], ["Drive", "High-Performance Turbine"], ["Turbine Warranty", "Lifetime"], ["Patient Populations", "Adult, Pediatric, Neonatal"], ["FDA Status", "Cleared"]] },
  { slug: "hamilton-c3", name: "Hamilton-C3", brand: "Hamilton Medical", category: "ventilator", price: 42500, spec: "Compact high-end design", rxRequired: false , image: "/products/hamilton-c3.png" , specs: [["Display", "12.1\" Touchscreen"], ["Monitoring Parameters", "52"], ["Trends", "72 Hours"], ["Weight", "26.5 lbs"], ["Drive System", "High-Performance Turbine"], ["Battery", "Hot-Swappable (x2)"], ["Patient Populations", "Adult, Pediatric, Neonatal (optional)"], ["Warranty", "2 Years"]] },
  { slug: "hamilton-c1", name: "Hamilton-C1", brand: "Hamilton Medical", category: "ventilator", price: 34500, spec: "All-rounder for every department", rxRequired: false , image: "/products/hamilton-c1.png" , specs: [["Weight", "22 lbs"], ["Battery", "4 Hours"], ["Drive", "High-Performance Turbine"], ["Modes", "CMV+, PCV+, PSIMV+, SPONT, DuoPAP, ASV, NIV, HFNC"], ["Patient Populations", "Adult, Pediatric, Neonatal"], ["FDA Status", "Cleared"], ["Warranty", "2 Years"]] },
  { slug: "hamilton-t1", name: "Hamilton-T1", brand: "Hamilton Medical", category: "ventilator", price: 28500, spec: "Rugged transport design", rxRequired: false , image: "/products/hamilton-t1.png" , specs: [["Drive", "High-Performance Turbine"], ["Design", "Rugged Transport"], ["Patient Populations", "Adult, Pediatric, Neonatal"], ["FDA Status", "Cleared"]] },
  { slug: "hamilton-mr1", name: "Hamilton-MR1", brand: "Hamilton Medical", category: "ventilator", price: 58000, spec: "MR-conditional (1.5T & 3.0T)", rxRequired: false , image: "/products/hamilton-mr1.png" , specs: [["MRI Compatibility", "MR-Conditional up to 50 mT"], ["Scanner Support", "1.5T and 3.0T"], ["Battery", "Up to 540 minutes"], ["Weight", "24 lbs"], ["Safety", "TeslaSpy Navigator + Auto-Lock Brakes"], ["Patient Populations", "Adult, Pediatric, Neonatal"], ["Warranty", "2 Years"]] },
  { slug: "hamilton-hf90", name: "Hamilton-HF90", brand: "Hamilton Medical", category: "ventilator", price: 18500, spec: "Standalone high-flow oxygen therapy device", rxRequired: false , image: "/products/hamilton-hf90.png" , specs: [["Type", "Standalone High-Flow Therapy"], ["Therapy", "Heated Humidified HFNC"], ["Weight", "12 lbs"], ["Patient Populations", "Adult, Pediatric"], ["FDA Status", "Cleared"], ["Warranty", "2 Years"]] },
  { slug: "draeger-evita-v800", name: "Dräger Evita V800", brand: "Dräger", category: "ventilator", price: 55000, spec: "Seamless O2/NIV/invasive transition", rxRequired: false , image: "/products/draeger-evita-v800.jpg" , specs: [["Display", "18.5\" Touchscreen"], ["Ventilation Modes", "VC, PC, PS, SIMV, CPAP, NIV, APRV, MMV"], ["Patient Populations", "Adult, Pediatric, Neonatal"], ["Connectivity", "SDC-Standard, HL7"], ["FDA Status", "Cleared"], ["Warranty", "2 Years"]] },
  { slug: "draeger-evita-v600", name: "Dräger Evita V600", brand: "Dräger", category: "ventilator", price: 42000, spec: "Early mobilization & transport", rxRequired: false , image: "/products/draeger-evita-v600.png" , specs: [["Drive", "Turbine-Driven"], ["Weaning", "SmartCare/PS Automated"], ["Patient Populations", "Adult, Pediatric, Neonatal"], ["Transport", "Battery-powered mobilization"], ["FDA Status", "Cleared"], ["Warranty", "2 Years"]] },
  { slug: "draeger-savina-300", name: "Dräger Savina 300", brand: "Dräger", category: "ventilator", price: 28000, spec: "Gas & power independent", rxRequired: false , image: "/products/draeger-savina-300.jpg" , specs: [["Drive", "Turbine-Driven"], ["Independence", "No external gas/power required"], ["Patient Populations", "Adult, Pediatric"], ["FDA Status", "Cleared"], ["Warranty", "2 Years"]] },
  { slug: "draeger-oxylog-3000-plus", name: "Dräger Oxylog 3000 Plus", brand: "Dräger", category: "ventilator", price: 18500, spec: "ICU-level transport ventilation", rxRequired: false , image: "/products/draeger-oxylog-3000-plus.jpg" , specs: [["Type", "Transport Ventilator"], ["Capnography", "Integrated Mainstream"], ["Weight", "12.8 lbs"], ["Battery", "Up to 6 hours"], ["FDA Status", "Cleared"], ["Warranty", "2 Years"]] },
  { slug: "draeger-babylog-vn800", name: "Dräger Babylog VN800", brand: "Dräger", category: "ventilator", price: 48000, spec: "Advanced neonatal ventilation", rxRequired: false , image: "/products/draeger-babylog-vn800.png" , specs: [["Display", "18.3\" Touchscreen"], ["Patient Population", "Neonatal"], ["Ventilation Modes", "PC, VC, SIMV, CPAP, HFO, Volume Guarantee"], ["FDA Status", "Cleared"], ["Warranty", "2 Years"]] },
  { slug: "draeger-oxylog-ve300", name: "Dräger Oxylog VE300", brand: "Dräger", category: "ventilator", price: 12500, spec: "Portable emergency design", rxRequired: false , image: "/products/draeger-oxylog-ve300.jpg" , specs: [["Type", "Emergency Ventilator"], ["Weight", "8.8 lbs"], ["Protection Rating", "IP54"], ["Battery Life", "Up to 10 hours"], ["FDA Status", "Cleared"], ["Warranty", "2 Years"]] },
  { slug: "getinge-servo-u", name: "Getinge Servo-u", brand: "Getinge", category: "ventilator", price: 48000, spec: "Personalized ventilation", rxRequired: false , image: "/products/getinge-servo-u.jpg" , specs: [["Display", "15\" Touchscreen"], ["Patient Populations", "Neonatal (300g) to Adult (300kg)"], ["Unique Technology", "NAVA, Edi Catheter"], ["Modes", "VC, PC, PS, SIMV, PRVC, Bi-Vent, NAVA, NIV"], ["FDA Status", "Cleared"]] },
  { slug: "getinge-servo-n", name: "Getinge Servo-n", brand: "Getinge", category: "ventilator", price: 52000, spec: "NAVA for neonates", rxRequired: false , image: "/products/getinge-servo-n.jpg" , specs: [["Patient Population", "Neonatal & Pediatric"], ["Technology", "NAVA, Edi Catheter"], ["Ventilation Modes", "PC, PS, CPAP, NAVA, NIV-NAVA, HFO"], ["FDA Status", "Cleared"], ["Warranty", "2 Years"]] },
  { slug: "getinge-servo-air", name: "Getinge Servo-air", brand: "Getinge", category: "ventilator", price: 32000, spec: "Turbine-driven, no compressed air", rxRequired: false , image: "/products/getinge-servo-air.jpg" , specs: [["Drive", "Turbine (No External Air)"], ["Patient Populations", "Adult, Pediatric"], ["Modes", "VC, PC, PS, SIMV, CPAP, NIV"], ["FDA Status", "Cleared"], ["Warranty", "2 Years"]] },
  { slug: "mindray-sv800", name: "Mindray SV800", brand: "Mindray", category: "ventilator", price: 38000, spec: "1080p HD 15.6\" widescreen", rxRequired: false , image: "/products/mindray-sv800.jpg" , specs: [["Display", "15.6\" 1080P HD Touchscreen"], ["Dimensions", "906x401x298mm (without trolley)"], ["Weight", "45 kg (with trolley)"], ["Patient Populations", "Adult, Pediatric, Neonatal"], ["Modes", "VC, PC, SIMV, CPAP, PS, PRVC, APRV, DuoPAP, NIV"], ["FDA Status", "Cleared"], ["Warranty", "3 Years"]] },
  { slug: "mindray-sv600", name: "Mindray SV600", brand: "Mindray", category: "ventilator", price: 28000, spec: "15.6\" HD widescreen display", rxRequired: false , image: "/products/mindray-sv600.jpg" , specs: [["Display", "15.6\" 1080P HD Touchscreen"], ["Weight", "45 kg (with trolley)"], ["Patient Populations", "Adult, Pediatric"], ["Modes", "VC, PC, SIMV, CPAP, PS, NIV"], ["FDA Status", "Cleared"], ["Warranty", "3 Years"]] },
  { slug: "mindray-sv300", name: "Mindray SV300", brand: "Mindray", category: "ventilator", price: 18000, spec: "Compact & lightweight", rxRequired: false , image: "/products/mindray-sv300.jpg" , specs: [["Display", "12.1\" Touchscreen"], ["Drive", "Turbine (No External Air)"], ["Battery", "Up to 4 hours"], ["Weight", "33 lbs"], ["Patient Populations", "Adult, Pediatric"], ["FDA Status", "Cleared"], ["Warranty", "3 Years"]] },
  { slug: "zoll-z-vent-731", name: "Zoll Z Vent 731", brand: "Zoll", category: "ventilator", price: 22000, spec: "Military & civilian transport", rxRequired: false , image: "/products/zoll-z-vent-731.jpg" , specs: [["Type", "Portable Critical Care Ventilator"], ["Weight", "13 lbs"], ["Modes", "AC, SIMV, CPAP, Bi-Level (Volume & Pressure)"], ["Military Standard", "MIL-STD-810"], ["FDA Status", "Cleared"], ["Warranty", "2 Years"]] },
  { slug: "zoll-emv-plus", name: "Zoll EMV+", brand: "Zoll", category: "ventilator", price: 19500, spec: "Military-grade construction", rxRequired: false , image: "/products/zoll-emv-plus.jpg" , specs: [["Type", "Military Portable Ventilator"], ["Weight", "12.5 lbs"], ["Battery", "10+ hours"], ["Military Certification", "MIL-STD-810G"], ["Altitude", "Up to 15,000 ft"], ["FDA Status", "Cleared"], ["Warranty", "2 Years"]] },
  { slug: "zoll-aev", name: "Zoll AEV", brand: "Zoll", category: "ventilator", price: 15000, spec: "EMS & fire service ready", rxRequired: false , image: "/products/zoll-aev.jpg" , specs: [["Type", "Advanced Emergency Ventilator"], ["Weight", "11.5 lbs"], ["Modes", "AC, SIMV, CPAP, Bi-Level"], ["FDA Status", "Cleared"], ["Warranty", "2 Years"]] },
  { slug: "hamilton-g5", name: "Hamilton-G5", brand: "Hamilton Medical", category: "ventilator", price: 54000, spec: "Modular high-end ventilation, neonate to adult", rxRequired: false , image: "/products/hamilton-g5.jpg" , specs: [["Display", "Ventilation Cockpit Touchscreen"], ["Drive", "High-Performance Turbine"], ["Cuff Management", "IntelliCuff Automatic Pressure Control"], ["Modes", "ASV, (S)CMV+, SIMV+, PCV+, NIV, HFNC"], ["Patient Populations", "Neonatal, Pediatric, Adult"], ["FDA Status", "Cleared"], ["Warranty", "2 Years"]] },
  { slug: "hamilton-s1", name: "Hamilton-S1", brand: "Hamilton Medical", category: "ventilator", price: 40000, spec: "Compact critical-care ventilator for ICU and OR", rxRequired: false , image: "/products/hamilton-s1.jpg" , specs: [["Display", "Ventilation Cockpit Touchscreen"], ["Drive", "High-Performance Turbine"], ["Modes", "ASV, INTELLiVENT-ASV, (S)CMV+, NIV"], ["Mobility", "Mobile cart or rack-mount"], ["Patient Populations", "Neonatal, Pediatric, Adult"], ["FDA Status", "Cleared"], ["Warranty", "2 Years"]] },
  { slug: "draeger-evita-infinity-v500", name: "Dräger Evita Infinity V500", brand: "Dräger", category: "ventilator", price: 50000, spec: "Full ICU ventilation on the Infinity Acute Care System", rxRequired: false , image: "/products/draeger-evita-infinity-v500.jpg" , specs: [["Weight", "130 lbs (59 kg)"], ["Connectivity", "3x RS232, 6x USB, LAN, 2x Ethernet"], ["Patient Populations", "Infant, Pediatric, Adult"], ["FDA Status", "Cleared"], ["Warranty", "2 Years"]] },
  { slug: "draeger-babylog-vn500", name: "Dräger Babylog VN500", brand: "Dräger", category: "ventilator", price: 39000, spec: "Neonatal ventilation with automatic leak compensation", rxRequired: false , image: "/products/draeger-babylog-vn500.jpg" , specs: [["Dimensions", "16.5\" x 27\" x 16.1\" (W x H x D)"], ["Patient Population", "Neonatal"], ["Key Feature", "Volume Guarantee + Automatic Leak Compensation"], ["FDA Status", "Cleared"], ["Warranty", "2 Years"]] },
  { slug: "mindray-sv70", name: "Mindray SV70", brand: "Mindray", category: "ventilator", price: 16500, spec: "Professional non-invasive ventilation", rxRequired: false , image: "/products/mindray-sv70.jpg" , specs: [["Type", "Non-Invasive Ventilator"], ["Technology", "EasySync Patient-Ventilator Synchronization"], ["Patient Populations", "Adult, Pediatric"], ["FDA Status", "Cleared"], ["Warranty", "3 Years"]] },
  // Puritan Bennett (Medtronic) — the 840 and 980 were discontinued by
  // Medtronic in March 2024; sold here as final/refurbished-channel
  // inventory, not new manufacturer stock. The 560 remains in current
  // production. Real disclosure, matching the "Discontinued" badge pattern
  // already used elsewhere in this catalog rather than presenting these as
  // active new units.
  { slug: "puritan-bennett-840", name: "Puritan Bennett 840", brand: "Medtronic", category: "ventilator", price: 24000, spec: "Manufacturer-discontinued (March 2024) — final inventory", badge: "Discontinued", rxRequired: false , image: "/products/puritan-bennett-840.jpg" , specs: [["Display", "DualView Touchscreens"], ["Electronics", "Dual-Microprocessor"], ["Notable Mode", "PAV+ (Proportional Assist Ventilation)"], ["Patient Populations", "Infant to Adult"], ["FDA Status", "Cleared"], ["Manufacturer Support", "Parts/service through 2031"]] },
  { slug: "puritan-bennett-980", name: "Puritan Bennett 980", brand: "Medtronic", category: "ventilator", price: 34000, spec: "Manufacturer-discontinued (March 2024) — final inventory", badge: "Discontinued", rxRequired: false , image: "/products/puritan-bennett-980.jpg" , specs: [["Oxygen Concentration", "21-100%, adjustable"], ["Modes", "Assist/Control, SIMV, Spontaneous"], ["Patient Populations", "Neonate to Adult"], ["FDA Status", "Cleared"], ["Manufacturer Support", "Parts/service through 2034"]] },
  { slug: "puritan-bennett-560", name: "Puritan Bennett 560", brand: "Medtronic", category: "ventilator", price: 16000, spec: "Compact portable ventilator for clinical and home use", rxRequired: false , image: "/products/puritan-bennett-560.jpg" , specs: [["Type", "Compact Portable Ventilator"], ["Setting", "Hospital, Transport, and Home"], ["Patient Populations", "Adult, Pediatric"], ["FDA Status", "Cleared"], ["Warranty", "2 Years"]] },
  { slug: "philips-trilogy-evo", name: "Philips Respironics Trilogy Evo", brand: "Philips Respironics", category: "ventilator", price: 26000, spec: "Invasive and non-invasive ventilation, pediatric through adult", rxRequired: false , image: "/products/philips-trilogy-evo.jpg" , specs: [["Display", "8\" Touchscreen"], ["Tidal Volume", "35-2000 mL"], ["Modes", "Volume, Pressure, AVAPS-AE"], ["Battery Life", "Up to 15 hours"], ["Patient Populations", "Pediatric (2.5kg+) through Adult"], ["FDA Status", "Cleared"], ["Warranty", "2 Years"]] },

  // ── Oxygen concentrator rentals ──────────────────────────────────
  { slug: "inogen-rove-6-weekly-rental", name: "Inogen Rove 6 - Weekly Rental", brand: "Inogen", category: "oxygen-rental", price: null, badge: "Rental", faaApproved: true, rxRequired: true , image: "/products/inogen-rove-6.png" , specs: [["Rental Term", "Weekly"], ["Weight", "4.8 lbs (standard battery)"], ["Flow Settings", "1-6 Pulse Dose"], ["Battery Life", "6-13 hours"], ["Noise Level", "37 dBA"], ["Includes", "Concentrator, battery, AC/DC chargers, carrying case, cannula"]] },
  { slug: "inogen-rove-6-monthly-rental", name: "Inogen Rove 6 - Monthly Rental", brand: "Inogen", category: "oxygen-rental", price: null, badge: "Rental", faaApproved: true, rxRequired: true , image: "/products/inogen-rove-6.png" , specs: [["Rental Term", "Monthly"], ["Weight", "4.8 lbs (standard battery)"], ["Flow Settings", "1-6 Pulse Dose"], ["Battery Life", "6-13 hours"], ["Noise Level", "37 dBA"], ["Includes", "Concentrator, battery, AC/DC chargers, carrying case, cannula"]] },
  { slug: "inogen-rove-4-weekly-rental", name: "Inogen Rove 4 - Weekly Rental", brand: "Inogen", category: "oxygen-rental", price: null, badge: "Rental", faaApproved: true, rxRequired: true , image: "/products/inogen-rove-4.png" , specs: [["Rental Term", "Weekly"], ["Weight", "2.9 lbs (standard battery)"], ["Flow Settings", "1-4 Pulse Dose"], ["Battery Life", "2.5-8 hours"], ["Noise Level", "40 dBA"], ["Includes", "Concentrator, battery, AC/DC chargers, carrying case, cannula"]] },
  { slug: "inogen-rove-4-monthly-rental", name: "Inogen Rove 4 - Monthly Rental", brand: "Inogen", category: "oxygen-rental", price: null, badge: "Rental", faaApproved: true, rxRequired: true , image: "/products/inogen-rove-4.png" , specs: [["Rental Term", "Monthly"], ["Weight", "2.9 lbs (standard battery)"], ["Flow Settings", "1-4 Pulse Dose"], ["Battery Life", "2.5-8 hours"], ["Noise Level", "40 dBA"], ["Includes", "Concentrator, battery, AC/DC chargers, carrying case, cannula"]] },
  { slug: "caire-freestyle-comfort-weekly-rental", name: "Caire FreeStyle Comfort - Weekly Rental", brand: "Caire", category: "oxygen-rental", price: 520, badge: "Rental", faaApproved: true, rxRequired: true , image: "/products/caire-freestyle-comfort.png" , specs: [["Rental Term", "Weekly"], ["Weight", "5 lbs (with battery)"], ["Flow Settings", "1-5 Pulse Dose"], ["Battery Life", "8-16 hours"], ["Noise Level", "43 dBA"], ["Includes", "Concentrator, battery, AC/DC chargers, carrying case, cannula"]] },
  { slug: "caire-freestyle-comfort-monthly-rental", name: "Caire FreeStyle Comfort - Monthly Rental", brand: "Caire", category: "oxygen-rental", price: 1100, badge: "Rental", faaApproved: true, rxRequired: true , image: "/products/caire-freestyle-comfort.png" , specs: [["Rental Term", "Monthly"], ["Weight", "5 lbs (with battery)"], ["Flow Settings", "1-5 Pulse Dose"], ["Battery Life", "8-16 hours"], ["Noise Level", "43 dBA"], ["Includes", "Concentrator, battery, AC/DC chargers, carrying case, cannula"]] },
  { slug: "caire-eclipse-5-weekly-rental", name: "Caire Eclipse 5 - Weekly Rental", brand: "Caire", category: "oxygen-rental", price: 600, badge: "Rental", faaApproved: true, rxRequired: true , image: "/products/caire-eclipse-5.png" , specs: [["Rental Term", "Weekly"], ["Weight", "18.4 lbs (with battery)"], ["Continuous Flow", "0.5-3 LPM"], ["Pulse Dose", "Settings 1-9"], ["Noise Level", "48 dBA"], ["Includes", "Concentrator, battery, AC/DC chargers, carrying case, cannula"]] },
  { slug: "caire-eclipse-5-monthly-rental", name: "Caire Eclipse 5 - Monthly Rental", brand: "Caire", category: "oxygen-rental", price: 1340, badge: "Rental", faaApproved: true, rxRequired: true , image: "/products/caire-eclipse-5.png" , specs: [["Rental Term", "Monthly"], ["Weight", "18.4 lbs (with battery)"], ["Continuous Flow", "0.5-3 LPM"], ["Pulse Dose", "Settings 1-9"], ["Noise Level", "48 dBA"], ["Includes", "Concentrator, battery, AC/DC chargers, carrying case, cannula"]] },
  { slug: "philips-home-concentrator-5l-weekly-rental", name: "Philips Home Concentrator 5L - Weekly Rental", brand: "Philips Respironics", category: "oxygen-rental", price: 459, badge: "Rental", rxRequired: true , image: "/products/philips-everflo.jpg" , specs: [["Rental Term", "Weekly"], ["Flow Rate", "1-5 LPM"], ["Weight", "31 lbs (14 kg)"], ["Noise Level", "40 dBA"], ["Oxygen Purity", "93% ± 3%"], ["Includes", "Concentrator, tubing, cannula, power cord"]] },
  { slug: "philips-home-concentrator-5l-monthly-rental", name: "Philips Home Concentrator 5L - Monthly Rental", brand: "Philips Respironics", category: "oxygen-rental", price: 500, badge: "Rental", rxRequired: true , image: "/products/philips-everflo.jpg" , specs: [["Rental Term", "Monthly"], ["Flow Rate", "1-5 LPM"], ["Weight", "31 lbs (14 kg)"], ["Noise Level", "40 dBA"], ["Oxygen Purity", "93% ± 3%"], ["Includes", "Concentrator, tubing, cannula, power cord"]] },
  { slug: "caire-home-concentrator-10l-weekly-rental", name: "Caire Home Concentrator 10L - Weekly Rental", brand: "Caire", category: "oxygen-rental", price: 599, badge: "Rental", rxRequired: true , image: "/products/caire-newlife-intensity-10.jpg" , specs: [["Rental Term", "Weekly"], ["Flow Rate", "2-10 LPM"], ["Weight", "58 lbs"], ["Noise Level", "50 dBA"], ["Oxygen Purity", "87-96%"], ["Includes", "Concentrator, tubing, cannula, power cord"]] },
  { slug: "caire-home-concentrator-10l-monthly-rental", name: "Caire Home Concentrator 10L - Monthly Rental", brand: "Caire", category: "oxygen-rental", price: 740, badge: "Rental", rxRequired: true , image: "/products/caire-newlife-intensity-10.jpg" , specs: [["Rental Term", "Monthly"], ["Flow Rate", "2-10 LPM"], ["Weight", "58 lbs"], ["Noise Level", "50 dBA"], ["Oxygen Purity", "87-96%"], ["Includes", "Concentrator, tubing, cannula, power cord"]] },

  // ── CPAP & BiPAP rentals ─────────────────────────────────────────
  { slug: "resmed-airsense-11-weekly-rental", name: "ResMed AirSense 11 AutoSet - Weekly Rental", brand: "ResMed", category: "cpap-rental", price: 448, badge: "Rental", rxRequired: true , image: "/products/resmed-airsense-11-autoset.jpg" , specs: [["Rental Term", "Weekly"], ["Pressure Range", "4-20 cm H2O"], ["Weight", "2.75 lbs"], ["Humidifier", "Built-in HumidAir"], ["Connectivity", "Cellular, Wi-Fi, Bluetooth"], ["Includes", "Machine, tubing, power supply — mask sold separately"]] },
  { slug: "resmed-airsense-11-monthly-rental", name: "ResMed AirSense 11 AutoSet - Monthly Rental", brand: "ResMed", category: "cpap-rental", price: 848, badge: "Rental", rxRequired: true , image: "/products/resmed-airsense-11-autoset.jpg" , specs: [["Rental Term", "Monthly"], ["Pressure Range", "4-20 cm H2O"], ["Weight", "2.75 lbs"], ["Humidifier", "Built-in HumidAir"], ["Connectivity", "Cellular, Wi-Fi, Bluetooth"], ["Includes", "Machine, tubing, power supply — mask sold separately"]] },
  { slug: "f-p-sleepstyle-weekly-rental", name: "Fisher & Paykel SleepStyle Auto CPAP - Weekly Rental", brand: "Fisher & Paykel", category: "cpap-rental", price: 428, badge: "Rental", rxRequired: true , image: "/products/f-p-sleepstyle.png" , specs: [["Rental Term", "Weekly"], ["Pressure Range", "4-20 cm H2O"], ["Weight", "3.3 lbs"], ["Humidifier", "Integrated ThermoSmart"], ["Noise Level", "26 dBA"], ["Includes", "Machine, tubing, power supply — mask sold separately"]] },
  { slug: "f-p-sleepstyle-monthly-rental", name: "Fisher & Paykel SleepStyle Auto CPAP - Monthly Rental", brand: "Fisher & Paykel", category: "cpap-rental", price: 748, badge: "Rental", rxRequired: true , image: "/products/f-p-sleepstyle.png" , specs: [["Rental Term", "Monthly"], ["Pressure Range", "4-20 cm H2O"], ["Weight", "3.3 lbs"], ["Humidifier", "Integrated ThermoSmart"], ["Noise Level", "26 dBA"], ["Includes", "Machine, tubing, power supply — mask sold separately"]] },
  { slug: "resmed-airmini-weekly-rental", name: "ResMed AirMini Travel CPAP - Weekly Rental", brand: "ResMed", category: "cpap-rental", price: 400, badge: "Rental", faaApproved: true, rxRequired: true , image: "/products/resmed-airmini.jpg" , specs: [["Rental Term", "Weekly"], ["Weight", "0.66 lbs"], ["Dimensions", "5.4\" x 3.3\" x 2.1\""], ["Pressure Range", "4-20 cm H2O"], ["Includes", "Machine, tubing, power supply — mask sold separately"]] },
  { slug: "resmed-airmini-monthly-rental", name: "ResMed AirMini Travel CPAP - Monthly Rental", brand: "ResMed", category: "cpap-rental", price: 740, badge: "Rental", faaApproved: true, rxRequired: true , image: "/products/resmed-airmini.jpg" , specs: [["Rental Term", "Monthly"], ["Weight", "0.66 lbs"], ["Dimensions", "5.4\" x 3.3\" x 2.1\""], ["Pressure Range", "4-20 cm H2O"], ["Includes", "Machine, tubing, power supply — mask sold separately"]] },
  { slug: "transcend-365-weekly-rental", name: "Transcend 365 Auto miniCPAP - Weekly Rental", brand: "Precision Medical", category: "cpap-rental", price: 348, badge: "Rental", faaApproved: true, rxRequired: true , image: "/products/transcend-365-auto.jpg" , specs: [["Rental Term", "Weekly"], ["Weight", "0.8 lbs"], ["Battery", "Integrated Li-Ion"], ["Pressure Range", "4-20 cm H2O"], ["Noise Level", "28 dBA"], ["Includes", "Machine, tubing, power supply — mask sold separately"]] },
  { slug: "transcend-365-monthly-rental", name: "Transcend 365 Auto miniCPAP - Monthly Rental", brand: "Precision Medical", category: "cpap-rental", price: 600, badge: "Rental", faaApproved: true, rxRequired: true , image: "/products/transcend-365-auto.jpg" , specs: [["Rental Term", "Monthly"], ["Weight", "0.8 lbs"], ["Battery", "Integrated Li-Ion"], ["Pressure Range", "4-20 cm H2O"], ["Noise Level", "28 dBA"], ["Includes", "Machine, tubing, power supply — mask sold separately"]] },
  { slug: "resmed-aircurve-10-vauto-weekly-rental", name: "ResMed AirCurve 10 VAuto BiPAP - Weekly Rental", brand: "ResMed", category: "cpap-rental", price: 548, badge: "Rental", rxRequired: true , image: "/products/resmed-aircurve-10-vauto.jpg" , specs: [["Rental Term", "Weekly"], ["IPAP", "4-25 cm H2O"], ["EPAP", "4-20 cm H2O"], ["Weight", "2.75 lbs"], ["Humidifier", "Built-in HumidAir"], ["Includes", "Machine, tubing, power supply — mask sold separately"]] },
  { slug: "resmed-aircurve-10-vauto-monthly-rental", name: "ResMed AirCurve 10 VAuto BiPAP - Monthly Rental", brand: "ResMed", category: "cpap-rental", price: 1048, badge: "Rental", rxRequired: true , image: "/products/resmed-aircurve-10-vauto.jpg" , specs: [["Rental Term", "Monthly"], ["IPAP", "4-25 cm H2O"], ["EPAP", "4-20 cm H2O"], ["Weight", "2.75 lbs"], ["Humidifier", "Built-in HumidAir"], ["Includes", "Machine, tubing, power supply — mask sold separately"]] },
  { slug: "resmed-aircurve-10-st-weekly-rental", name: "ResMed AirCurve 10 ST BiPAP - Weekly Rental", brand: "ResMed", category: "cpap-rental", price: 648, badge: "Rental", rxRequired: true , image: "/products/resmed-aircurve-10-st.jpg" , specs: [["Rental Term", "Weekly"], ["IPAP", "4-25 cm H2O"], ["EPAP", "4-25 cm H2O"], ["Backup Rate", "0-30 BPM"], ["Weight", "2.75 lbs (1.25 kg)"], ["Includes", "Machine, tubing, power supply — mask sold separately"]] },
  { slug: "resmed-aircurve-10-st-monthly-rental", name: "ResMed AirCurve 10 ST BiPAP - Monthly Rental", brand: "ResMed", category: "cpap-rental", price: 1248, badge: "Rental", rxRequired: true , image: "/products/resmed-aircurve-10-st.jpg" , specs: [["Rental Term", "Monthly"], ["IPAP", "4-25 cm H2O"], ["EPAP", "4-25 cm H2O"], ["Backup Rate", "0-30 BPM"], ["Weight", "2.75 lbs (1.25 kg)"], ["Includes", "Machine, tubing, power supply — mask sold separately"]] },
  { slug: "philips-dreamstation-bipap-weekly-rental", name: "Philips DreamStation BiPAP - Weekly Rental", brand: "Philips Respironics", category: "cpap-rental", price: 528, badge: "Rental", rxRequired: true , image: "/products/philips-dreamstation-bipap.png" , specs: [["Rental Term", "Weekly"], ["IPAP", "4-25 cm H2O"], ["EPAP", "4-20 cm H2O"], ["Weight", "2.95 lbs"], ["Humidifier", "Integrated"], ["Includes", "Machine, tubing, power supply — mask sold separately"]] },
  { slug: "philips-dreamstation-bipap-monthly-rental", name: "Philips DreamStation BiPAP - Monthly Rental", brand: "Philips Respironics", category: "cpap-rental", price: 1000, badge: "Rental", rxRequired: true , image: "/products/philips-dreamstation-bipap.png" , specs: [["Rental Term", "Monthly"], ["IPAP", "4-25 cm H2O"], ["EPAP", "4-20 cm H2O"], ["Weight", "2.95 lbs"], ["Humidifier", "Integrated"], ["Includes", "Machine, tubing, power supply — mask sold separately"]] },
  { slug: "luna-ii-auto-cpap-weekly-rental", name: "Luna II Auto CPAP - Weekly Rental", brand: "3B Medical", category: "cpap-rental", price: 348, badge: "Rental", rxRequired: true , image: "/products/luna-ii-auto-cpap.jpg" , specs: [["Rental Term", "Weekly"], ["Pressure Range", "4-20 cm H2O"], ["Weight", "4 lbs (1.9 kg)"], ["Dimensions", "10.75\" x 7.25\" x 4.5\""], ["Humidifier", "Integrated, heated (360 mL)"], ["Includes", "Machine, tubing, power supply — mask sold separately"]] },
  { slug: "luna-ii-auto-cpap-monthly-rental", name: "Luna II Auto CPAP - Monthly Rental", brand: "3B Medical", category: "cpap-rental", price: 600, badge: "Rental", rxRequired: true , image: "/products/luna-ii-auto-cpap.jpg" , specs: [["Rental Term", "Monthly"], ["Pressure Range", "4-20 cm H2O"], ["Weight", "4 lbs (1.9 kg)"], ["Dimensions", "10.75\" x 7.25\" x 4.5\""], ["Humidifier", "Integrated, heated (360 mL)"], ["Includes", "Machine, tubing, power supply — mask sold separately"]] },
];

/** Highest price first (nulls/"Call for Pricing" last) — an honest proxy for
 *  "highest-value item first" since real margin data isn't available. */
function byValueDesc(a: Product, b: Product) {
  if (a.price === null && b.price === null) return 0;
  if (a.price === null) return 1;
  if (b.price === null) return -1;
  return b.price - a.price;
}

export const productsByCategory = (category: Category) =>
  PRODUCTS.filter((p) => p.category === category).sort(byValueDesc);

export function getProduct(category: Category, slug: string) {
  return PRODUCTS.find((p) => p.category === category && p.slug === slug);
}

/** Looks up a product by its URL base segment + slug, spanning categories that share a base (e.g. sleep-cpap + sleep-travel both live under /sleep/cpap). */
export function getProductByBase(base: string, slug: string) {
  return PRODUCTS.find((p) => CATEGORY_META[p.category].base === base && p.slug === slug);
}

export function productsByBase(base: string) {
  return PRODUCTS.filter((p) => CATEGORY_META[p.category].base === base).sort(byValueDesc);
}

/** Real accessories to cross-sell on a machine's PDP — sourced entirely from
 * each accessory's own disclosed "Compatibility" spec field, never a
 * fabricated or inferred pairing. Most accessories in the catalog don't
 * carry a Compatibility field at all, so this only surfaces something for
 * the specific models that actually have one on file. */
export function compatibleAccessories(product: Product): Product[] {
  return PRODUCTS.filter((p) => {
    if (!p.specs) return false;
    const compat = p.specs.find(([label]) => label === "Compatibility")?.[1];
    if (!compat) return false;
    return compat
      .split(",")
      .map((model) => model.trim().toLowerCase())
      .some((model) => product.name.toLowerCase().includes(model) || model === "most cpap/bipap");
  }).filter((p) => {
    // "Most CPAP/BiPAP" accessories only make sense cross-sold on sleep
    // machines, not oxygen equipment — the field says "most", not "all",
    // so this is deliberately scoped to the category it's actually about.
    const compat = p.specs!.find(([label]) => label === "Compatibility")![1];
    if (compat.toLowerCase() === "most cpap/bipap") {
      return product.category === "sleep-cpap" || product.category === "sleep-bipap";
    }
    return true;
  });
}

export function productHref(p: Pick<Product, "category" | "slug">) {
  return href(p);
}

/** Top-level section a product's breadcrumb belongs to, derived from its base path's first segment. */
export function productSection(p: Pick<Product, "category">): { name: string; url: string } {
  const base = CATEGORY_META[p.category].base;
  const firstSegment = "/" + base.split("/")[1];
  const names: Record<string, string> = {
    "/oxygen": "Oxygen",
    "/sleep": "Sleep",
    "/respiratory-accessories": "Respiratory Accessories",
    "/ventilators": "Ventilators",
    "/rentals": "Rentals",
  };
  return { name: names[firstSegment] ?? firstSegment.slice(1), url: firstSegment };
}

// Descriptive alt text for image search — real category label, not a fabricated description.
export function productAltText(p: Pick<Product, "name" | "category">) {
  return `${p.name} — ${CATEGORY_META[p.category].label}`;
}

export function formatPrice(n: number) {
  return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(n);
}

/** Parses a real disclosed weight spec ("4.8 lbs (standard battery)") into
 * pounds, or a real disclosed battery-life spec ("6-13 hours") into its
 * upper-bound hours. Returns null on anything that doesn't cleanly match —
 * never estimates or falls back to a guessed number. */
function parseLeadingNumber(value: string): number | null {
  const match = value.match(/(\d+(?:\.\d+)?)/);
  return match ? Number(match[1]) : null;
}

function parseUpperBoundNumber(value: string): number | null {
  const matches = value.match(/\d+(?:\.\d+)?/g);
  if (!matches || matches.length === 0) return null;
  return Number(matches[matches.length - 1]);
}

export type WeightPerBatteryHour = { weightLbs: number; maxHours: number; lbsPerHour: number };

/** Weight-per-hour-of-runtime, computed only from this product's own
 * disclosed "Weight" and "Battery Life" spec rows. Returns null if either
 * spec is missing or doesn't parse cleanly — a comparison this site can't
 * verify from real numbers doesn't get published, not even a rounded one. */
export function weightPerBatteryHour(p: Pick<Product, "specs">): WeightPerBatteryHour | null {
  const weightSpec = p.specs?.find(([label]) => label === "Weight")?.[1];
  const batterySpec = p.specs?.find(([label]) => label === "Battery Life")?.[1];
  if (!weightSpec || !batterySpec) return null;
  const weightLbs = parseLeadingNumber(weightSpec);
  const maxHours = parseUpperBoundNumber(batterySpec);
  if (weightLbs === null || maxHours === null || maxHours === 0) return null;
  return { weightLbs, maxHours, lbsPerHour: Math.round((weightLbs / maxHours) * 100) / 100 };
}

/** Rental SKU → purchase SKU of the same physical device. Every pairing
 * mirrors the catalog's own reuse of that device's specs and photo — no
 * pairing is asserted that the catalog doesn't already embody. Powers the
 * rent-vs-buy crossover table and isRelatedTo schema edges. Luna II rentals
 * are intentionally unmapped: the catalog carries no purchase SKU for it. */
export const RENTAL_PURCHASE_EQUIVALENT: Record<string, string> = {
  "inogen-rove-6-weekly-rental": "inogen-rove-6",
  "inogen-rove-6-monthly-rental": "inogen-rove-6",
  "inogen-rove-4-weekly-rental": "inogen-rove-4",
  "inogen-rove-4-monthly-rental": "inogen-rove-4",
  "caire-freestyle-comfort-weekly-rental": "caire-freestyle-comfort",
  "caire-freestyle-comfort-monthly-rental": "caire-freestyle-comfort",
  "caire-eclipse-5-weekly-rental": "caire-eclipse-5",
  "caire-eclipse-5-monthly-rental": "caire-eclipse-5",
  "philips-home-concentrator-5l-weekly-rental": "philips-everflo",
  "philips-home-concentrator-5l-monthly-rental": "philips-everflo",
  "caire-home-concentrator-10l-weekly-rental": "caire-newlife-intensity-10",
  "caire-home-concentrator-10l-monthly-rental": "caire-newlife-intensity-10",
  "resmed-airsense-11-weekly-rental": "resmed-airsense-11-autoset",
  "resmed-airsense-11-monthly-rental": "resmed-airsense-11-autoset",
  "f-p-sleepstyle-weekly-rental": "f-p-sleepstyle",
  "f-p-sleepstyle-monthly-rental": "f-p-sleepstyle",
  "resmed-airmini-weekly-rental": "resmed-airmini",
  "resmed-airmini-monthly-rental": "resmed-airmini",
  "transcend-365-weekly-rental": "transcend-365-auto",
  "transcend-365-monthly-rental": "transcend-365-auto",
  "luna-ii-auto-cpap-weekly-rental": "luna-ii-auto-cpap",
  "luna-ii-auto-cpap-monthly-rental": "luna-ii-auto-cpap",
  "resmed-aircurve-10-vauto-weekly-rental": "resmed-aircurve-10-vauto",
  "resmed-aircurve-10-vauto-monthly-rental": "resmed-aircurve-10-vauto",
  "resmed-aircurve-10-st-weekly-rental": "resmed-aircurve-10-st",
  "resmed-aircurve-10-st-monthly-rental": "resmed-aircurve-10-st",
  "philips-dreamstation-bipap-weekly-rental": "philips-dreamstation-bipap",
  "philips-dreamstation-bipap-monthly-rental": "philips-dreamstation-bipap",
};

export type RentVsBuyRow = {
  deviceName: string;
  purchaseSlug: string;
  rentalSlug: string;
  purchasePrice: number;
  monthlyRental: number;
  breakevenMonths: number;
};

/** Rent-vs-buy crossover rows, computed live from catalog prices so the
 * table can never drift from what the PDPs actually charge. Only pairs
 * where both prices are real numbers qualify — call-for-pricing SKUs on
 * either side are excluded rather than estimated. */
export function rentVsBuyRows(): RentVsBuyRow[] {
  const rows: RentVsBuyRow[] = [];
  for (const [rentalSlug, purchaseSlug] of Object.entries(RENTAL_PURCHASE_EQUIVALENT)) {
    if (!rentalSlug.endsWith("-monthly-rental")) continue;
    const rental = PRODUCTS.find((p) => p.slug === rentalSlug);
    const purchase = PRODUCTS.find((p) => p.slug === purchaseSlug);
    if (!rental || !purchase || rental.price === null || purchase.price === null) continue;
    rows.push({
      deviceName: purchase.name,
      purchaseSlug,
      rentalSlug,
      purchasePrice: purchase.price,
      monthlyRental: rental.price,
      breakevenMonths: Math.round((purchase.price / rental.price) * 10) / 10,
    });
  }
  return rows.sort((a, b) => a.breakevenMonths - b.breakevenMonths);
}
